require "json"

module NoirTechs
  TECHS = {
    :crystal_amber => {
      :framework => "Amber",
      :language  => "Crystal",
      :similar   => ["amber", "crystal-amber", "crystal_amber"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => true,
      },
    },
    :crystal_kemal => {
      :framework => "Kemal",
      :language  => "Crystal",
      :similar   => ["kemal", "crystal-kemal", "crystal_kemal"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :crystal_lucky => {
      :framework => "Lucky",
      :language  => "Crystal",
      :similar   => ["lucky", "crystal-lucky", "crystal_lucky"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :crystal_marten => {
      :framework => "Marten",
      :language  => "Crystal",
      :similar   => ["marten", "crystal-marten", "crystal_marten"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :crystal_grip => {
      :framework => "Grip",
      :language  => "Crystal",
      :similar   => ["grip", "crystal-grip", "crystal_grip"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :cs_aspnet_mvc => {
      :framework => "ASP.NET MVC",
      :language  => "C#",
      :similar   => ["asp.net mvc", "cs-aspnet-mvc", "cs_aspnet_mvc", "c# asp.net mvc", "c#-asp.net-mvc", "c#_aspnet_mvc"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :cs_aspnet_core_mvc => {
      :framework => "ASP.NET Core MVC",
      :language  => "C#",
      :similar   => ["asp.net core mvc", "asp.net core", "aspnetcore", "cs-aspnet-core-mvc", "cs_aspnet_core_mvc", "c# asp.net core mvc", "c#-asp.net-core-mvc", "c#_aspnet_core_mvc"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :elixir_phoenix => {
      :framework => "Phoenix",
      :language  => "Elixir",
      :similar   => ["phoenix", "elixir-phoenix", "elixir_phoenix"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :elixir_plug => {
      :framework => "Plug",
      :language  => "Elixir",
      :similar   => ["plug", "elixir-plug", "elixir_plug"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :go_beego => {
      :framework => "Beego",
      :language  => "Go",
      :similar   => ["beego", "go-beego", "go_beego"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :go_echo => {
      :framework => "Echo",
      :language  => "Go",
      :similar   => ["echo", "go-echo", "go_echo"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :go_fasthttp => {
      :framework => "fasthttp",
      :language  => "Go",
      :similar   => ["fasthttp", "go-fasthttp", "go_fasthttp"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :go_fiber => {
      :framework => "Fiber",
      :language  => "Go",
      :similar   => ["fiber", "go-fiber", "go_fiber"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :go_gin => {
      :framework => "Gin",
      :language  => "Go",
      :similar   => ["gin", "go-gin", "go_gin"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
      },
    },
    :go_chi => {
      :framework => "Chi",
      :language  => "Go",
      :similar   => ["chi", "go-chi", "go_chi"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :go_gozero => {
      :framework => "go-zero",
      :language  => "Go",
      :similar   => ["go-zero", "gozero", "go_gozero"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :go_mux => {
      :framework => "Gorilla Mux",
      :language  => "Go",
      :similar   => ["mux", "go-mux", "go_mux", "gorilla-mux", "gorilla_mux"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :har => {
      :format    => ["JSON"],
      :similar   => ["har"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
      },
    },
    :java_armeria => {
      :framework => "Armeria",
      :language  => "Java",
      :similar   => ["armeria", "java-armeria", "java_armeria"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :java_jsp => {
      :framework => "JSP",
      :language  => "Java",
      :similar   => ["jsp", "java-jsp", "java_jsp"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => false,
          :cookie => false,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :java_spring => {
      :framework => "Spring",
      :language  => "Java",
      :similar   => ["spring", "java-spring", "java_spring"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :java_vertx => {
      :framework => "Vert.x",
      :language  => "Java",
      :similar   => ["vertx", "vert.x", "java-vertx", "java_vertx"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :js_express => {
      :framework => "Express",
      :language  => "JavaScript",
      :similar   => ["express", "js-express", "js_express"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :js_restify => {
      :framework => "Restify",
      :language  => "JavaScript",
      :similar   => ["restify", "js-restify"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :js_fastify => {
      :framework => "Fastify",
      :language  => "JavaScript",
      :similar   => ["fastify", "js-fastify"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :js_koa => {
      :framework => "Koa",
      :language  => "JavaScript",
      :similar   => ["koa", "js-koa"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :js_nestjs => {
      :framework => "NestJS",
      :language  => "JavaScript",
      :similar   => ["nestjs", "nest", "js-nestjs", "js_nestjs"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :ts_nestjs => {
      :framework => "NestJS",
      :language  => "TypeScript",
      :similar   => ["typescript-nestjs", "ts-nestjs", "ts_nestjs"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :js_vuejs => {
      :framework => "Vue.js",
      :language  => "JavaScript",
      :similar   => ["vuejs", "vue", "vue.js", "js-vuejs", "js_vuejs"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :kotlin_spring => {
      :framework => "Spring",
      :language  => "Kotlin",
      :similar   => ["spring", "kotlin-spring", "kotlin_spring"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :kotlin_ktor => {
      :framework => "Ktor",
      :language  => "Kotlin",
      :similar   => ["ktor", "kotlin-ktor", "kotlin_ktor"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :oas2 => {
      :format    => ["JSON", "YAML"],
      :similar   => ["oas 2.0", "oas_2_0", "swagger 2.0", "swagger_2_0", "swagger"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
      },
    },
    :oas3 => {
      :format    => ["JSON", "YAML"],
      :similar   => ["oas 3.0", "oas_3_0"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
      },
    },
    :graphql => {
      :format    => ["GRAPHQL"],
      :similar   => ["graphql", ".graphql"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
      },
    },
    :php_pure => {
      :framework => "",
      :language  => "PHP",
      :similar   => ["php", "php-pure", "php_pure"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :php_laravel => {
      :framework => "Laravel",
      :language  => "PHP",
      :similar   => ["laravel", "php-laravel", "php_laravel"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :php_symfony => {
      :framework => "Symfony",
      :language  => "PHP",
      :similar   => ["symfony", "php-symfony", "php_symfony"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_django => {
      :framework => "Django",
      :language  => "Python",
      :similar   => ["django", "python-django", "python_django"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :python_fastapi => {
      :framework => "FastAPI",
      :language  => "Python",
      :similar   => ["fastapi", "python-fastapi", "python_fastapi"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_flask => {
      :framework => "Flask",
      :language  => "Python",
      :similar   => ["flask", "python-flask", "python_flask"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_sanic => {
      :framework => "Sanic",
      :language  => "Python",
      :similar   => ["sanic", "python-sanic", "python_sanic"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :python_tornado => {
      :framework => "Tornado",
      :language  => "Python",
      :similar   => ["tornado", "python-tornado", "python_tornado"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :postman => {
      :format    => ["JSON"],
      :similar   => ["postman", "postman collection"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
      },
    },
    :raml => {
      :format    => ["YAML"],
      :similar   => ["raml"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
      },
    },
    :ruby_hanami => {
      :framework => "Hanami",
      :language  => "Ruby",
      :similar   => ["hanami", "ruby-hanami", "ruby_hanami"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :ruby_rails => {
      :framework => "Rails",
      :language  => "Ruby",
      :similar   => ["rails", "ruby-rails", "ruby_rails"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :ruby_sinatra => {
      :framework => "Sinatra",
      :language  => "Ruby",
      :similar   => ["sinatra", "ruby-sinatra", "ruby_sinatra"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :rust_axum => {
      :framework => "Axum",
      :language  => "Rust",
      :similar   => ["axum", "rust-axum", "rust_axum"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :rust_rocket => {
      :framework => "Rocket",
      :language  => "Rust",
      :similar   => ["rocket", "rust-rocket", "rust_rocket"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => false,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :rust_actix_web => {
      :framework => "Actix Web",
      :language  => "Rust",
      :similar   => ["actix-web", "actix_web", "rust-actix-web", "rust_actix_web"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :rust_loco => {
      :framework => "Loco",
      :language  => "Rust",
      :similar   => ["loco", "loco-rs", "rust-loco", "rust_loco"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :rust_rwf => {
      :framework => "RWF",
      :language  => "Rust",
      :similar   => ["rwf", "rust-rwf", "rust_rwf"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :rust_tide => {
      :framework => "Tide",
      :language  => "Rust",
      :similar   => ["tide", "rust-tide", "rust_tide"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :rust_warp => {
      :framework => "Warp",
      :language  => "Rust",
      :similar   => ["warp", "rust-warp", "rust_warp"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :rust_gotham => {
      :framework => "Gotham",
      :language  => "Rust",
      :similar   => ["gotham", "rust-gotham", "rust_gotham"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => false,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :scala_akka => {
      :framework => "Akka HTTP",
      :language  => "Scala",
      :similar   => ["akka", "akka-http", "akka_http", "scala-akka", "scala_akka"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :scala_scalatra => {
      :framework => "Scalatra",
      :language  => "Scala",
      :similar   => ["scalatra", "scala-scalatra", "scala_scalatra"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :scala_play => {
      :framework => "Play Framework",
      :language  => "Scala",
      :similar   => ["play", "play-framework", "scala-play", "scala_play"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :java_play => {
      :framework => "Play Framework",
      :language  => "Java",
      :similar   => ["play", "play-framework", "java-play", "java_play"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :swift_vapor => {
      :framework => "Vapor",
      :language  => "Swift",
      :similar   => ["vapor", "swift-vapor", "swift_vapor"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :swift_kitura => {
      :framework => "Kitura",
      :language  => "Swift",
      :similar   => ["kitura", "swift-kitura", "swift_kitura"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :swift_hummingbird => {
      :framework => "Hummingbird",
      :language  => "Swift",
      :similar   => ["hummingbird", "swift-hummingbird", "swift_hummingbird"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
  }

  def self.techs
    TECHS
  end

  def self.similar_to_tech(word)
    TECHS.each do |key, value|
      if value[:similar].includes? word.downcase
        return key.to_s
      end
    end

    ""
  end
end

if __FILE__ == PROGRAM_NAME
  # When running this file directly (e.g., `crystal run src/techs/techs.cr`),
  # print the TECHS catalog as JSON. This block does not run when the file is
  # required from other code (e.g., Noir's main application).
  puts NoirTechs::TECHS.to_json
end
