Metrics/CyclomaticComplexity:
  Enabled: false

# Disable spec filename check for fixture files (they represent real code)
Lint/SpecFilename:
  Excluded:
    - "spec/functional_test/fixtures/**/*"

# Disable useless assign warnings for fixture files
Lint/UselessAssign:
  Excluded:
    - "spec/functional_test/fixtures/**/*"

# Allow common short block parameter names used throughout the codebase
Naming/BlockParameterName:
  Enabled: false
