{
  description = "Hunt every Endpoint in your code, expose Shadow APIs, map the Attack Surface";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
    }:
    let
      # Written as a function of `pkgs` so one expression backs both this
      # flake's own package and `overlays.default`, which has to build against
      # whichever nixpkgs a consumer overlays it onto.
      mkNoir =
        pkgs:
        let
          inherit (pkgs) lib;

          # Only the files the compiler actually reads. `./.` pulls the whole
          # tree into the store — including the 16MB spec fixture corpus and
          # the docs site — so a docs-only commit changed the derivation hash
          # and cost every Nix user a full release rebuild.
          source = lib.fileset.toSource {
            root = ./.;
            fileset = lib.fileset.unions [
              ./src
              ./shard.yml
              ./shard.lock
              ./README.md
              ./LICENSE
            ];
          };
        in
        pkgs.crystal.buildCrystalPackage {
          pname = "noir";
          version = "1.3.0";

          src = source;

          # Build through shards rather than a hand-written `crystal build`, so
          # the target list stays in shard.yml alone. `shardsFile` pins every
          # dependency by rev and hash; it is generated by `just nix-update`
          # and kept honest by `just nix-check`, which CI runs.
          format = "shards";
          shardsFile = ./shards.nix;

          # The flags every other official build uses (justfile `build-release`,
          # Dockerfile, snapcraft, release binaries). Without them the Nix build
          # was the only one shipping a debug binary.
          options = [
            "--release"
            "--no-debug"
          ];

          # The spec suite needs the fixture corpus that `source` above leaves
          # out on purpose, and CI runs it on every push.
          doCheck = false;

          meta = {
            description = "OWASP Noir: Hunt every Endpoint in your code, expose Shadow APIs, map the Attack Surface";
            homepage = "https://github.com/owasp-noir/noir";
            license = lib.licenses.mit;
            mainProgram = "noir";
            maintainers = [
              {
                name = "hahwul";
                github = "hahwul";
                githubId = 13212227;
              }
              {
                name = "ksg97031";
                github = "ksg97031";
                githubId = 6715194;
              }
            ];
          };
        };
    in
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
        noir = mkNoir pkgs;
      in
      {
        packages = {
          inherit noir;
          default = noir;
        };

        # Makes `nix flake check` build the package instead of only evaluating
        # the flake.
        checks.noir = noir;

        formatter = pkgs.nixfmt;

        devShells.default = pkgs.mkShell {
          inputsFrom = [ noir ];
          packages = with pkgs; [
            crystal
            shards
            crystal2nix
            just
            git
          ];
          # Deliberately no `shards install` here: entering a shell should not
          # reach the network or write into the checkout behind the user's back.
          shellHook = ''
            echo "OWASP Noir dev shell — $(crystal --version | head -n 1)"
            echo "  shards install   # once, to populate ./lib"
            echo "  just build       # or: just build-release, just test"
          '';
        };
      }
    )
    // {
      # For consumers who would rather compose Noir into their own nixpkgs than
      # depend on this flake's per-system outputs.
      overlays.default = final: _prev: { noir = mkNoir final; };
    };
}
