# NoirTechs catalog: go technologies.
# Entry shape and helpers live in src/techs/techs.cr, which
# merges every Catalog constant into NoirTechs::TECHS.
module NoirTechs::Catalog
  GO = {
    :go_gf => {
      :framework => "GoFrame",
      :language  => "Go",
      :similar   => ["gf", "goframe", "go-gf", "go_gf", "gogf/gf"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_beego => {
      :framework => "Beego",
      :language  => "Go",
      :similar   => ["beego", "go-beego", "go_beego"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_cli => {
      :framework => "CLI (flag / cobra / urfave / pflag / go-arg / go-flags / kong / kingpin / mitchellh)",
      :language  => "Go",
      :similar   => ["go-cli", "go_cli", "cobra", "urfave", "go-arg", "go-flags", "pflag", "kong", "kingpin", "mitchellh-cli"],
      :supported => {
        :endpoint => true,
        # CLI endpoints carry the synthetic "CLI" verb, not an HTTP method,
        # and their inputs are flag/argument/env params, which are outside
        # the HTTP query/path/body/header/cookie buckets the docs table
        # tracks.
        :method => false,
        :params => {
          :query  => false,
          :path   => false,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :go_echo => {
      :framework => "Echo",
      :language  => "Go",
      :similar   => ["echo", "go-echo", "go_echo"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_fasthttp => {
      :framework => "fasthttp",
      :language  => "Go",
      :similar   => ["fasthttp", "go-fasthttp", "go_fasthttp"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_fiber => {
      :framework => "Fiber",
      :language  => "Go",
      :similar   => ["fiber", "go-fiber", "go_fiber"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_gin => {
      :framework => "Gin",
      :language  => "Go",
      :similar   => ["gin", "go-gin", "go_gin"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_hertz => {
      :framework => "Hertz",
      :language  => "Go",
      :similar   => ["hertz", "go-hertz", "go_hertz", "cloudwego"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_iris => {
      :framework => "Iris",
      :language  => "Go",
      :similar   => ["iris", "go-iris", "go_iris", "kataras"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_restful => {
      :framework => "go-restful",
      :language  => "Go",
      :similar   => ["go-restful", "go_restful", "restful", "emicklei", "emicklei/go-restful"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_chi => {
      :framework => "Chi",
      :language  => "Go",
      :similar   => ["chi", "go-chi", "go_chi"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_gozero => {
      :framework => "go-zero",
      :language  => "Go",
      :similar   => ["go-zero", "gozero", "go_gozero"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_goyave => {
      :framework => "Goyave",
      :language  => "Go",
      :similar   => ["goyave", "go-goyave", "go_goyave"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_http => {
      :framework => "net/http",
      :language  => "Go",
      :similar   => ["http", "net/http", "go-http", "go_http", "stdlib-http", "std/http"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => false,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_mux => {
      :framework => "Gorilla Mux",
      :language  => "Go",
      :similar   => ["mux", "go-mux", "go_mux", "gorilla-mux", "gorilla_mux"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :go_connect_rpc => {
      :framework => "Connect-RPC",
      :language  => "Go",
      :similar   => ["connect", "connect-rpc", "connect_rpc", "connectrpc", "go-connect", "go_connect_rpc"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => false,
          :body   => true,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :go_pocketbase => {
      :framework => "PocketBase",
      :language  => "Go",
      :similar   => ["pocketbase", "go-pocketbase", "go_pocketbase"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :go_httprouter => {
      :framework => "httprouter",
      :language  => "Go",
      :similar   => ["httprouter", "go-httprouter", "go_httprouter", "julienschmidt-httprouter"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :go_huma => {
      :framework => "Huma",
      :language  => "Go",
      :similar   => ["huma", "go-huma", "go_huma", "danielgtaylor-huma"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
  }
end
