# NoirTechs catalog: java technologies.
# Entry shape and helpers live in src/techs/techs.cr, which
# merges every Catalog constant into NoirTechs::TECHS.
module NoirTechs::Catalog
  JAVA = {
    :java_cli => {
      :framework => "CLI (picocli / args4j / JCommander / commons-cli / airline / JOpt Simple)",
      :language  => "Java",
      :similar   => ["java-cli", "java_cli", "picocli", "args4j", "jcommander", "commons-cli", "airline", "jopt-simple", "joptsimple"],
      :supported => {
        :endpoint => true,
        :method   => false,
        :params   => {
          :query  => false,
          :path   => false,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :java_armeria => {
      :framework => "Armeria",
      :language  => "Java",
      :similar   => ["armeria", "java-armeria", "java_armeria"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :java_dropwizard => {
      :framework => "Dropwizard",
      :language  => "Java",
      :similar   => ["dropwizard", "java-dropwizard", "java_dropwizard"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_httpserver => {
      :framework => "JDK HttpServer",
      :language  => "Java",
      :similar   => ["jdk-httpserver", "java-httpserver", "java_httpserver", "com.sun.net.httpserver", "jdk.httpserver"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => false,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_jaxrs => {
      :framework => "JAX-RS",
      :language  => "Java",
      :similar   => ["jaxrs", "jax-rs", "jakarta-rest", "java-jaxrs", "java_jaxrs"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_quarkus => {
      :framework => "Quarkus",
      :language  => "Java",
      :similar   => ["quarkus", "java-quarkus", "java_quarkus"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_javalin => {
      :framework => "Javalin",
      :language  => "Java",
      :similar   => ["javalin", "java-javalin", "java_javalin"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_spark => {
      :framework => "Spark Java",
      :language  => "Java",
      :similar   => ["spark", "spark-java", "java-spark", "java_spark"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_micronaut => {
      :framework => "Micronaut",
      :language  => "Java",
      :similar   => ["micronaut", "java-micronaut", "java_micronaut"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_jsp => {
      :framework => "JSP",
      :language  => "Java",
      :similar   => ["jsp", "java-jsp", "java_jsp"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => false,
          :cookie => false,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:guards => true},
    },
    :java_spring => {
      :framework => "Spring",
      :language  => "Java",
      :similar   => ["spring", "java-spring", "java_spring"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :java_struts2 => {
      :framework => "Apache Struts 2",
      :language  => "Java",
      :similar   => ["struts", "struts2", "apache-struts", "apache-struts2", "java-struts2", "java_struts2"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_vertx => {
      :framework => "Vert.x",
      :language  => "Java",
      :similar   => ["vertx", "vert.x", "java-vertx", "java_vertx"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :java_wicket => {
      :framework => "Apache Wicket",
      :language  => "Java",
      :similar   => ["wicket", "apache-wicket", "apache wicket", "java-wicket", "java_wicket"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :java_play => {
      :framework => "Play Framework",
      :language  => "Java",
      :similar   => ["play", "play-framework", "java-play", "java_play"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
  }
end
