# NoirTechs catalog: javascript technologies.
# Entry shape and helpers live in src/techs/techs.cr, which
# merges every Catalog constant into NoirTechs::TECHS.
module NoirTechs::Catalog
  JAVASCRIPT = {
    :js_cli => {
      :framework => "CLI (parseArgs / commander / yargs / cac / meow / minimist / citty / arg / command-line-args / getopts)",
      :language  => "JavaScript",
      :similar   => ["js-cli", "js_cli", "commander", "yargs", "cac", "meow", "minimist", "oclif", "clipanion", "sade", "citty", "arg", "command-line-args", "getopts"],
      :supported => {
        :endpoint => true,
        :method   => false,
        :params   => {
          :query  => false,
          :path   => false,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :js_adonisjs => {
      :framework => "AdonisJS",
      :language  => "JavaScript",
      :similar   => ["adonisjs", "adonis", "js-adonisjs", "js_adonisjs"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_astro => {
      :framework => "Astro",
      :language  => "JavaScript",
      :similar   => ["astro", "js-astro", "js_astro"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_elysia => {
      :framework => "Elysia",
      :language  => "JavaScript",
      :similar   => ["elysia", "js-elysia", "js_elysia", "bun-elysia"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_express => {
      :framework => "Express",
      :language  => "JavaScript",
      :similar   => ["express", "js-express", "js_express"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :js_socketio => {
      :framework => "Socket.IO",
      :language  => "JavaScript",
      :similar   => ["socket.io", "socketio", "socket-io", "js-socketio", "js_socketio"],
      :supported => {
        :endpoint => true,
        :method   => false,
        :params   => {
          :query  => false,
          :path   => false,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :js_restify => {
      :framework => "Restify",
      :language  => "JavaScript",
      :similar   => ["restify", "js-restify"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :js_remix => {
      :framework => "Remix",
      :language  => "JavaScript",
      :similar   => ["remix", "remix-run", "js-remix", "js_remix"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_sveltekit => {
      :framework => "SvelteKit",
      :language  => "JavaScript",
      :similar   => ["sveltekit", "svelte-kit", "js-sveltekit", "js_sveltekit"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_fastify => {
      :framework => "Fastify",
      :language  => "JavaScript",
      :similar   => ["fastify", "js-fastify"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :js_fresh => {
      :framework => "Fresh",
      :language  => "JavaScript",
      :similar   => ["fresh", "js-fresh", "js_fresh", "deno-fresh"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_hapi => {
      :framework => "Hapi",
      :language  => "JavaScript",
      :similar   => ["hapi", "js-hapi", "js_hapi", "@hapi/hapi"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_apollo => {
      :framework => "Apollo Server",
      :language  => "JavaScript",
      :similar   => ["apollo", "apollo-server", "apollo_server", "js-apollo", "@apollo/server"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => false,
          :body   => true,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => true,
      },
      :context => {:callee => true},
    },
    :js_graphql_yoga => {
      :framework => "GraphQL Yoga",
      :language  => "JavaScript",
      :similar   => ["graphql-yoga", "graphql_yoga", "yoga", "js-graphql-yoga", "@graphql-yoga/node"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => false,
          :body   => true,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :js_hono => {
      :framework => "Hono",
      :language  => "JavaScript",
      :similar   => ["hono", "js-hono"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :js_http => {
      :framework => "Node.js http/https",
      :language  => "JavaScript",
      :similar   => ["js-http", "js_http", "node-http", "node-https", "nodejs-http", "nodejs-https", "node:http", "node:https"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => false,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :js_koa => {
      :framework => "Koa",
      :language  => "JavaScript",
      :similar   => ["koa", "js-koa"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :js_nestjs => {
      :framework => "NestJS",
      :language  => "JavaScript",
      :similar   => ["nestjs", "nest", "js-nestjs", "js_nestjs"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :js_nextjs => {
      :framework => "Next.js",
      :language  => "JavaScript",
      :similar   => ["nextjs", "next.js", "next", "js-nextjs", "js_nextjs"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_nitro => {
      :framework => "Nitro",
      :language  => "JavaScript",
      :similar   => ["nitro", "nitrojs", "nitropack", "js-nitro", "js_nitro"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :js_nuxtjs => {
      :framework => "NuxtJS",
      :language  => "JavaScript",
      :similar   => ["nuxtjs", "nuxt", "js-nuxtjs", "js_nuxtjs"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
  }
end
