# NoirTechs catalog: php technologies.
# Entry shape and helpers live in src/techs/techs.cr, which
# merges every Catalog constant into NoirTechs::TECHS.
module NoirTechs::Catalog
  PHP = {
    :php_cli => {
      :framework => "CLI (symfony/console / getopt / artisan / wp-cli / robo)",
      :language  => "PHP",
      :similar   => ["php-cli", "php_cli", "symfony-console", "getopt", "climate", "minicli", "artisan", "illuminate-console", "wp-cli", "robo"],
      :supported => {
        :endpoint => true,
        :method   => false,
        :params   => {
          :query  => false,
          :path   => false,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :php_pure => {
      :framework => "Pure",
      :language  => "PHP",
      :similar   => ["php", "php-pure", "php_pure"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_laravel => {
      :framework => "Laravel",
      :language  => "PHP",
      :similar   => ["laravel", "php-laravel", "php_laravel"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_lumen => {
      :framework => "Lumen",
      :language  => "PHP",
      :similar   => ["lumen", "php-lumen", "php_lumen", "laravel/lumen", "laravel-lumen", "lumen-framework"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :php_mautic => {
      :framework => "Mautic",
      :language  => "PHP",
      :similar   => ["mautic", "php-mautic", "php_mautic", "mautic/core-lib"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :php_laminas => {
      :framework => "Laminas",
      :language  => "PHP",
      :similar   => ["laminas", "zend", "zend-framework", "zendframework", "php-laminas", "php_laminas", "laminas/laminas-mvc", "mezzio", "mezzio/mezzio"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_slim => {
      :framework => "Slim",
      :language  => "PHP",
      :similar   => ["slim", "slimframework", "slim-framework", "php-slim", "php_slim", "slim/slim"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_symfony => {
      :framework => "Symfony",
      :language  => "PHP",
      :similar   => ["symfony", "php-symfony", "php_symfony"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_yii => {
      :framework => "Yii2",
      :language  => "PHP",
      :similar   => ["yii", "yii2", "php-yii", "php_yii", "yiisoft", "yiisoft/yii2"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_thinkphp => {
      :framework => "ThinkPHP",
      :language  => "PHP",
      :similar   => ["thinkphp", "php-thinkphp", "php_thinkphp"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_cakephp => {
      :framework => "CakePHP",
      :language  => "PHP",
      :similar   => ["cakephp", "php-cakephp", "php_cakephp"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_codeigniter => {
      :framework => "CodeIgniter",
      :language  => "PHP",
      :similar   => ["codeigniter", "codeigniter4", "php-codeigniter", "php_codeigniter"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true, :guards => true},
    },
    :php_hyperf => {
      :framework => "Hyperf",
      :language  => "PHP",
      :similar   => ["hyperf", "php-hyperf", "php_hyperf", "hyperf/hyperf"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
      :context => {:callee => true},
    },
    :php_wordpress => {
      :framework => "WordPress",
      :language  => "PHP",
      :similar   => ["wordpress", "wp", "php-wordpress", "php_wordpress"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :php_drupal => {
      :framework => "Drupal",
      :language  => "PHP",
      :similar   => ["drupal", "php-drupal", "php_drupal", "drupal/core"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :php_magento => {
      :framework => "Magento",
      :language  => "PHP",
      :similar   => ["magento", "magento2", "php-magento", "php_magento", "magento/product-community-edition"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => false,
          :path   => true,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
  }
end
