# NoirTechs catalog: python technologies.
# Entry shape and helpers live in src/techs/techs.cr, which
# merges every Catalog constant into NoirTechs::TECHS.
module NoirTechs::Catalog
  PYTHON = {
    :python_django => {
      :framework => "Django",
      :language  => "Python",
      :similar   => ["django", "python-django", "python_django"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => true,
        :websocket   => false,
      },
    },
    :python_django_ninja => {
      :framework => "Django Ninja",
      :language  => "Python",
      :similar   => ["django-ninja", "django_ninja", "python-django-ninja", "python_django_ninja", "ninja"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_fastapi => {
      :framework => "FastAPI",
      :language  => "Python",
      :similar   => ["fastapi", "python-fastapi", "python_fastapi"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_aiohttp => {
      :framework => "aiohttp",
      :language  => "Python",
      :similar   => ["aiohttp", "python-aiohttp", "python_aiohttp"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :python_bottle => {
      :framework => "Bottle",
      :language  => "Python",
      :similar   => ["bottle", "bottlepy", "python-bottle", "python_bottle"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_cli => {
      :framework => "CLI (argparse / click / typer / fire / docopt / getopt / absl / cleo)",
      :language  => "Python",
      :similar   => ["python-cli", "python_cli", "argparse", "click", "typer", "fire", "docopt", "absl", "abseil", "cleo"],
      :supported => {
        :endpoint => true,
        # CLI endpoints carry the synthetic "CLI" verb, not an HTTP method,
        # and their inputs are flag/argument/env params, outside the HTTP
        # query/path/body/header/cookie buckets the docs table tracks.
        :method => false,
        :params => {
          :query  => false,
          :path   => false,
          :body   => false,
          :header => false,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_falcon => {
      :framework => "Falcon",
      :language  => "Python",
      :similar   => ["falcon", "falconframework", "python-falcon", "python_falcon"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_flask => {
      :framework => "Flask",
      :language  => "Python",
      :similar   => ["flask", "python-flask", "python_flask"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_litestar => {
      :framework => "Litestar",
      :language  => "Python",
      :similar   => ["litestar", "starlite", "python-litestar", "python_litestar"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :python_pyramid => {
      :framework => "Pyramid",
      :language  => "Python",
      :similar   => ["pyramid", "python-pyramid", "python_pyramid"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_quart => {
      :framework => "Quart",
      :language  => "Python",
      :similar   => ["quart", "python-quart", "python_quart"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :python_robyn => {
      :framework => "Robyn",
      :language  => "Python",
      :similar   => ["robyn", "python-robyn", "python_robyn"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => false,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :python_sanic => {
      :framework => "Sanic",
      :language  => "Python",
      :similar   => ["sanic", "python-sanic", "python_sanic"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :python_starlette => {
      :framework => "Starlette",
      :language  => "Python",
      :similar   => ["starlette", "python-starlette", "python_starlette"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
    :python_tornado => {
      :framework => "Tornado",
      :language  => "Python",
      :similar   => ["tornado", "python-tornado", "python_tornado"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => true,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => true,
      },
    },
    :python_http_server => {
      :framework => "http.server",
      :language  => "Python",
      :similar   => ["http.server", "python-http-server", "python_http_server", "BaseHTTPRequestHandler", "HTTPServer", "SimpleHTTPRequestHandler", "wsgiref.simple_server"],
      :supported => {
        :endpoint => true,
        :method   => true,
        :params   => {
          :query  => true,
          :path   => false,
          :body   => true,
          :header => true,
          :cookie => true,
        },
        :static_path => false,
        :websocket   => false,
      },
    },
  }
end
