require "../../engines/ruby_engine"

module Analyzer::Ruby
  class Rails < RubyEngine
    # Devise routes generated by `devise_for :scope`. Tuples are
    # {METHOD, sub_path} appended to the scope's base path.
    DEVISE_ROUTES = [
      {"GET", "/sign_in"},
      {"POST", "/sign_in"},
      {"DELETE", "/sign_out"},
      {"POST", ""},
      {"GET", "/sign_up"},
      {"GET", "/edit"},
      {"PUT", ""},
      {"PATCH", ""},
      {"DELETE", ""},
      {"GET", "/password/new"},
      {"POST", "/password"},
      {"GET", "/password/edit"},
      {"PUT", "/password"},
      {"PATCH", "/password"},
      {"GET", "/confirmation/new"},
      {"POST", "/confirmation"},
      {"GET", "/confirmation"},
      {"GET", "/unlock/new"},
      {"POST", "/unlock"},
      {"GET", "/unlock"},
    ]

    struct Frame
      property kind : Symbol
      property path : String
      property controller_subdir : String
      property resource_name : String?
      property controller_path : String?
      property controller_scope : String?

      def initialize(@kind : Symbol, @path : String = "", @controller_subdir : String = "",
                     @resource_name : String? = nil, @controller_path : String? = nil,
                     @controller_scope : String? = nil)
      end
    end

    record ControllerData,
      param_type : String,
      params_method : Hash(String, Array(Param)),
      params_body_by_action : Hash(String, Array(Param)),
      params_query_by_action : Hash(String, Array(Param)),
      defined_actions : Set(String),
      helper_calls_by_action : Hash(String, Array(String)),
      callees_by_action : Hash(String, Array(Noir::RubyCalleeExtractor::Entry)),
      action_lines : Hash(String, Int32)

    record ConcernResource,
      kind_kw : String,
      name : String,
      options : Hash(String, String),
      stack : Array(Frame)

    @controller_data_cache = Hash(String, ControllerData).new

    def analyze
      framework_roots = discover_framework_roots("config/routes.rb")
      framework_roots = [@base_path] if framework_roots.empty?

      framework_roots.each do |framework_root|
        begin
          get_public_files(framework_root).each do |file|
            if file =~ /\/public\/(.*)/
              relative_path = $1
              details = Details.new(PathInfo.new(file))
              @result << Endpoint.new("/#{relative_path}", "GET", details)
            end
          end
        rescue e
          logger.debug e
        end

        routes_path = "#{framework_root}/config/routes.rb"
        next unless File.exists?(routes_path)

        parse_routes_file(routes_path, framework_root)
      end

      @result
    end

    private def parse_routes_file(routes_path : String, framework_root : String)
      parsed_route_files = Set(String).new
      concern_resources = {} of String => Array(ConcernResource)
      parse_routes_file(routes_path, framework_root, parsed_route_files, [] of Frame, concern_resources)
    end

    private def parse_routes_file(routes_path : String, framework_root : String,
                                  parsed_route_files : Set(String),
                                  inherited_stack : Array(Frame),
                                  concern_resources : Hash(String, Array(ConcernResource)))
      expanded_routes_path = File.expand_path(routes_path)
      parse_key = route_file_parse_key(expanded_routes_path, inherited_stack)
      return if parsed_route_files.includes?(parse_key)
      parsed_route_files << parse_key

      details = Details.new(PathInfo.new(routes_path))
      stack = inherited_stack.dup
      # Routes files routinely DRY repeated prefixes into local
      # string vars (`base_c_route = "/c/:channel_title/:channel_id"`)
      # then use them with Ruby interpolation
      # (`get "#{base_c_route}/:message_id" => "ctrl#act"`). The
      # line-based parser saw the literal `#{base_c_route}` survive
      # into URLs. discourse/discourse alone parked ~153 phantom
      # routes with `#{...}` in them. Track the assignments as we
      # walk the file and expand interpolations before route
      # matching.
      local_string_vars = Hash(String, String).new
      logical_route_lines(routes_path).each do |raw_line|
        line = raw_line.strip
        next if line.empty?

        # Capture `name = "literal"` assignments at any nesting.
        # We only resolve simple string-literal RHS; anything more
        # complex (method calls, concatenation) stays opaque and
        # the original `#{...}` falls through unchanged.
        if assign = line.match(/^([a-z_][a-z0-9_]*)\s*=\s*["']([^"']+)["']\s*$/)
          local_string_vars[assign[1]] = assign[2]
        end

        # Expand interpolations in-place so downstream regexes
        # see the resolved path. We only substitute names we've
        # actually seen — unresolved `#{...}` survives, which is
        # better than producing an empty `/` placeholder.
        unless local_string_vars.empty?
          line = line.gsub(/\#\{([a-z_][a-z0-9_]*)\}/) do |match|
            name = $~[1]
            local_string_vars[name]? || match
          end
        end

        # Handle `end` (top of stack pops one).
        if line == "end" || line.starts_with?("end ") || line.starts_with?("end;") || line.starts_with?("end#")
          stack.pop unless stack.empty?
          next
        end

        opens_block = opens_do_block?(line)

        # Outermost: Rails.application.routes.draw do ... end
        if line.starts_with?("Rails.application.routes.draw")
          stack << Frame.new(:neutral) if opens_block
          next
        end

        # draw :admin / draw("api") loads config/routes/admin.rb inline.
        # Rails evaluates those files in the current mapper scope.
        if call = route_call(line, ["draw"])
          draw_names = parse_symbol_list(call[1])
          draw_names.each do |draw_name|
            draw_path = File.join(framework_root, "config", "routes", "#{draw_name}.rb")
            parse_routes_file(draw_path, framework_root, parsed_route_files, stack, concern_resources) if File.exists?(draw_path)
          end
          next
        end

        # concern :commentable do
        if call = route_call(line, ["concern"])
          next unless m = call[1].match(/^\s*:(\w+)/)
          name = m[1]
          concern_resources[name] ||= [] of ConcernResource
          stack << Frame.new(:concern, resource_name: name) if opens_block
          next
        end

        # namespace :foo do
        if call = route_call(line, ["namespace"])
          next unless m = call[1].match(/^\s*(?::(\w+)|['"]([^'"]+)['"])/)
          name = m[1]? || m[2]? || ""
          options = parse_options(call[1])
          namespace_path = options.has_key?("path") ? options["path"] : name
          stack << Frame.new(:namespace, path: namespace_path, controller_subdir: name) if opens_block
          next
        end

        # scope :name / scope "/admin" / scope path: ...
        if call = route_call(line, ["scope"])
          args = call[1]
          options = parse_options(args)
          scope_path = ""
          if m = args.match(/^\s*:(\w+)/)
            scope_path = m[1]
          elsif m = args.match(/^\s*['"]([^'"]+)['"]/)
            scope_path = m[1].lchop('/')
          elsif path_option = options["path"]?
            scope_path = path_option.lchop('/')
          end
          controller_subdir = options["module"]? || ""
          controller_scope = options["controller"]?
          stack << Frame.new(:scope, path: scope_path, controller_subdir: controller_subdir,
            controller_scope: controller_scope) if opens_block
          next
        end

        # controller :posts do ... end
        if call = route_call(line, ["controller"])
          controller_name = parse_first_route_name(call[1])
          stack << Frame.new(:controller, controller_scope: controller_name) if opens_block && controller_name
          next
        end

        # root "ctrl#action" / root to: "ctrl#action"
        if call = route_call(line, ["root"])
          rest = call[1]
          prefix = current_path_prefix(stack)
          url = prefix.empty? ? "/" : "/#{prefix}"
          ctrl_action = parse_controller_action(rest, current_controller_scope(stack))
          ctrl_path = nil.as(String?)
          action_name = nil.as(String?)
          if ctrl_action
            ctrl_name, action = ctrl_action
            ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
            action_name = action
          end
          parse_route_verbs(rest, ["GET"]).each do |root_verb|
            action_params = action_name ? params_for_action(ctrl_path, action_name, root_verb) : ([] of Param)
            endpoint = Endpoint.new(url, root_verb, action_params, details)
            attach_callees_for_action(endpoint, ctrl_path, action_name) if action_name
            @result << endpoint
          end
          next
        end

        # devise_for :users
        if call = route_call(line, ["devise_for"])
          next unless m = call[1].match(/^\s*:(\w+)/)
          scope_name = m[1]
          prefix = current_path_prefix(stack)
          base = prefix.empty? ? "/#{scope_name}" : "/#{prefix}/#{scope_name}"
          DEVISE_ROUTES.each do |verb, sub|
            @result << Endpoint.new("#{base}#{sub}", verb, details)
          end
          next
        end

        # mount Engine, at: "/path"  /  mount Engine => "/path"
        if call = route_call(line, ["mount"])
          rest = call[1]
          at_path = nil
          if m = rest.match(/at:\s*['"]([^'"]+)['"]/)
            at_path = m[1]
          elsif m = rest.match(/=>\s*['"]([^'"]+)['"]/)
            at_path = m[1]
          end
          if at_path
            prefix = current_path_prefix(stack)
            normalized = at_path.starts_with?("/") ? at_path : "/#{at_path}"
            url = prefix.empty? ? normalized : "/#{prefix}#{normalized}"
            @result << Endpoint.new(url, "GET", details)
          end
          next
        end

        # concerns :commentable / concerns [:commentable, :taggable]
        if call = route_call(line, ["concerns"])
          emit_concern_resources(parse_symbol_list(call[1]), concern_resources, framework_root, stack)
          next
        end

        # resources :foo / resource :foo
        if call = route_call(line, ["resources", "resource"])
          kind_kw = call[0]
          next unless name = parse_first_route_name(call[1])
          options = parse_options(call[1])

          if concern_name = current_concern_definition(stack)
            concern_resources[concern_name] ||= [] of ConcernResource
            concern_resources[concern_name] << ConcernResource.new(kind_kw, name, options, current_concern_relative_stack(stack))
            if opens_block
              url_segment = options["path"]? || name
              singular = (kind_kw == "resource")
              child_path = singular ? url_segment : "#{url_segment}/1"
              stack << Frame.new(:resources, path: child_path, resource_name: name)
            end
            next
          end

          existing_controller_path = emit_resource_routes(framework_root, stack, kind_kw, name, options)

          concern_names = parse_symbol_list(options["concerns"]?)
          unless concern_names.empty?
            url_segment = options["path"]? || name
            virtual_stack = stack.dup
            virtual_stack << Frame.new(:resources, path: (kind_kw == "resource" ? url_segment : "#{url_segment}/1"),
              resource_name: name, controller_path: existing_controller_path)
            emit_concern_resources(concern_names, concern_resources, framework_root, virtual_stack)
          end

          if opens_block
            url_segment = options["path"]? || name
            singular = (kind_kw == "resource")
            child_path = singular ? url_segment : "#{url_segment}/1"
            stack << Frame.new(:resources, path: child_path, resource_name: name,
              controller_path: existing_controller_path)
          end
          next
        end

        # member do / collection do
        if route_call(line, ["member"])
          stack << Frame.new(:member) if opens_block
          next
        end
        if route_call(line, ["collection"])
          stack << Frame.new(:collection) if opens_block
          next
        end
        if route_call(line, ["new"])
          stack << Frame.new(:new) if opens_block
          next
        end

        # HTTP verb routes
        if call = route_call(line, ["get", "post", "put", "patch", "delete", "head", "options"])
          verb = call[0].upcase
          rest = call[1]
          options = parse_options(rest)

          route_scope = options["on"]? || current_custom_route_scope(stack)
          in_collection = route_scope == "collection"
          in_member = route_scope == "member"
          in_new = route_scope == "new"

          # `get :action` form inside member/collection/new blocks, inline
          # `on:` declarations, or directly nested in a resources block.
          if (am = rest.match(/^\s*:(\w+)\b/)) && (in_member || in_collection || in_new || parent_resources_frame(stack))
            action = am[1]
            url = custom_resource_action_url(stack, action, route_scope)
            if url
              parent = parent_resources_frame(stack)
              action_params = parent ? params_for_action(parent.controller_path, action, verb) : ([] of Param)
              endpoint = Endpoint.new(url, verb, action_params, details)
              attach_callees_for_action(endpoint, parent.try(&.controller_path), action)
              @result << endpoint
            end
            next
          end

          # `get "path"` / `get "path" => "..."` / `get "path", to: "..."`
          if sm = rest.match(/^\s*['"]([^'"]+)['"]/)
            path = sm[1]
            prefix = current_path_prefix_for_route(stack, route_scope)
            path_part = path.starts_with?("/") ? path : "/#{path}"
            url = prefix.empty? ? path_part : "/#{prefix}#{path_part}"

            ctrl_action = parse_controller_action(rest, current_controller_scope(stack))
            action_params = [] of Param
            ctrl_path = nil.as(String?)
            action_name = nil.as(String?)
            if ctrl_action
              ctrl_name, action = ctrl_action
              ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
              action_name = action
              action_params = params_for_action(ctrl_path, action, verb)
            elsif parent = parent_resources_frame(stack)
              if action = infer_action_from_path(path)
                ctrl_path = parent.controller_path
                action_name = action
                action_params = params_for_action(ctrl_path, action, verb)
              end
            end

            endpoint = Endpoint.new(url, verb, action_params, details)
            attach_callees_for_action(endpoint, ctrl_path, action) if action = action_name
            @result << endpoint
            next
          end
          next
        end

        # `match` — Rails legacy multi-verb route. Requires `via:`
        # (or, on older codebases, defaults to ANY). Emits one
        # endpoint per verb listed under via, all sharing the
        # same path/controller#action.
        if call = route_call(line, ["match"])
          rest = call[1]
          if sm = rest.match(/^\s*['"]([^'"]+)['"]/)
            path = sm[1]
            prefix = current_path_prefix_for_route(stack, parse_options(rest)["on"]?)
            path_part = path.starts_with?("/") ? path : "/#{path}"
            url = prefix.empty? ? path_part : "/#{prefix}#{path_part}"

            match_verbs = parse_match_verbs(rest)
            ctrl_action = parse_controller_action(rest, current_controller_scope(stack))

            ctrl_path = nil.as(String?)
            action_name = nil.as(String?)
            if ctrl_action
              ctrl_name, action = ctrl_action
              ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
              action_name = action
            end

            match_verbs.each do |match_verb|
              action_params = if name = action_name
                                params_for_action(ctrl_path, name, match_verb)
                              else
                                [] of Param
                              end
              endpoint = Endpoint.new(url, match_verb, action_params, details)
              attach_callees_for_action(endpoint, ctrl_path, action_name) if action_name
              @result << endpoint
            end
          end
          next
        end

        # Unknown DSL line that still opens a block (e.g. `constraints ... do`).
        stack << Frame.new(:neutral) if opens_block
      end
    end

    private def current_concern_definition(stack : Array(Frame)) : String?
      if frame = stack.reverse.find { |f| f.kind == :concern }
        return frame.resource_name
      end
      nil
    end

    private def route_file_parse_key(path : String, stack : Array(Frame)) : String
      stack_key = stack.map do |frame|
        [
          frame.kind.to_s,
          frame.path,
          frame.controller_subdir,
          frame.resource_name || "",
          frame.controller_path || "",
          frame.controller_scope || "",
        ].join(":")
      end.join("|")

      "#{path}##{stack_key}"
    end

    private def logical_route_lines(routes_path : String) : Array(String)
      lines = [] of String
      buffer = ""
      paren_depth = 0
      bracket_depth = 0
      brace_depth = 0

      File.open(routes_path, "r", encoding: "utf-8", invalid: :skip) do |file|
        file.each_line do |raw_line|
          stripped = strip_inline_comment(raw_line).strip
          next if stripped.empty?

          buffer = buffer.empty? ? stripped : "#{buffer} #{stripped}"
          delta = delimiter_delta(stripped)
          paren_depth += delta[0]
          bracket_depth += delta[1]
          brace_depth += delta[2]

          next if paren_depth > 0 || bracket_depth > 0 || brace_depth > 0
          next if stripped.ends_with?(",")

          lines << buffer
          buffer = ""
          paren_depth = 0
          bracket_depth = 0
          brace_depth = 0
        end
      end

      lines << buffer unless buffer.empty?
      lines
    end

    private def delimiter_delta(line : String) : Tuple(Int32, Int32, Int32)
      paren = 0
      bracket = 0
      brace = 0
      in_str = false
      escaped = false
      quote = '\0'

      line.each_char do |c|
        if in_str
          if escaped
            escaped = false
          elsif c == '\\'
            escaped = true
          elsif c == quote
            in_str = false
          end
          next
        end

        if c == '"' || c == '\''
          in_str = true
          quote = c
          next
        end

        case c
        when '('
          paren += 1
        when ')'
          paren -= 1
        when '['
          bracket += 1
        when ']'
          bracket -= 1
        when '{'
          brace += 1
        when '}'
          brace -= 1
        end
      end

      {paren, bracket, brace}
    end

    private def route_call(line : String, names : Array(String)) : Tuple(String, String)?
      names.each do |name|
        next unless line.starts_with?(name)
        after = line[name.size, line.size - name.size]
        next if after.matches?(/\A[A-Za-z0-9_]/)

        stripped = after.lstrip
        if stripped.starts_with?("(")
          return {name, stripped[1, stripped.size - 1].strip}
        end
        return {name, stripped.strip}
      end
      nil
    end

    private def parse_first_route_name(args : String) : String?
      if m = args.match(/^\s*(?::([A-Za-z_]\w*)|['"]([^'"]+)['"])/)
        return (m[1]? || m[2]?).to_s
      end
      nil
    end

    private def current_custom_route_scope(stack : Array(Frame)) : String?
      if frame = stack.last?
        return frame.kind.to_s if frame.kind == :member || frame.kind == :collection || frame.kind == :new
      end
      nil
    end

    private def current_path_prefix_for_route(stack : Array(Frame), route_scope : String?) : String
      prefix = current_path_prefix(stack)
      return prefix if prefix.empty?

      case route_scope
      when "collection"
        prefix.ends_with?("/1") ? prefix[0, prefix.size - 2] : prefix
      when "new"
        prefix.ends_with?("/1") ? "#{prefix[0, prefix.size - 2]}/new" : "#{prefix}/new"
      else
        prefix
      end
    end

    private def custom_resource_action_url(stack : Array(Frame), action : String, route_scope : String?) : String?
      resources_idx = nil
      stack.each_with_index do |f, i|
        resources_idx = i if f.kind == :resources
      end
      return if resources_idx.nil?

      parts = [] of String
      stack[0, resources_idx].each do |f|
        parts << f.path unless f.path.empty?
      end

      rf = stack[resources_idx]
      seg = rf.path
      case route_scope
      when "collection"
        seg = seg[0, seg.size - 2] if seg.ends_with?("/1")
      when "new"
        seg = seg.ends_with?("/1") ? "#{seg[0, seg.size - 2]}/new" : "#{seg}/new"
      end

      parts << seg unless seg.empty?
      parts << action
      "/" + parts.join("/")
    end

    private def current_controller_scope(stack : Array(Frame)) : String?
      stack.reverse_each do |f|
        return f.controller_scope if f.controller_scope
      end
      nil
    end

    private def infer_action_from_path(path : String) : String?
      normalized = path.lchop("/")
      return normalized if normalized.matches?(/\A[A-Za-z_]\w*\z/)
      nil
    end

    private def current_concern_relative_stack(stack : Array(Frame)) : Array(Frame)
      index = stack.size - 1
      while index >= 0
        if stack[index].kind == :concern
          return [] of Frame if index == stack.size - 1
          return stack[(index + 1)..].dup
        end
        index -= 1
      end
      [] of Frame
    end

    private def emit_concern_resources(names : Array(String),
                                       concern_resources : Hash(String, Array(ConcernResource)),
                                       framework_root : String,
                                       stack : Array(Frame))
      names.each do |name|
        next unless resources = concern_resources[name]?
        resources.each do |resource|
          emit_resource_routes(framework_root, stack + resource.stack, resource.kind_kw, resource.name, resource.options)
        end
      end
    end

    private def emit_resource_routes(framework_root : String,
                                     stack : Array(Frame),
                                     kind_kw : String,
                                     name : String,
                                     options : Hash(String, String)) : String?
      singular = (kind_kw == "resource")
      controller_subdir = current_controller_subdir(stack)
      ctrl_override = options["controller"]?
      file_base = if ctrl_override
                    ctrl_override.includes?('/') ? ctrl_override : (controller_subdir.empty? ? ctrl_override : "#{controller_subdir}/#{ctrl_override}")
                  else
                    controller_subdir.empty? ? name : "#{controller_subdir}/#{name}"
                  end

      only_list = parse_symbol_list(options["only"]?)
      except_list = parse_symbol_list(options["except"]?)
      url_segment = options["path"]? || name
      path_prefix = current_path_prefix(stack)

      candidates = [] of String
      candidates << "#{framework_root}/app/controllers/#{file_base}_controller.rb"
      unless ctrl_override
        candidates << "#{framework_root}/app/controllers/#{file_base}s_controller.rb"
        candidates << "#{framework_root}/app/controllers/#{file_base}es_controller.rb"
      end

      existing_controller_path = candidates.find { |c| File.exists?(c) }
      candidates.each do |ctrl_path|
        @result += controller_to_endpoint(
          ctrl_path, @url, url_segment,
          path_prefix: path_prefix,
          only: only_list,
          except: except_list,
          singular: singular,
        )
      end

      existing_controller_path
    end

    # Pull the verb list out of a `match ... :via => :get` or
    # `match ... via: [:get, :post]` declaration. Returns the
    # single-element `["ANY"]` when `via:` is missing or empty —
    # modern Rails raises in that case but the older Redmine
    # idiom is permissive.
    private def parse_match_verbs(rest : String) : Array(String)
      parse_route_verbs(rest, ["ANY"])
    end

    private def parse_route_verbs(rest : String, default_verbs : Array(String)) : Array(String)
      via_match = rest.match(/:?via\s*(?:=>|:)\s*(\[[^\]]+\]|%i[\[\(][^\]\)]*[\]\)]|:\w+)/)
      return default_verbs unless via_match
      tail = via_match[1]
      verbs = [] of String
      parse_symbol_list(tail).each do |verb|
        normalized = verb.upcase
        normalized = "ANY" if normalized == "ALL"
        verbs << normalized
      end
      verbs.empty? ? default_verbs : verbs.uniq
    end

    private def strip_inline_comment(line : String) : String
      in_str = false
      escaped = false
      quote = '\0'
      line.each_char_with_index do |c, i|
        if in_str
          if escaped
            escaped = false
          elsif c == '\\'
            escaped = true
          elsif c == quote
            in_str = false
          end
        else
          if c == '"' || c == '\''
            in_str = true
            quote = c
          elsif c == '#'
            return line[0, i]
          end
        end
      end
      line
    end

    private def opens_do_block?(line : String) : Bool
      !!line.match(/\bdo\b\s*(\|[^|]*\|)?\s*\z/)
    end

    private def parse_options(line : String) : Hash(String, String)
      result = {} of String => String
      value_pattern = "nil|['\"][^'\"]+['\"]|:[a-zA-Z_]\\w*|\\[[^\\]]*\\]|%i[\\[\\(][^\\]\\)]*[\\]\\)]|%w[\\[\\(][^\\]\\)]*[\\]\\)]"
      # capture key: "value", key: :symbol, key: [..], key: %i[..], and
      # older hash-rocket forms like :only => [:index].
      line.scan(Regex.new("(\\w+):\\s*(#{value_pattern})")) do |m|
        key = m[1]
        result[key] = normalize_option_value(m[2])
      end
      line.scan(Regex.new(":(\\w+)\\s*=>\\s*(#{value_pattern})")) do |m|
        key = m[1]
        result[key] = normalize_option_value(m[2])
      end
      result
    end

    private def normalize_option_value(raw : String) : String
      return "" if raw == "nil"
      if raw.starts_with?('"') || raw.starts_with?('\'')
        raw[1, raw.size - 2]
      elsif raw.starts_with?(':')
        raw[1, raw.size - 1]
      elsif raw.starts_with?("%i") || raw.starts_with?("%w")
        raw[3, raw.size - 4]
      else
        raw[1, raw.size - 2] # strip [ ]
      end
    end

    private def parse_symbol_list(raw : String?) : Array(String)
      return [] of String if raw.nil?
      cleaned = raw.gsub(/%[iw][\[\(]/, "").gsub(/[\[\]\(\)'"]/, "")
      cleaned.split(/[,\s]+/).map(&.strip.lchop(':').strip).reject(&.empty?)
    end

    private def current_path_prefix(stack : Array(Frame)) : String
      parts = [] of String
      stack.each do |f|
        next if f.path.empty?
        parts << f.path
      end
      parts.join("/")
    end

    private def current_controller_subdir(stack : Array(Frame)) : String
      parts = [] of String
      stack.each do |f|
        next if f.controller_subdir.empty?
        parts << f.controller_subdir
      end
      parts.join("/")
    end

    # Build URL for a `get :action` inside member/collection blocks. For
    # member: uses the parent resource's `name/1` prefix; for collection:
    # strips the trailing `/1` so the action sits on the index URL.
    private def member_collection_url(stack : Array(Frame), action : String, in_collection : Bool) : String?
      resources_idx = nil
      stack.each_with_index do |f, i|
        resources_idx = i if f.kind == :resources
      end
      return if resources_idx.nil?

      parts = [] of String
      stack[0, resources_idx].each do |f|
        parts << f.path unless f.path.empty?
      end
      rf = stack[resources_idx]
      seg = rf.path
      if in_collection && seg.ends_with?("/1")
        seg = seg[0, seg.size - 2]
      end
      parts << seg unless seg.empty?
      parts << action
      "/" + parts.join("/")
    end

    def controller_to_endpoint(
      path : String,
      @url : String,
      resource : String,
      path_prefix : String = "",
      only : Array(String) = [] of String,
      except : Array(String) = [] of String,
      singular : Bool = false,
    )
      @result = [] of Endpoint

      return @result unless File.exists?(path)

      data = extract_controller_data(path)
      defined_actions = data.defined_actions

      methods = [] of String
      {"index", "show", "create", "update", "destroy"}.each do |name|
        next unless defined_actions.includes?(name)
        next unless action_allowed?(name, only, except)
        case name
        when "index"
          methods << "GET/INDEX" unless singular
        when "show"
          methods << "GET/SHOW"
        when "create"
          methods << "POST"
        when "update"
          methods << "PUT"
          methods << "PATCH"
        when "destroy"
          methods << "DELETE"
        end
      end

      index_url = compose_url(path_prefix, "/#{resource}")
      member_url = compose_url(path_prefix, singular ? "/#{resource}" : "/#{resource}/1")

      methods.each do |method|
        case method
        when "GET/INDEX"
          last_params = action_params(data, "index", "GET")
          details = Details.new(PathInfo.new(path, data.action_lines["index"]?))
          endpoint = Endpoint.new(index_url, "GET", last_params, details)
          attach_callees_for_action(endpoint, data, "index")
          @result << endpoint
        when "GET/SHOW"
          last_params = promote_identifier_to_path(action_params(data, "show", "GET"))
          details = Details.new(PathInfo.new(path, data.action_lines["show"]?))
          endpoint = Endpoint.new(member_url, "GET", last_params, details)
          attach_callees_for_action(endpoint, data, "show")
          @result << endpoint
        when "POST"
          last_params = action_params(data, "create", method)
          details = Details.new(PathInfo.new(path, data.action_lines["create"]?))
          endpoint = Endpoint.new(index_url, method, last_params, details)
          attach_callees_for_action(endpoint, data, "create")
          @result << endpoint
        when "DELETE"
          last_params = promote_identifier_to_path(action_params(data, "destroy", method))
          details = Details.new(PathInfo.new(path, data.action_lines["destroy"]?))
          endpoint = Endpoint.new(member_url, method, last_params, details)
          attach_callees_for_action(endpoint, data, "destroy")
          @result << endpoint
        else
          last_params = promote_identifier_to_path(action_params(data, "update", method))
          details = Details.new(PathInfo.new(path, data.action_lines["update"]?))
          endpoint = Endpoint.new(member_url, method, last_params, details)
          attach_callees_for_action(endpoint, data, "update")
          @result << endpoint
        end
      end

      @result
    end

    # Scans a controller file once, collecting per-method params (headers/cookies)
    # plus shared params (params[:x] / params["x"], params.require...permit) and
    # the names of every `def`. Shared because the existing heuristic associates
    # params[:x] with the whole controller, not a specific action. Results are
    # memoized per path so re-resolution (resources + member/collection + `to:`)
    # only reads each controller once.
    private def extract_controller_data(path : String) : ControllerData
      cached = @controller_data_cache[path]?
      return cached if cached

      params_method = Hash(String, Array(Param)).new
      params_body_by_action = Hash(String, Array(Param)).new
      params_query_by_action = Hash(String, Array(Param)).new
      defined_actions = Set(String).new
      helper_calls_by_action = Hash(String, Array(String)).new
      callees_by_action = Hash(String, Array(Noir::RubyCalleeExtractor::Entry)).new
      action_lines = Hash(String, Int32).new
      method_bodies = Hash(String, Array(String)).new
      param_type = "form"

      unless File.exists?(path)
        empty = ControllerData.new(param_type, params_method, params_body_by_action, params_query_by_action,
          defined_actions, helper_calls_by_action, callees_by_action, action_lines)
        @controller_data_cache[path] = empty
        return empty
      end

      File.open(path, "r", encoding: "utf-8", invalid: :skip) do |controller_file|
        controller_content = controller_file.gets_to_end
        param_type = "json" if controller_content.includes?("render json:")
        callees_by_action = extract_action_callees(controller_content, path) if callees_needed?

        controller_file.rewind
        this_method = ""

        controller_file.each_line.with_index do |raw_line, index|
          line = strip_inline_comment(raw_line)

          if line.includes?("def ")
            func_name = line.split("def ", 2)[1].split("(")[0].split(";")[0].strip
            func_name = func_name.lchop("self.").strip
            unless func_name.empty?
              this_method = func_name
              defined_actions << func_name
              action_lines[func_name] = index + 1
              method_bodies[this_method] ||= [] of String
            end
          end

          unless this_method.empty?
            method_bodies[this_method] ||= [] of String
            method_bodies[this_method] << line
          end

          if pm = line.match(/permit\s*\(([^)]*)\)/)
            pm[1].split(',').each do |raw|
              name = raw.gsub(/[:\s'"]/, "")
              next if name.empty? || this_method.empty?
              params_body_by_action[this_method] ||= [] of Param
              params_body_by_action[this_method] << Param.new(name, "", param_type)
              params_query_by_action[this_method] ||= [] of Param
              params_query_by_action[this_method] << Param.new(name, "", "query")
            end
          end

          line.scan(/params\[\s*(?::(\w+)|['"]([^'"]+)['"])\s*\]/) do |m|
            name = (m[1]? || m[2]?).to_s.strip
            next if name.empty? || this_method.empty?
            params_body_by_action[this_method] ||= [] of Param
            params_body_by_action[this_method] << Param.new(name, "", param_type)
            params_query_by_action[this_method] ||= [] of Param
            params_query_by_action[this_method] << Param.new(name, "", "query")
          end

          if hm = line.match(/request\.headers\[\s*['"]([^'"]+)['"]\s*\]/)
            name = hm[1].strip
            if !name.empty? && !this_method.empty?
              params_method[this_method] ||= [] of Param
              params_method[this_method] << Param.new(name, "", "header")
            end
          end

          line.scan(/cookies(?:\.(?:signed|encrypted))?\[\s*(?::(\w+)|['"]([^'"]+)['"])\s*\]/) do |cm|
            name = (cm[1]? || cm[2]?).to_s.strip
            next if name.empty? || this_method.empty?
            params_method[this_method] ||= [] of Param
            params_method[this_method] << Param.new(name, "", "cookie")
          end
        end
      end

      helper_calls_by_action = build_helper_call_map(method_bodies, defined_actions)

      data = ControllerData.new(param_type, params_method, params_body_by_action, params_query_by_action,
        defined_actions, helper_calls_by_action, callees_by_action, action_lines)
      @controller_data_cache[path] = data
      data
    end

    private def extract_action_callees(content : String, path : String) : Hash(String, Array(Noir::RubyCalleeExtractor::Entry))
      result = Hash(String, Array(Noir::RubyCalleeExtractor::Entry)).new
      lines = content.lines
      index = 0

      while index < lines.size
        stripped = strip_inline_comment(lines[index]).strip
        if m = stripped.match(/^(?:private\s+|protected\s+|public\s+)?def\s+(?:self\.)?([A-Za-z_]\w*[!?=]?)\b/)
          action = m[1]
          inline_body, closed_on_def_line = inline_def_body(stripped, m[0])
          body_lines = [] of String
          body_start_line = inline_body ? index + 1 : index + 2
          body_lines << inline_body if inline_body

          unless closed_on_def_line
            depth = 1
            index += 1

            while index < lines.size
              raw_body_line = lines[index]
              body_line = strip_inline_comment(raw_body_line).strip

              if closes_ruby_block?(body_line)
                depth -= 1
                break if depth == 0
                body_lines << raw_body_line
                index += 1
                next
              end

              body_lines << raw_body_line
              depth += ruby_block_open_delta(body_line)
              index += 1
            end
          end

          callees = Noir::RubyCalleeExtractor.callees_for_body(body_lines.join("\n"), path, body_start_line)
          result[action] = callees unless callees.empty?
        end

        index += 1
      end

      result
    end

    private def inline_def_body(line : String, match_text : String) : Tuple(String?, Bool)
      return {nil, false} if match_text.size >= line.size

      tail = line[match_text.size, line.size - match_text.size].strip
      return {nil, false} unless tail.starts_with?(";")

      tail = tail[1, tail.size - 1].strip
      if m = tail.match(/^(.*?)(?:;\s*)?end\b/)
        body = m[1].strip
        return {body.empty? ? nil : body, true}
      end

      {tail.empty? ? nil : tail, false}
    end

    private def ruby_block_open_delta(line : String) : Int32
      return 0 if line.empty?
      return 1 if line.match(/\bdo\b\s*(\|[^|]*\|)?\s*\z/)
      return 1 if line.match(/^(if|unless|case|begin|while|until|for|class|module|def)\b/) && !line.match(/\bend\b/)
      0
    end

    private def closes_ruby_block?(line : String) : Bool
      !!line.match(/^end\b/)
    end

    private def dedup_by_name(params : Array(Param)) : Array(Param)
      seen = Set(String).new
      params.each_with_object([] of Param) do |p, acc|
        next if seen.includes?(p.name)
        seen << p.name
        acc << p
      end
    end

    # Build params for a custom action (member/collection or explicit
    # controller#action). Mirrors the resources flow: per-action headers/cookies
    # plus the action-local body/query params for the verb.
    private def params_for_action(controller_path : String?, action : String, verb : String) : Array(Param)
      return [] of Param if controller_path.nil?
      data = extract_controller_data(controller_path)
      return [] of Param unless data.defined_actions.includes?(action)

      action_params(data, action, verb)
    end

    private def action_params(data : ControllerData, action : String, verb : String) : Array(Param)
      result = [] of Param
      merge_action_params(result, data, action, verb)

      helper_names = data.helper_calls_by_action[action]? || [] of String
      helper_names.each do |helper_name|
        next if helper_name == action
        merge_action_params(result, data, helper_name, verb)
      end

      result
    end

    private def merge_action_params(result : Array(Param), data : ControllerData, action : String, verb : String)
      data.params_method[action]?.try &.each { |p| push_unique_param(result, clone_param(p)) }

      source_params = case verb
                      when "GET", "HEAD", "OPTIONS", "DELETE"
                        dedup_by_name(data.params_query_by_action[action]? || [] of Param)
                      else
                        dedup_by_name(data.params_body_by_action[action]? || [] of Param)
                      end

      source_params.each do |param|
        push_unique_param(result, clone_param(param))
      end
    end

    private def push_unique_param(params : Array(Param), param : Param)
      params << param unless params.any? { |existing| existing.name == param.name && existing.param_type == param.param_type }
    end

    private def promote_identifier_to_path(params : Array(Param)) : Array(Param)
      params.each_index do |index|
        next unless params[index].name == "id"
        param = params[index]
        param.param_type = "path"
        params[index] = param
      end
      params
    end

    private def clone_param(param : Param) : Param
      Param.new(param.name, param.value, param.param_type)
    end

    private def build_helper_call_map(method_bodies : Hash(String, Array(String)), defined_actions : Set(String)) : Hash(String, Array(String))
      helper_calls = Hash(String, Array(String)).new

      method_bodies.each do |method_name, body_lines|
        body = body_lines.join("\n")
        defined_actions.each do |candidate|
          next if candidate == method_name
          next unless body.matches?(/\b#{Regex.escape(candidate)}\b/)
          helper_calls[method_name] ||= [] of String
          helper_calls[method_name] << candidate unless helper_calls[method_name].includes?(candidate)
        end
      end

      helper_calls
    end

    private def attach_callees_for_action(endpoint : Endpoint, controller_path : String?, action : String)
      return if controller_path.nil?
      attach_callees_for_action(endpoint, extract_controller_data(controller_path), action)
    end

    private def attach_callees_for_action(endpoint : Endpoint, data : ControllerData, action : String)
      return unless callees_needed?
      if callees = data.callees_by_action[action]?
        attach_ruby_callees(endpoint, callees)
      end
    end

    # Callees feed both `--include-callee` (direct output) and `--ai-context`
    # (aggregated review context). Extraction is skipped when neither flag is
    # set so default scans avoid the controller-body walk per action.
    private def callees_needed? : Bool
      any_to_bool(@options["include_callee"]?) || any_to_bool(@options["ai_context"]?)
    end

    private def parent_resources_frame(stack : Array(Frame)) : Frame?
      stack.reverse_each do |f|
        return f if f.kind == :resources
      end
      nil
    end

    # Parses `=> "ctrl#action"`, `to: "ctrl#action"`,
    # `controller: "ctrl", action: :show`, and controller-block
    # `get "path" => :action` forms.
    private def parse_controller_action(rest : String, scoped_controller : String? = nil) : Tuple(String, String)?
      if m = rest.match(/=>\s*['"]([^'"#]+)#([\w]+)['"]/)
        return {m[1], m[2]}
      end
      if m = rest.match(/to:\s*['"]([^'"#]+)#([\w]+)['"]/)
        return {m[1], m[2]}
      end
      options = parse_options(rest)
      if controller = options["controller"]?
        if action = options["action"]?
          return {controller, action}
        end
      end
      if scoped_controller
        if action = options["action"]?
          return {scoped_controller, action}
        end
        if m = rest.match(/(?:=>|to:)\s*:(\w+)/)
          return {scoped_controller, m[1]}
        end
      end
      nil
    end

    # Resolve `ctrl#action` to a controller file. When the route lives inside a
    # `namespace :admin` block, Rails resolves "monitor#ping" to
    # `Admin::MonitorController` — try the subdir-prefixed path first, then fall
    # back to a bare lookup so absolute-style references ("api/v1/users") still
    # work regardless of where they're declared.
    private def find_controller_file(framework_root : String, ctrl_name : String,
                                     stack : Array(Frame) = [] of Frame) : String?
      return if ctrl_name.empty?
      candidates = [] of String
      subdir = current_controller_subdir(stack)
      if !subdir.empty? && !ctrl_name.includes?('/')
        candidates << "#{framework_root}/app/controllers/#{subdir}/#{ctrl_name}_controller.rb"
      end
      candidates << "#{framework_root}/app/controllers/#{ctrl_name}_controller.rb"
      candidates.find { |c| File.exists?(c) }
    end

    private def action_allowed?(name : String, only : Array(String), except : Array(String)) : Bool
      return false if !only.empty? && !only.includes?(name)
      return false if except.includes?(name)
      true
    end

    private def compose_url(prefix : String, suffix : String) : String
      return suffix if prefix.empty?
      "/#{prefix}#{suffix}"
    end
  end
end
