require "../../engines/ruby_engine"

module Analyzer::Ruby
  class Rails < RubyEngine
    # Devise routes generated by `devise_for :scope`. Tuples are
    # {METHOD, sub_path} appended to the scope's base path.
    DEVISE_ROUTES = [
      {"GET", "/sign_in"},
      {"POST", "/sign_in"},
      {"DELETE", "/sign_out"},
      {"POST", ""},
      {"GET", "/sign_up"},
      {"GET", "/edit"},
      {"PUT", ""},
      {"PATCH", ""},
      {"DELETE", ""},
      {"GET", "/password/new"},
      {"POST", "/password"},
      {"GET", "/password/edit"},
      {"PUT", "/password"},
      {"PATCH", "/password"},
      {"GET", "/confirmation/new"},
      {"POST", "/confirmation"},
      {"GET", "/confirmation"},
      {"GET", "/unlock/new"},
      {"POST", "/unlock"},
      {"GET", "/unlock"},
    ]

    struct Frame
      property kind : Symbol
      property path : String
      property controller_subdir : String
      property resource_name : String?
      property controller_path : String?

      def initialize(@kind : Symbol, @path : String = "", @controller_subdir : String = "",
                     @resource_name : String? = nil, @controller_path : String? = nil)
      end
    end

    record ControllerData,
      param_type : String,
      params_method : Hash(String, Array(Param)),
      permit_body_params : Array(Param),
      permit_query_params : Array(Param),
      defined_actions : Set(String)

    @controller_data_cache = Hash(String, ControllerData).new

    def analyze
      framework_roots = discover_framework_roots("config/routes.rb")
      framework_roots = [@base_path] if framework_roots.empty?

      framework_roots.each do |framework_root|
        begin
          get_public_files(framework_root).each do |file|
            if file =~ /\/public\/(.*)/
              relative_path = $1
              details = Details.new(PathInfo.new(file))
              @result << Endpoint.new("/#{relative_path}", "GET", details)
            end
          end
        rescue e
          logger.debug e
        end

        routes_path = "#{framework_root}/config/routes.rb"
        next unless File.exists?(routes_path)

        parse_routes_file(routes_path, framework_root)
      end

      @result
    end

    private def parse_routes_file(routes_path : String, framework_root : String)
      details = Details.new(PathInfo.new(routes_path))
      stack = [] of Frame

      File.open(routes_path, "r", encoding: "utf-8", invalid: :skip) do |file|
        file.each_line do |raw_line|
          line = strip_inline_comment(raw_line).strip
          next if line.empty?

          # Handle `end` (top of stack pops one).
          if line == "end" || line.starts_with?("end ") || line.starts_with?("end;") || line.starts_with?("end#")
            stack.pop unless stack.empty?
            next
          end

          opens_block = opens_do_block?(line)

          # Outermost: Rails.application.routes.draw do ... end
          if line.starts_with?("Rails.application.routes.draw")
            stack << Frame.new(:neutral) if opens_block
            next
          end

          # namespace :foo do
          if m = line.match(/^namespace\s+(?::(\w+)|['"]([^'"]+)['"])/)
            name = m[1]? || m[2]? || ""
            stack << Frame.new(:namespace, path: name, controller_subdir: name) if opens_block
            next
          end

          # scope :name / scope "/admin" / scope path: ...
          if line.starts_with?("scope")
            scope_path = ""
            if m = line.match(/^scope\s+:(\w+)/)
              scope_path = m[1]
            elsif m = line.match(/^scope\s+['"]([^'"]+)['"]/)
              scope_path = m[1].lchop('/')
            elsif m = line.match(/path:\s*['"]([^'"]+)['"]/)
              scope_path = m[1].lchop('/')
            elsif m = line.match(/path:\s*:(\w+)/)
              scope_path = m[1]
            end
            stack << Frame.new(:scope, path: scope_path) if opens_block
            next
          end

          # root "ctrl#action" / root to: "ctrl#action"
          if line.starts_with?("root")
            prefix = current_path_prefix(stack)
            url = prefix.empty? ? "/" : "/#{prefix}"
            @result << Endpoint.new(url, "GET", details)
            next
          end

          # devise_for :users
          if m = line.match(/^devise_for\s+:(\w+)/)
            scope_name = m[1]
            prefix = current_path_prefix(stack)
            base = prefix.empty? ? "/#{scope_name}" : "/#{prefix}/#{scope_name}"
            DEVISE_ROUTES.each do |verb, sub|
              @result << Endpoint.new("#{base}#{sub}", verb, details)
            end
            next
          end

          # mount Engine, at: "/path"  /  mount Engine => "/path"
          if line.starts_with?("mount")
            at_path = nil
            if m = line.match(/at:\s*['"]([^'"]+)['"]/)
              at_path = m[1]
            elsif m = line.match(/=>\s*['"]([^'"]+)['"]/)
              at_path = m[1]
            end
            if at_path
              prefix = current_path_prefix(stack)
              normalized = at_path.starts_with?("/") ? at_path : "/#{at_path}"
              url = prefix.empty? ? normalized : "/#{prefix}#{normalized}"
              @result << Endpoint.new(url, "GET", details)
            end
            next
          end

          # resources :foo / resource :foo
          if m = line.match(/^(resources?)\s+:(\w+)/)
            kind_kw = m[1]
            name = m[2]
            singular = (kind_kw == "resource")
            options = parse_options(line)

            controller_subdir = current_controller_subdir(stack)
            ctrl_override = options["controller"]?
            file_base = if ctrl_override
                          ctrl_override.includes?('/') ? ctrl_override : (controller_subdir.empty? ? ctrl_override : "#{controller_subdir}/#{ctrl_override}")
                        else
                          controller_subdir.empty? ? name : "#{controller_subdir}/#{name}"
                        end

            only_list = parse_symbol_list(options["only"]?)
            except_list = parse_symbol_list(options["except"]?)

            url_segment = options["path"]? || name
            path_prefix = current_path_prefix(stack)

            candidates = [] of String
            candidates << "#{framework_root}/app/controllers/#{file_base}_controller.rb"
            unless ctrl_override
              candidates << "#{framework_root}/app/controllers/#{file_base}s_controller.rb"
              candidates << "#{framework_root}/app/controllers/#{file_base}es_controller.rb"
            end

            existing_controller_path = candidates.find { |c| File.exists?(c) }

            candidates.each do |ctrl_path|
              @result += controller_to_endpoint(
                ctrl_path, @url, url_segment,
                path_prefix: path_prefix,
                only: only_list,
                except: except_list,
                singular: singular,
              )
            end

            if opens_block
              child_path = singular ? url_segment : "#{url_segment}/1"
              stack << Frame.new(:resources, path: child_path, resource_name: name,
                controller_path: existing_controller_path)
            end
            next
          end

          # member do / collection do
          if line == "member" || line == "member do" || line.starts_with?("member do")
            stack << Frame.new(:member) if opens_block
            next
          end
          if line == "collection" || line == "collection do" || line.starts_with?("collection do")
            stack << Frame.new(:collection) if opens_block
            next
          end

          # HTTP verb routes
          if m = line.match(/^(get|post|put|patch|delete|head|options)\b(.*)/)
            verb = m[1].upcase
            rest = m[2]

            in_collection = stack.last?.try(&.kind) == :collection
            in_member = stack.last?.try(&.kind) == :member

            # `get :action` form inside member/collection
            if (am = rest.match(/^\s*:(\w+)\b/)) && (in_member || in_collection)
              action = am[1]
              url = member_collection_url(stack, action, in_collection)
              if url
                parent = parent_resources_frame(stack)
                action_params = parent ? params_for_action(parent.controller_path, action, verb) : ([] of Param)
                @result << Endpoint.new(url, verb, action_params, details)
              end
              next
            end

            # `get "path"` / `get "path" => "..."` / `get "path", to: "..."`
            if sm = rest.match(/^\s*['"]([^'"]+)['"]/)
              path = sm[1]
              prefix = current_path_prefix(stack)
              path_part = path.starts_with?("/") ? path : "/#{path}"
              url = prefix.empty? ? path_part : "/#{prefix}#{path_part}"

              ctrl_action = parse_controller_action(rest)
              action_params = [] of Param
              if ctrl_action
                ctrl_name, action = ctrl_action
                ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
                action_params = params_for_action(ctrl_path, action, verb)
              end

              @result << Endpoint.new(url, verb, action_params, details)
              next
            end
            next
          end

          # Unknown DSL line that still opens a block (e.g. `constraints ... do`).
          stack << Frame.new(:neutral) if opens_block
        end
      end
    end

    private def strip_inline_comment(line : String) : String
      in_str = false
      escaped = false
      quote = '\0'
      line.each_char_with_index do |c, i|
        if in_str
          if escaped
            escaped = false
          elsif c == '\\'
            escaped = true
          elsif c == quote
            in_str = false
          end
        else
          if c == '"' || c == '\''
            in_str = true
            quote = c
          elsif c == '#'
            return line[0, i]
          end
        end
      end
      line
    end

    private def opens_do_block?(line : String) : Bool
      !!line.match(/\bdo\b\s*(\|[^|]*\|)?\s*\z/)
    end

    private def parse_options(line : String) : Hash(String, String)
      result = {} of String => String
      # capture key: "value" or key: 'value' or key: :symbol or key: [..]
      line.scan(/(\w+):\s*(['"][^'"]+['"]|:[a-zA-Z_][\w]*|\[[^\]]*\])/) do |m|
        key = m[1]
        raw = m[2]
        value = if raw.starts_with?('"') || raw.starts_with?('\'')
                  raw[1, raw.size - 2]
                elsif raw.starts_with?(':')
                  raw[1, raw.size - 1]
                else
                  raw[1, raw.size - 2] # strip [ ]
                end
        result[key] = value
      end
      result
    end

    private def parse_symbol_list(raw : String?) : Array(String)
      return [] of String if raw.nil?
      raw.split(',').map(&.strip.lchop(':').strip).reject(&.empty?)
    end

    private def current_path_prefix(stack : Array(Frame)) : String
      parts = [] of String
      stack.each do |f|
        next if f.path.empty?
        parts << f.path
      end
      parts.join("/")
    end

    private def current_controller_subdir(stack : Array(Frame)) : String
      parts = [] of String
      stack.each do |f|
        next if f.controller_subdir.empty?
        parts << f.controller_subdir
      end
      parts.join("/")
    end

    # Build URL for a `get :action` inside member/collection blocks. For
    # member: uses the parent resource's `name/1` prefix; for collection:
    # strips the trailing `/1` so the action sits on the index URL.
    private def member_collection_url(stack : Array(Frame), action : String, in_collection : Bool) : String?
      resources_idx = nil
      stack.each_with_index do |f, i|
        resources_idx = i if f.kind == :resources
      end
      return if resources_idx.nil?

      parts = [] of String
      stack[0, resources_idx].each do |f|
        parts << f.path unless f.path.empty?
      end
      rf = stack[resources_idx]
      seg = rf.path
      if in_collection && seg.ends_with?("/1")
        seg = seg[0, seg.size - 2]
      end
      parts << seg unless seg.empty?
      parts << action
      "/" + parts.join("/")
    end

    def controller_to_endpoint(
      path : String,
      @url : String,
      resource : String,
      path_prefix : String = "",
      only : Array(String) = [] of String,
      except : Array(String) = [] of String,
      singular : Bool = false,
    )
      @result = [] of Endpoint

      return @result unless File.exists?(path)

      data = extract_controller_data(path)
      defined_actions = data.defined_actions
      params_method = data.params_method
      params_body = data.permit_body_params
      deduplication_params_query = dedup_by_name(data.permit_query_params)

      methods = [] of String
      {"index", "show", "create", "update", "destroy"}.each do |name|
        next unless defined_actions.includes?(name)
        next unless action_allowed?(name, only, except)
        case name
        when "index"
          methods << "GET/INDEX" unless singular
        when "show"
          methods << "GET/SHOW"
        when "create"
          methods << "POST"
        when "update"
          methods << "PUT"
        when "destroy"
          methods << "DELETE"
        end
      end

      details = Details.new(PathInfo.new(path))
      index_url = compose_url(path_prefix, "/#{resource}")
      member_url = compose_url(path_prefix, singular ? "/#{resource}" : "/#{resource}/1")

      methods.each do |method|
        case method
        when "GET/INDEX"
          last_params = (params_method["index"]? || [] of Param) + deduplication_params_query
          @result << Endpoint.new(index_url, "GET", last_params, details)
        when "GET/SHOW"
          last_params = (params_method["show"]? || [] of Param) + deduplication_params_query
          @result << Endpoint.new(member_url, "GET", last_params, details)
        when "POST"
          last_params = (params_method["create"]? || [] of Param) + params_body
          @result << Endpoint.new(index_url, method, last_params, details)
        when "DELETE"
          last_params = params_method["destroy"]? || [] of Param
          @result << Endpoint.new(member_url, method, last_params, details)
        else
          last_params = (params_method["update"]? || [] of Param) + params_body
          @result << Endpoint.new(member_url, method, last_params, details)
        end
      end

      @result
    end

    # Scans a controller file once, collecting per-method params (headers/cookies)
    # plus shared params (params[:x] / params["x"], params.require...permit) and
    # the names of every `def`. Shared because the existing heuristic associates
    # params[:x] with the whole controller, not a specific action. Results are
    # memoized per path so re-resolution (resources + member/collection + `to:`)
    # only reads each controller once.
    private def extract_controller_data(path : String) : ControllerData
      cached = @controller_data_cache[path]?
      return cached if cached

      params_method = Hash(String, Array(Param)).new
      permit_body_params = [] of Param
      permit_query_params = [] of Param
      defined_actions = Set(String).new
      param_type = "form"

      unless File.exists?(path)
        empty = ControllerData.new(param_type, params_method, permit_body_params, permit_query_params, defined_actions)
        @controller_data_cache[path] = empty
        return empty
      end

      File.open(path, "r", encoding: "utf-8", invalid: :skip) do |controller_file|
        controller_content = controller_file.gets_to_end
        param_type = "json" if controller_content.includes?("render json:")

        controller_file.rewind
        this_method = ""

        controller_file.each_line do |raw_line|
          line = strip_inline_comment(raw_line)

          if line.includes?("def ")
            func_name = line.split("def ", 2)[1].split("(")[0].split(";")[0].strip
            func_name = func_name.lchop("self.").strip
            unless func_name.empty?
              this_method = func_name
              defined_actions << func_name
            end
          end

          if pm = line.match(/permit\s*\(([^)]*)\)/)
            pm[1].split(',').each do |raw|
              name = raw.gsub(/[:\s'"]/, "")
              next if name.empty?
              permit_body_params << Param.new(name, "", param_type)
              permit_query_params << Param.new(name, "", "query")
            end
          end

          line.scan(/params\[\s*(?::(\w+)|['"]([^'"]+)['"])\s*\]/) do |m|
            name = (m[1]? || m[2]?).to_s.strip
            next if name.empty?
            permit_body_params << Param.new(name, "", param_type)
            permit_query_params << Param.new(name, "", "query")
          end

          if hm = line.match(/request\.headers\[\s*['"]([^'"]+)['"]\s*\]/)
            name = hm[1].strip
            if !name.empty? && this_method != ""
              params_method[this_method] ||= [] of Param
              params_method[this_method] << Param.new(name, "", "header")
            end
          end

          line.scan(/cookies(?:\.(?:signed|encrypted))?\[\s*(?::(\w+)|['"]([^'"]+)['"])\s*\]/) do |cm|
            name = (cm[1]? || cm[2]?).to_s.strip
            next if name.empty? || this_method == ""
            params_method[this_method] ||= [] of Param
            params_method[this_method] << Param.new(name, "", "cookie")
          end
        end
      end

      data = ControllerData.new(param_type, params_method, permit_body_params, permit_query_params, defined_actions)
      @controller_data_cache[path] = data
      data
    end

    private def dedup_by_name(params : Array(Param)) : Array(Param)
      seen = Set(String).new
      params.each_with_object([] of Param) do |p, acc|
        next if seen.includes?(p.name)
        seen << p.name
        acc << p
      end
    end

    # Build params for a custom action (member/collection or explicit
    # controller#action). Mirrors the resources flow: per-action headers/cookies
    # plus the controller's shared permitted/body/query params for the verb.
    private def params_for_action(controller_path : String?, action : String, verb : String) : Array(Param)
      return [] of Param if controller_path.nil?
      data = extract_controller_data(controller_path)
      return [] of Param unless data.defined_actions.includes?(action)

      result = [] of Param
      data.params_method[action]?.try &.each { |p| result << p }

      case verb
      when "GET", "HEAD", "OPTIONS"
        result.concat(dedup_by_name(data.permit_query_params))
      when "DELETE"
        # No shared body params for delete, matching the resources flow.
      else
        result.concat(data.permit_body_params)
      end

      result
    end

    private def parent_resources_frame(stack : Array(Frame)) : Frame?
      stack.reverse_each do |f|
        return f if f.kind == :resources
      end
      nil
    end

    # Parses `=> "ctrl#action"` and `to: "ctrl#action"` forms.
    private def parse_controller_action(rest : String) : Tuple(String, String)?
      if m = rest.match(/=>\s*['"]([^'"#]+)#([\w]+)['"]/)
        return {m[1], m[2]}
      end
      if m = rest.match(/to:\s*['"]([^'"#]+)#([\w]+)['"]/)
        return {m[1], m[2]}
      end
      nil
    end

    # Resolve `ctrl#action` to a controller file. When the route lives inside a
    # `namespace :admin` block, Rails resolves "monitor#ping" to
    # `Admin::MonitorController` — try the subdir-prefixed path first, then fall
    # back to a bare lookup so absolute-style references ("api/v1/users") still
    # work regardless of where they're declared.
    private def find_controller_file(framework_root : String, ctrl_name : String,
                                     stack : Array(Frame) = [] of Frame) : String?
      return if ctrl_name.empty?
      candidates = [] of String
      subdir = current_controller_subdir(stack)
      if !subdir.empty? && !ctrl_name.includes?('/')
        candidates << "#{framework_root}/app/controllers/#{subdir}/#{ctrl_name}_controller.rb"
      end
      candidates << "#{framework_root}/app/controllers/#{ctrl_name}_controller.rb"
      candidates.find { |c| File.exists?(c) }
    end

    private def action_allowed?(name : String, only : Array(String), except : Array(String)) : Bool
      return false if !only.empty? && !only.includes?(name)
      return false if except.includes?(name)
      true
    end

    private def compose_url(prefix : String, suffix : String) : String
      return suffix if prefix.empty?
      "/#{prefix}#{suffix}"
    end
  end
end
