require "../../engines/ruby_engine"

module Analyzer::Ruby
  class Rails < RubyEngine
    # Devise routes generated by `devise_for :scope`. Tuples are
    # {METHOD, sub_path} appended to the scope's base path.
    DEVISE_ROUTES = [
      {"GET", "/sign_in"},
      {"POST", "/sign_in"},
      {"DELETE", "/sign_out"},
      {"POST", ""},
      {"GET", "/sign_up"},
      {"GET", "/edit"},
      {"PUT", ""},
      {"PATCH", ""},
      {"DELETE", ""},
      {"GET", "/password/new"},
      {"POST", "/password"},
      {"GET", "/password/edit"},
      {"PUT", "/password"},
      {"PATCH", "/password"},
      {"GET", "/confirmation/new"},
      {"POST", "/confirmation"},
      {"GET", "/confirmation"},
      {"GET", "/unlock/new"},
      {"POST", "/unlock"},
      {"GET", "/unlock"},
    ]

    # Routes generated by Doorkeeper's `use_doorkeeper` (the de-facto
    # OAuth2 provider for Rails — Mastodon, GitLab, Discourse plugins,
    # …). Each tuple is {METHOD, sub_path, group, action}. `group`
    # matches the `skip_controllers` symbols so a `use_doorkeeper do
    # skip_controllers :applications end` block drops the right rows,
    # and indexes the `controllers foo: 'bar'` remap used to resolve
    # the implementing controller for params/callees. Paths are
    # appended to `/oauth` under the scope where `use_doorkeeper` runs.
    DOORKEEPER_ROUTES = [
      {"GET", "/oauth/authorize", "authorizations", "new"},
      {"POST", "/oauth/authorize", "authorizations", "create"},
      {"DELETE", "/oauth/authorize", "authorizations", "destroy"},
      {"POST", "/oauth/token", "tokens", "create"},
      {"POST", "/oauth/revoke", "tokens", "revoke"},
      {"POST", "/oauth/introspect", "tokens", "introspect"},
      {"GET", "/oauth/token/info", "token_info", "show"},
      {"GET", "/oauth/applications", "applications", "index"},
      {"POST", "/oauth/applications", "applications", "create"},
      {"GET", "/oauth/applications/new", "applications", "new"},
      {"GET", "/oauth/applications/:id", "applications", "show"},
      {"GET", "/oauth/applications/:id/edit", "applications", "edit"},
      {"PATCH", "/oauth/applications/:id", "applications", "update"},
      {"PUT", "/oauth/applications/:id", "applications", "update"},
      {"DELETE", "/oauth/applications/:id", "applications", "destroy"},
      {"GET", "/oauth/authorized_applications", "authorized_applications", "index"},
      {"DELETE", "/oauth/authorized_applications/:id", "authorized_applications", "destroy"},
    ]

    struct Frame
      property kind : Symbol
      property path : String
      property controller_subdir : String
      property resource_name : String?
      property controller_path : String?
      property controller_scope : String?

      def initialize(@kind : Symbol, @path : String = "", @controller_subdir : String = "",
                     @resource_name : String? = nil, @controller_path : String? = nil,
                     @controller_scope : String? = nil)
      end
    end

    record ControllerData,
      param_type : String,
      params_method : Hash(String, Array(Param)),
      params_body_by_action : Hash(String, Array(Param)),
      params_query_by_action : Hash(String, Array(Param)),
      defined_actions : Set(String),
      helper_calls_by_action : Hash(String, Array(String)),
      callees_by_action : Hash(String, Array(Noir::RubyCalleeExtractor::Entry)),
      action_lines : Hash(String, Int32)

    record ConcernResource,
      kind_kw : String,
      name : String,
      options : Hash(String, String),
      stack : Array(Frame)

    alias EngineMountKey = Tuple(String, String)

    @controller_data_cache = Hash(String, ControllerData).new
    # Maps a mountable-engine constant (e.g. `DiscoursePoll::Engine`) to the
    # path it is mounted at (`/polls`). A Rails engine's `routes.draw` block
    # holds engine-relative paths; the `mount` that anchors them usually
    # lives in a different file (a plugin.rb, the host app's routes), so we
    # resolve it cross-file once up front.
    @engine_mount_prefixes = Hash(EngineMountKey, String).new
    @known_files = Set(String).new

    def analyze
      files = all_files.reject { |file| ruby_non_production_path?(file) }
      @known_files = Set(String).new(files)
      @engine_mount_prefixes = build_engine_mount_map(files)

      framework_roots = discover_framework_roots(files, "config/routes.rb")
      framework_roots = base_paths if framework_roots.empty?

      framework_roots.each do |framework_root|
        begin
          get_public_files(files, framework_root).each do |file|
            if file =~ /\/public\/(.*)/
              relative_path = $1
              details = Details.new(PathInfo.new(file))
              @result << Endpoint.new("/#{relative_path}", "GET", details)
            end
          end
        rescue e
          logger.debug e
        end

        routes_path = "#{framework_root}/config/routes.rb"
        next unless known_file?(routes_path)

        parse_routes_file(routes_path, framework_root)
      end

      @result
    end

    private def parse_routes_file(routes_path : String, framework_root : String)
      parsed_route_files = Set(String).new
      concern_resources = {} of String => Array(ConcernResource)
      parse_routes_file(routes_path, framework_root, parsed_route_files, [] of Frame, concern_resources)
    end

    private def known_file?(path : String) : Bool
      return @known_files.includes?(path) unless @known_files.empty?
      File.exists?(path)
    end

    private def discover_framework_roots(files : Array(String), anchor : String) : Array(String)
      suffix = anchor.starts_with?("/") ? anchor : "/#{anchor}"
      roots = [] of String

      files.each do |file|
        next unless file.ends_with?(suffix)
        next unless base_paths.any? { |base| path_under_root?(file, base) }

        root = file[0, file.size - suffix.size]
        roots << root unless roots.includes?(root)
      end

      roots
    end

    private def get_public_files(files : Array(String), base_path : String) : Array(String)
      project_public_roots = Set(String).new
      files.each do |file|
        next unless File.basename(file) == "Gemfile"
        next unless path_under_root?(file, base_path)
        project_public_roots << File.join(File.dirname(file), "public")
      end

      files.select do |file|
        next false unless path_under_root?(file, base_path)
        next false if FileHelper::PUBLIC_FILE_IGNORE.includes?(File.basename(file))
        project_public_roots.any? { |root| file != root && path_under_root?(file, root) }
      end
    end

    private def parse_routes_file(routes_path : String, framework_root : String,
                                  parsed_route_files : Set(String),
                                  inherited_stack : Array(Frame),
                                  concern_resources : Hash(String, Array(ConcernResource)))
      expanded_routes_path = File.expand_path(routes_path)
      parse_key = route_file_parse_key(expanded_routes_path, inherited_stack)
      return if parsed_route_files.includes?(parse_key)
      parsed_route_files << parse_key

      details = Details.new(PathInfo.new(routes_path))
      stack = inherited_stack.dup
      # Routes files routinely DRY repeated prefixes into local
      # string vars (`base_c_route = "/c/:channel_title/:channel_id"`)
      # then use them with Ruby interpolation
      # (`get "#{base_c_route}/:message_id" => "ctrl#act"`). The
      # line-based parser saw the literal `#{base_c_route}` survive
      # into URLs. discourse/discourse alone parked ~153 phantom
      # routes with `#{...}` in them. Track the assignments as we
      # walk the file and expand interpolations before route
      # matching.
      local_string_vars = Hash(String, String).new
      # `use_doorkeeper do ... end` config accumulated while the block
      # is on top of the stack: `skip_controllers :foo` drops a group,
      # `controllers foo: 'bar'` remaps the implementing controller.
      doorkeeper_skip = Set(String).new
      doorkeeper_controllers = Hash(String, String).new
      expand_inline_route_blocks(expand_static_loops(logical_route_lines(routes_path))).each do |raw_line|
        line = raw_line.strip
        next if line.empty?

        # Capture `name = "literal"` assignments at any nesting.
        # We only resolve simple string-literal RHS; anything more
        # complex (method calls, concatenation) stays opaque and
        # the original `#{...}` falls through unchanged.
        if assign = line.match(/^([a-z_][a-z0-9_]*)\s*=\s*["']([^"']+)["']\s*$/)
          local_string_vars[assign[1]] = assign[2]
        end

        # Expand interpolations in-place so downstream regexes
        # see the resolved path. We only substitute names we've
        # actually seen — unresolved `#{...}` survives, which is
        # better than producing an empty `/` placeholder.
        unless local_string_vars.empty?
          line = line.gsub(/\#\{([a-z_][a-z0-9_]*)\}/) do |match|
            name = $~[1]
            local_string_vars[name]? || match
          end
        end

        # Handle `end` (top of stack pops one). Closing a
        # `use_doorkeeper` block is where its routes are emitted, now
        # that any `skip_controllers`/`controllers` config is known.
        if end_line?(line)
          unless stack.empty?
            popped = stack.pop
            if popped.kind == :doorkeeper
              emit_doorkeeper_routes(framework_root, stack, doorkeeper_skip, doorkeeper_controllers, details)
              doorkeeper_skip = Set(String).new
              doorkeeper_controllers = Hash(String, String).new
            end
          end
          next
        end

        # Inside a `use_doorkeeper do ... end` block only configuration
        # DSL appears (`controllers`, `skip_controllers`, `skip_*`) —
        # never routes — so collect what we need and swallow the rest.
        if stack.last?.try(&.kind) == :doorkeeper
          if line.starts_with?("skip_controllers")
            parse_symbol_list(line["skip_controllers".size..]).each { |group| doorkeeper_skip << group }
          elsif line.starts_with?("controllers")
            parse_options(line).each { |group, ctrl| doorkeeper_controllers[group] = ctrl }
          end
          next
        end

        opens_block = opens_do_block?(line) || opens_keyword_block?(line)

        # Outermost: Rails.application.routes.draw do ... end
        if line.starts_with?("Rails.application.routes.draw")
          stack << Frame.new(:neutral) if opens_block
          next
        end

        # Mountable engine: `SomeEngine.routes.draw do ... end`. Its routes
        # are relative to where the host `mount`s the engine, so resolve the
        # mount prefix (built cross-file in @engine_mount_prefixes) and push
        # it as a scope. Unknown mounts (engine shipped as a library, host
        # not in scan) fall back to a transparent frame — same as before.
        if opens_block && (em = line.match(/^(?:::)?([A-Z][A-Za-z0-9_:]*)\.routes\.draw\b/))
          mount_prefix = @engine_mount_prefixes[{configured_base_for(routes_path), em[1]}]?
          if mount_prefix && !mount_prefix.empty?
            stack << Frame.new(:scope, path: mount_prefix)
          else
            stack << Frame.new(:neutral)
          end
          next
        end

        # draw :admin / draw("api") loads config/routes/admin.rb inline.
        # Rails evaluates those files in the current mapper scope.
        if call = route_call(line, ["draw"])
          draw_names = parse_symbol_list(call[1])
          draw_names.each do |draw_name|
            draw_path = File.join(framework_root, "config", "routes", "#{draw_name}.rb")
            parse_routes_file(draw_path, framework_root, parsed_route_files, stack, concern_resources) if known_file?(draw_path)
          end
          next
        end

        # concern :commentable do
        if call = route_call(line, ["concern"])
          next unless m = call[1].match(/^\s*:(\w+)/)
          name = m[1]
          concern_resources[name] ||= [] of ConcernResource
          stack << Frame.new(:concern, resource_name: name) if opens_block
          next
        end

        # namespace :foo do
        if call = route_call(line, ["namespace"])
          next unless m = call[1].match(/^\s*(?::(\w+)|['"]([^'"]+)['"])/)
          name = m[1]? || m[2]? || ""
          options = parse_options(call[1])
          namespace_path = normalize_route_prefix(options.has_key?("path") ? options["path"] : name)
          stack << Frame.new(:namespace, path: namespace_path, controller_subdir: name) if opens_block
          next
        end

        # scope :name / scope "/admin" / scope path: ...
        if call = route_call(line, ["scope"])
          args = call[1]
          options = parse_options(args)
          scope_path = ""
          if m = args.match(/^\s*:(\w+)/)
            scope_path = m[1]
          elsif m = args.match(/^\s*['"]([^'"]+)['"]/)
            scope_path = normalize_route_prefix(m[1])
          elsif path_option = options["path"]?
            scope_path = normalize_route_prefix(path_option)
          end
          controller_subdir = options["module"]? || ""
          controller_scope = options["controller"]?
          stack << Frame.new(:scope, path: scope_path, controller_subdir: controller_subdir,
            controller_scope: controller_scope) if opens_block
          next
        end

        # controller :posts do ... end
        if call = route_call(line, ["controller"])
          controller_name = parse_first_route_name(call[1])
          stack << Frame.new(:controller, controller_scope: controller_name) if opens_block && controller_name
          next
        end

        # root "ctrl#action" / root to: "ctrl#action"
        if call = route_call(line, ["root"])
          rest = call[1]
          prefix = current_path_prefix(stack)
          url = prefix.empty? ? "/" : "/#{prefix}"
          ctrl_action = parse_controller_action(rest, current_controller_scope(stack))
          ctrl_path = nil.as(String?)
          action_name = nil.as(String?)
          if ctrl_action
            ctrl_name, action = ctrl_action
            ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
            action_name = action
          end
          parse_route_verbs(rest, ["GET"]).each do |root_verb|
            action_params = action_name ? params_for_action(ctrl_path, action_name, root_verb) : ([] of Param)
            endpoint = Endpoint.new(url, root_verb, action_params, details)
            attach_callees_for_action(endpoint, ctrl_path, action_name) if action_name
            @result << endpoint
          end
          next
        end

        # devise_for :users
        if call = route_call(line, ["devise_for"])
          next unless m = call[1].match(/^\s*:(\w+)/)
          scope_name = m[1]
          prefix = current_path_prefix(stack)
          base = prefix.empty? ? "/#{scope_name}" : "/#{prefix}/#{scope_name}"
          DEVISE_ROUTES.each do |verb, sub|
            @result << Endpoint.new("#{base}#{sub}", verb, details)
          end
          next
        end

        # use_doorkeeper / use_doorkeeper do ... end
        if route_call(line, ["use_doorkeeper"])
          if opens_block
            # Defer emission until `end` so skip_controllers/controllers
            # config inside the block is captured first.
            stack << Frame.new(:doorkeeper)
          else
            emit_doorkeeper_routes(framework_root, stack, doorkeeper_skip, doorkeeper_controllers, details)
          end
          next
        end

        # mount Engine, at: "/path"  /  mount Engine => "/path"
        if call = route_call(line, ["mount"])
          rest = call[1]
          at_path = nil
          if m = rest.match(/at:\s*['"]([^'"]+)['"]/)
            at_path = m[1]
          elsif m = rest.match(/=>\s*['"]([^'"]+)['"]/)
            at_path = m[1]
          end
          if at_path
            prefix = current_path_prefix(stack)
            normalized = at_path.starts_with?("/") ? at_path : "/#{at_path}"
            url = prefix.empty? ? normalized : "/#{prefix}#{normalized}"
            @result << Endpoint.new(url, "GET", details)
          end
          next
        end

        # concerns :commentable / concerns [:commentable, :taggable]
        if call = route_call(line, ["concerns"])
          emit_concern_resources(parse_symbol_list(call[1]), concern_resources, framework_root, stack)
          next
        end

        # resources :foo / resource :foo
        if call = route_call(line, ["resources", "resource"])
          kind_kw = call[0]
          next unless name = parse_first_route_name(call[1])
          options = parse_options(call[1])

          if concern_name = current_concern_definition(stack)
            concern_resources[concern_name] ||= [] of ConcernResource
            concern_resources[concern_name] << ConcernResource.new(kind_kw, name, options, current_concern_relative_stack(stack))
            if opens_block
              url_segment = options["path"]? || name
              singular = (kind_kw == "resource")
              child_path = singular ? url_segment : "#{url_segment}/1"
              stack << Frame.new(:resources, path: child_path, resource_name: name)
            end
            next
          end

          existing_controller_path = emit_resource_routes(framework_root, stack, kind_kw, name, options)

          concern_names = parse_symbol_list(options["concerns"]?)
          unless concern_names.empty?
            url_segment = options["path"]? || name
            virtual_stack = stack.dup
            virtual_stack << Frame.new(:resources, path: (kind_kw == "resource" ? url_segment : "#{url_segment}/1"),
              resource_name: name, controller_path: existing_controller_path)
            emit_concern_resources(concern_names, concern_resources, framework_root, virtual_stack)
          end

          if opens_block
            url_segment = options["path"]? || name
            singular = (kind_kw == "resource")
            child_path = singular ? url_segment : "#{url_segment}/1"
            # A `module:` on the resources line also scopes nested
            # resources/routes inside its block, so carry it on the frame's
            # controller_subdir for children to inherit.
            stack << Frame.new(:resources, path: child_path, resource_name: name,
              controller_path: existing_controller_path, controller_subdir: options["module"]? || "")
          end
          next
        end

        # member do / collection do
        if route_call(line, ["member"])
          stack << Frame.new(:member) if opens_block
          next
        end
        if route_call(line, ["collection"])
          stack << Frame.new(:collection) if opens_block
          next
        end
        if route_call(line, ["new"])
          stack << Frame.new(:new) if opens_block
          next
        end

        # HTTP verb routes
        if call = route_call(line, ["get", "post", "put", "patch", "delete", "head", "options"])
          verb = call[0].upcase
          rest = call[1]
          options = parse_options(rest)

          route_scope = options["on"]? || current_custom_route_scope(stack)
          in_collection = route_scope == "collection"
          in_member = route_scope == "member"
          in_new = route_scope == "new"

          # `get :action` form inside member/collection/new blocks, inline
          # `on:` declarations, or directly nested in a resources block.
          if (am = rest.match(/^\s*:(\w+)\b/)) && (in_member || in_collection || in_new || parent_resources_frame(stack))
            segment = am[1]
            url = custom_resource_action_url(stack, segment, route_scope)
            if url
              parent = parent_resources_frame(stack)
              ctrl_path = parent.try(&.controller_path)
              action_name = controller_action_for_symbol_route(rest, segment)

              if ctrl_action = parse_controller_action(rest, current_controller_scope(stack))
                ctrl_name, parsed_action = ctrl_action
                ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
                action_name = parsed_action
              end

              action_params = params_for_action(ctrl_path, action_name, verb)
              action_params = promote_identifier_to_path(action_params) unless in_collection || in_new
              endpoint = Endpoint.new(url, verb, action_params, details)
              attach_callees_for_action(endpoint, ctrl_path, action_name)
              @result << endpoint
            end
            next
          end

          # `get :action, to: "ctrl#action"` outside any resource block —
          # e.g. inside a bare `namespace :apps`. The symbol is a literal
          # path segment (`/api/v1/apps/verify_credentials`), not a resource
          # action. Requires an explicit destination so a bare `get :foo`
          # with no controller context isn't fabricated into a route.
          if (am = rest.match(/^\s*:(\w+)\b/)) && explicit_route_destination?(rest)
            segment = am[1]
            prefix = current_path_prefix_for_route(stack, route_scope)
            url = prefix.empty? ? "/#{segment}" : "/#{prefix}/#{segment}"

            ctrl_action = parse_controller_action(rest, current_controller_scope(stack))
            ctrl_path = nil.as(String?)
            action_name = nil.as(String?)
            action_params = [] of Param
            if ctrl_action
              ctrl_name, action = ctrl_action
              ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
              action_name = action
              action_params = params_for_action(ctrl_path, action, verb)
            end

            endpoint = Endpoint.new(url, verb, action_params, details)
            attach_callees_for_action(endpoint, ctrl_path, action_name) if action_name
            @result << endpoint
            next
          end

          # `get "path"` / `get "path" => "..."` / `get "path", to: "..."`.
          # The path literal may be empty (`get "" => "admin#index"` maps a
          # namespace to its bare prefix), so accept `*` not `+`. A `#{...}`
          # interpolation can embed its own quotes (`get
          # "/#{ENV.fetch('X', 'bb')}/:area"`), so consume those blocks
          # wholesale instead of stopping at the first inner quote — that
          # truncation surfaced a malformed `/#{ENV.fetch('` route.
          if sm = rest.match(/^\s*(['"])((?:\#\{[^}]*\}|(?!\1).)*)\1/)
            path = normalize_ruby_interpolation(strip_optional_route_segments(sm[2]))
            prefix = current_path_prefix_for_route(stack, route_scope)
            path_part = path.starts_with?("/") ? path : "/#{path}"
            url = prefix.empty? ? path_part : "/#{prefix}#{path_part}"
            # `get ""` / `get "/"` inside a namespace/scope composes to a
            # bare `/prefix/`; collapse the redundant trailing slash so the
            # URL matches the real route (`/admin`, not `/admin/`).
            url = url.rchop('/') if url.size > 1 && url.ends_with?('/')

            ctrl_action = parse_controller_action(rest, current_controller_scope(stack))
            action_params = [] of Param
            ctrl_path = nil.as(String?)
            action_name = nil.as(String?)
            if ctrl_action
              ctrl_name, action = ctrl_action
              ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
              action_name = action
              action_params = params_for_action(ctrl_path, action, verb)
            elsif inferred = infer_implicit_controller_action(path, rest, current_controller_scope(stack))
              ctrl_name, action = inferred
              ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
              action_name = action
              action_params = params_for_action(ctrl_path, action, verb)
            elsif parent = parent_resources_frame(stack)
              if action = infer_action_from_path(path)
                ctrl_path = parent.controller_path
                action_name = action
                action_params = params_for_action(ctrl_path, action, verb)
              end
            end

            endpoint = Endpoint.new(url, verb, action_params, details)
            attach_callees_for_action(endpoint, ctrl_path, action) if action = action_name
            @result << endpoint
            next
          end
          next
        end

        # `match` — Rails legacy multi-verb route. Requires `via:`
        # (or, on older codebases, defaults to ANY). Emits one
        # endpoint per verb listed under via, all sharing the
        # same path/controller#action.
        if call = route_call(line, ["match"])
          rest = call[1]
          if sm = rest.match(/^\s*['"]([^'"]*)['"]/)
            path = normalize_ruby_interpolation(strip_optional_route_segments(sm[1]))
            prefix = current_path_prefix_for_route(stack, parse_options(rest)["on"]?)
            path_part = path.starts_with?("/") ? path : "/#{path}"
            url = prefix.empty? ? path_part : "/#{prefix}#{path_part}"
            url = url.rchop('/') if url.size > 1 && url.ends_with?('/')

            match_verbs = parse_match_verbs(rest)
            ctrl_action = parse_controller_action(rest, current_controller_scope(stack))

            ctrl_path = nil.as(String?)
            action_name = nil.as(String?)
            if ctrl_action
              ctrl_name, action = ctrl_action
              ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
              action_name = action
            elsif inferred = infer_implicit_controller_action(path, rest, current_controller_scope(stack))
              ctrl_name, action = inferred
              ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
              action_name = action
            end

            match_verbs.each do |match_verb|
              action_params = if name = action_name
                                params_for_action(ctrl_path, name, match_verb)
                              else
                                [] of Param
                              end
              endpoint = Endpoint.new(url, match_verb, action_params, details)
              attach_callees_for_action(endpoint, ctrl_path, action_name) if action_name
              @result << endpoint
            end
          end
          next
        end

        # Unknown DSL line that still opens a block (e.g. `constraints ... do`).
        stack << Frame.new(:neutral) if opens_block
      end
    end

    private def current_concern_definition(stack : Array(Frame)) : String?
      if frame = stack.reverse.find { |f| f.kind == :concern }
        return frame.resource_name
      end
      nil
    end

    private def route_file_parse_key(path : String, stack : Array(Frame)) : String
      stack_key = stack.map do |frame|
        [
          frame.kind.to_s,
          frame.path,
          frame.controller_subdir,
          frame.resource_name || "",
          frame.controller_path || "",
          frame.controller_scope || "",
        ].join(":")
      end.join("|")

      "#{path}##{stack_key}"
    end

    # A `%w[...].each do |var|` / `%i[...].each_with_index do |var, i|`
    # block over a STATIC literal list unrolls to one copy of its body per
    # element with the loop variable's `#{var}` interpolations substituted.
    # discourse alone wraps ~46 routes in `%w[users u].each` — without this,
    # `get "#{root_path}/..."` leaks `{root_path}` into ~130 endpoints (a
    # fabricated path param) AND the real /users + /u variants are lost.
    #
    # Only literal `%w`/`%i` receivers are expanded: a dynamic
    # `Model.scopes.each do |s|` cannot be resolved to values at parse time,
    # so it is left for the normal parser (its block opens a neutral frame).
    LOOP_OPENER = /^%([wi])[\[\(\{]([^\]\)\}]*)[\]\)\}]\s*\.each(?:_with_index)?\s+do\s*\|\s*([a-z_]\w*)[^|]*\|\s*$/

    # noir scans arbitrary untrusted repos, so loop unrolling must not be a DoS
    # vector — expansion is multiplicative (elements ^ nesting). A crafted
    # `routes.rb` with deep nesting or a huge `%w[...]` list could otherwise
    # blow up CPU/memory. Real apps use tiny shallow lists (discourse's biggest
    # is the 2-element `%w[users u]`), so modest caps preserve all genuine
    # recall while bounding the worst case. Over a limit, the block is passed
    # through unexpanded (the pre-unrolling behavior — a transparent frame).
    MAX_LOOP_DEPTH  =      3
    MAX_LOOP_VALUES =    100
    MAX_LOOP_OUTPUT = 20_000

    private def expand_static_loops(lines : Array(String), depth : Int32 = 0) : Array(String)
      return lines if depth > MAX_LOOP_DEPTH
      return lines unless lines.any?(&.matches?(LOOP_OPENER))

      result = [] of String
      index = 0
      while index < lines.size
        line = lines[index]
        if m = line.match(LOOP_OPENER)
          var = m[3]
          values = m[2].split(/\s+/).reject(&.empty?)

          # Walk to the `end` that closes this `.each do`, mirroring the main
          # parser's one-block-open-per-line / `end`-pops-one model.
          block_depth = 1
          body = [] of String
          cursor = index + 1
          while cursor < lines.size && block_depth > 0
            body_line = lines[cursor]
            if end_line?(body_line)
              block_depth -= 1
              break if block_depth == 0
            elsif opens_do_block?(body_line) || opens_keyword_block?(body_line)
              block_depth += 1
            end
            body << body_line
            cursor += 1
          end

          if values.size > MAX_LOOP_VALUES || result.size > MAX_LOOP_OUTPUT
            # Over budget: emit the block verbatim so the main parser handles
            # it as a neutral frame instead of unrolling an attacker-sized fan-out.
            (index..cursor).each { |i| result << lines[i] if i < lines.size }
          else
            expanded_body = expand_static_loops(body, depth + 1)
            # Precompile the substitution once per loop var (Crystal recompiles
            # an interpolated regex literal on every match).
            pattern = Regex.new("\\#\\{\\s*#{Regex.escape(var)}\\s*\\}")
            values.each do |value|
              break if result.size > MAX_LOOP_OUTPUT
              expanded_body.each { |unrolled| result << unrolled.gsub(pattern, value) }
            end
          end
          index = cursor + 1 # skip the closing `end`
        else
          result << line
          index += 1
        end
      end

      result
    end

    # Rails commonly writes compact inline route scopes:
    # `collection { get "preview" }` / `member { post :use }`.
    # The parser is stack-based, so normalize these to the same do/end
    # structure before route extraction.
    INLINE_ROUTE_BLOCK = /^(member|collection|new)\s*\{\s*(.+?)\s*\}\s*$/

    private def expand_inline_route_blocks(lines : Array(String)) : Array(String)
      result = [] of String
      lines.each do |line|
        if m = line.match(INLINE_ROUTE_BLOCK)
          result << "#{m[1]} do"
          result << m[2].strip
          result << "end"
        else
          result << line
        end
      end
      result
    end

    private def end_line?(line : String) : Bool
      line == "end" || line.starts_with?("end ") || line.starts_with?("end;") || line.starts_with?("end#")
    end

    # Scan the files that declare engine mounts (`config/routes.rb`,
    # `plugin.rb` — discourse pins every plugin's `mount X::Engine, at:`
    # there) and build the engine-constant -> mount-path map. Forms handled:
    #   mount X::Engine, at: "/p"        mount X::Engine => "/p"
    #   Discourse::Application.routes.append { mount X::Engine, at: "/p" }
    private def build_engine_mount_map(files : Array(String)) : Hash(EngineMountKey, String)
      map = Hash(EngineMountKey, String).new
      files.each do |file|
        base = File.basename(file)
        next unless base == "plugin.rb" || base.ends_with?("routes.rb")
        content = read_file_content(file)
        next unless content.includes?("mount")

        content.each_line do |raw|
          line = strip_inline_comment(raw)
          next unless line.includes?("mount")
          if m = line.match(/\bmount\b\s*\(?\s*(?:::)?([A-Z][A-Za-z0-9_:]*)\s*(?:,\s*at:\s*|=>\s*)['"]([^'"]+)['"]/)
            const = m[1]
            key = {configured_base_for(file), const}
            map[key] = normalize_mount_prefix(m[2]) unless map.has_key?(key)
          end
        end
      end
      map
    end

    private def normalize_mount_prefix(at : String) : String
      prefix = at.strip
      return "" if prefix.empty? || prefix == "/"
      prefix = prefix.rchop('/') if prefix.size > 1 && prefix.ends_with?('/')
      prefix.lchop('/')
    end

    private def logical_route_lines(routes_path : String) : Array(String)
      lines = [] of String
      buffer = ""
      paren_depth = 0
      bracket_depth = 0
      brace_depth = 0

      File.open(routes_path, "r", encoding: "utf-8", invalid: :skip) do |file|
        file.each_line do |raw_line|
          stripped = strip_inline_comment(raw_line).strip
          next if stripped.empty?

          buffer = buffer.empty? ? stripped : "#{buffer} #{stripped}"
          delta = delimiter_delta(stripped)
          paren_depth += delta[0]
          bracket_depth += delta[1]
          brace_depth += delta[2]

          next if paren_depth > 0 || bracket_depth > 0 || brace_depth > 0
          next if stripped.ends_with?(",")

          lines << buffer
          buffer = ""
          paren_depth = 0
          bracket_depth = 0
          brace_depth = 0
        end
      end

      lines << buffer unless buffer.empty?
      lines
    end

    private def delimiter_delta(line : String) : Tuple(Int32, Int32, Int32)
      paren = 0
      bracket = 0
      brace = 0
      in_str = false
      escaped = false
      quote = '\0'

      line.each_char do |c|
        if in_str
          if escaped
            escaped = false
          elsif c == '\\'
            escaped = true
          elsif c == quote
            in_str = false
          end
          next
        end

        if c == '"' || c == '\''
          in_str = true
          quote = c
          next
        end

        case c
        when '('
          paren += 1
        when ')'
          paren -= 1
        when '['
          bracket += 1
        when ']'
          bracket -= 1
        when '{'
          brace += 1
        when '}'
          brace -= 1
        end
      end

      {paren, bracket, brace}
    end

    private def route_call(line : String, names : Array(String)) : Tuple(String, String)?
      names.each do |name|
        next unless line.starts_with?(name)
        after = line[name.size, line.size - name.size]
        next if after.matches?(/\A[A-Za-z0-9_]/)

        stripped = after.lstrip
        if stripped.starts_with?("(")
          return {name, stripped[1, stripped.size - 1].strip}
        end
        return {name, stripped.strip}
      end
      nil
    end

    private def parse_first_route_name(args : String) : String?
      if m = args.match(/^\s*(?::([A-Za-z_]\w*)|['"]([^'"]+)['"])/)
        return (m[1]? || m[2]?).to_s
      end
      nil
    end

    private def current_custom_route_scope(stack : Array(Frame)) : String?
      if frame = stack.last?
        return frame.kind.to_s if frame.kind == :member || frame.kind == :collection || frame.kind == :new
      end
      nil
    end

    private def current_path_prefix_for_route(stack : Array(Frame), route_scope : String?) : String
      prefix = current_path_prefix(stack)
      return prefix if prefix.empty?

      case route_scope
      when "collection"
        prefix.ends_with?("/1") ? prefix[0, prefix.size - 2] : prefix
      when "new"
        prefix.ends_with?("/1") ? "#{prefix[0, prefix.size - 2]}/new" : "#{prefix}/new"
      else
        prefix
      end
    end

    private def custom_resource_action_url(stack : Array(Frame), action : String, route_scope : String?) : String?
      resources_idx = nil
      stack.each_with_index do |f, i|
        resources_idx = i if f.kind == :resources
      end
      return if resources_idx.nil?

      parts = [] of String
      stack[0, resources_idx].each do |f|
        parts << f.path unless f.path.empty?
      end

      rf = stack[resources_idx]
      seg = rf.path
      case route_scope
      when "collection"
        seg = seg[0, seg.size - 2] if seg.ends_with?("/1")
      when "new"
        seg = seg.ends_with?("/1") ? "#{seg[0, seg.size - 2]}/new" : "#{seg}/new"
      end

      parts << seg unless seg.empty?
      parts << action
      "/" + parts.join("/")
    end

    private def current_controller_scope(stack : Array(Frame)) : String?
      stack.reverse_each do |f|
        return f.controller_scope if f.controller_scope
      end
      nil
    end

    private def infer_action_from_path(path : String) : String?
      normalized = path.lchop("/")
      return normalized if normalized.matches?(/\A[A-Za-z_]\w*\z/)
      nil
    end

    private def current_concern_relative_stack(stack : Array(Frame)) : Array(Frame)
      index = stack.size - 1
      while index >= 0
        if stack[index].kind == :concern
          return [] of Frame if index == stack.size - 1
          return stack[(index + 1)..].dup
        end
        index -= 1
      end
      [] of Frame
    end

    private def emit_concern_resources(names : Array(String),
                                       concern_resources : Hash(String, Array(ConcernResource)),
                                       framework_root : String,
                                       stack : Array(Frame))
      names.each do |name|
        next unless resources = concern_resources[name]?
        resources.each do |resource|
          emit_resource_routes(framework_root, stack + resource.stack, resource.kind_kw, resource.name, resource.options)
        end
      end
    end

    private def emit_resource_routes(framework_root : String,
                                     stack : Array(Frame),
                                     kind_kw : String,
                                     name : String,
                                     options : Hash(String, String)) : String?
      singular = (kind_kw == "resource")
      controller_subdir = current_controller_subdir(stack)
      # `module:` on a `resources`/`resource` line nests the controller
      # under an extra namespace directory WITHOUT changing the URL —
      # `resources :accounts, module: :lists` is served by
      # `Lists::AccountsController` (app/controllers/.../lists/accounts_controller.rb).
      # The namespace/scope `module:` is already folded into the stack via
      # `controller_subdir`; the per-line one is not, so apply it here.
      if line_module = options["module"]?
        controller_subdir = controller_subdir.empty? ? line_module : "#{controller_subdir}/#{line_module}"
      end
      ctrl_override = options["controller"]?
      file_base = if ctrl_override
                    ctrl_override.includes?('/') ? ctrl_override : (controller_subdir.empty? ? ctrl_override : "#{controller_subdir}/#{ctrl_override}")
                  else
                    controller_subdir.empty? ? name : "#{controller_subdir}/#{name}"
                  end

      only_list = parse_symbol_list(options["only"]?)
      except_list = parse_symbol_list(options["except"]?)
      url_segment = options["path"]? || name
      path_prefix = current_path_prefix(stack)

      candidates = [] of String
      candidates << "#{framework_root}/app/controllers/#{file_base}_controller.rb"
      unless ctrl_override
        candidates << "#{framework_root}/app/controllers/#{file_base}s_controller.rb"
        candidates << "#{framework_root}/app/controllers/#{file_base}es_controller.rb"
        # Irregular y->ies plural: a singular `resource :directory` is backed
        # by `DirectoriesController` (directories_controller.rb), never
        # `directorys`/`directoryes`.
        candidates << "#{framework_root}/app/controllers/#{file_base.rchop('y')}ies_controller.rb" if file_base.ends_with?('y')
      end

      existing_controller_path = candidates.find { |c| known_file?(c) }
      candidates.each do |ctrl_path|
        @result += controller_to_endpoint(
          ctrl_path, @url, url_segment,
          path_prefix: path_prefix,
          only: only_list,
          except: except_list,
          singular: singular,
        )
      end

      existing_controller_path
    end

    # Expand a `use_doorkeeper` block into the OAuth routes Doorkeeper
    # mounts. `skip` drops `skip_controllers :group` rows; `controller_map`
    # carries the `controllers group: 'path'` remap so params/callees can
    # still resolve against the app's own controller (Mastodon points
    # `authorizations` at `app/controllers/oauth/authorizations_controller.rb`).
    # Default (un-remapped) groups resolve against `doorkeeper/<group>`,
    # which the host app rarely ships, so they emit the endpoint alone.
    private def emit_doorkeeper_routes(framework_root : String,
                                       stack : Array(Frame),
                                       skip : Set(String),
                                       controller_map : Hash(String, String),
                                       details : Details)
      prefix = current_path_prefix(stack)
      DOORKEEPER_ROUTES.each do |verb, sub, group, action|
        next if skip.includes?(group)

        url = prefix.empty? ? sub : "/#{prefix}#{sub}"
        ctrl_name = controller_map[group]? || "doorkeeper/#{group}"
        ctrl_path = find_controller_file(framework_root, ctrl_name, stack)
        action_params = ctrl_path ? params_for_action(ctrl_path, action, verb) : ([] of Param)
        endpoint = Endpoint.new(url, verb, action_params, details)
        attach_callees_for_action(endpoint, ctrl_path, action)
        @result << endpoint
      end
    end

    # Pull the verb list out of a `match ... :via => :get` or
    # `match ... via: [:get, :post]` declaration. Returns the
    # single-element `["ANY"]` when `via:` is missing or empty —
    # modern Rails raises in that case but the older Redmine
    # idiom is permissive.
    private def parse_match_verbs(rest : String) : Array(String)
      parse_route_verbs(rest, ["ANY"])
    end

    private def parse_route_verbs(rest : String, default_verbs : Array(String)) : Array(String)
      via_match = rest.match(/:?via\s*(?:=>|:)\s*(\[[^\]]+\]|%i[\[\(][^\]\)]*[\]\)]|:\w+|['"][A-Za-z_]+['"])/)
      return default_verbs unless via_match
      tail = via_match[1]
      verbs = [] of String
      parse_symbol_list(tail).each do |verb|
        normalized = verb.upcase
        normalized = "ANY" if normalized == "ALL"
        verbs << normalized
      end
      verbs.empty? ? default_verbs : verbs.uniq
    end

    private def strip_inline_comment(line : String) : String
      in_str = false
      escaped = false
      quote = '\0'
      line.each_char_with_index do |c, i|
        if in_str
          if escaped
            escaped = false
          elsif c == '\\'
            escaped = true
          elsif c == quote
            in_str = false
          end
        else
          if c == '"' || c == '\''
            in_str = true
            quote = c
          elsif c == '#'
            return line[0, i]
          end
        end
      end
      line
    end

    private def opens_do_block?(line : String) : Bool
      !!line.match(/\bdo\b\s*(\|[^|]*\|)?\s*\z/)
    end

    # Statement-position `if`/`unless`/`case`/`begin`/`while`/`until`/`for`
    # open a block that a later bare `end` closes. The `end` handler always
    # pops one stack frame, so without crediting these openers a conditional
    # like `if Rails.env.test? ... end` wrapped around routes pops a *real*
    # scope (Spree's `POST /admin/table_columns` leaked out as
    # `/table_columns` once the `if` block above it closed). They carry no
    # path/module of their own, so a transparent `:neutral` frame keeps the
    # surrounding prefix intact for routes inside and restores it after.
    # Modifier forms (`get 'x' if cond`, `redirect_to y unless z`) keep the
    # keyword mid-line, never at the anchored start, so they stay uncounted.
    private def opens_keyword_block?(line : String) : Bool
      return false unless line.matches?(/^(?:if|unless|case|begin|while|until|for)\b/)
      !line.matches?(/\bend\b/)
    end

    # Rails route strings carry optional segments in parentheses —
    # `(.:format)`, `(/page/:page)`, even nested `(/:length(/page/:page))`.
    # They are DSL syntax, not part of any concrete URL, so emitting
    # `/domain/:id(.:format)` hands a consumer a path that 404s when hit
    # literally. Peel every (possibly nested) optional group down to the
    # required base path, then collapse the `//` and trailing-`/`
    # artifacts the removal can leave behind. `(.:format)` is appended to
    # most Rails string routes, so this touches nearly every app.
    private def strip_optional_route_segments(path : String) : String
      return path unless path.includes?('(')

      result = path
      loop do
        stripped = result.gsub(/\([^()]*\)/, "")
        break if stripped == result
        result = stripped
      end

      result = result.gsub(%r{/{2,}}, "/")
      result = result.rchop('/') if result.size > 1 && result.ends_with?('/')
      result
    end

    private def normalize_route_prefix(path : String) : String
      normalized = strip_optional_route_segments(path).lchop('/')
      normalized = normalized.rchop('/') if normalized.size > 1 && normalized.ends_with?('/')
      normalized
    end

    private def parse_options(line : String) : Hash(String, String)
      result = {} of String => String
      value_pattern = "nil|['\"][^'\"]+['\"]|:[a-zA-Z_]\\w*|\\[[^\\]]*\\]|%i[\\[\\(][^\\]\\)]*[\\]\\)]|%w[\\[\\(][^\\]\\)]*[\\]\\)]"
      # capture key: "value", key: :symbol, key: [..], key: %i[..], and
      # older hash-rocket forms like :only => [:index].
      line.scan(Regex.new("(\\w+):\\s*(#{value_pattern})")) do |m|
        key = m[1]
        result[key] = normalize_option_value(m[2])
      end
      line.scan(Regex.new(":(\\w+)\\s*=>\\s*(#{value_pattern})")) do |m|
        key = m[1]
        result[key] = normalize_option_value(m[2])
      end
      result
    end

    private def normalize_option_value(raw : String) : String
      return "" if raw == "nil"
      if raw.starts_with?('"') || raw.starts_with?('\'')
        raw[1, raw.size - 2]
      elsif raw.starts_with?(':')
        raw[1, raw.size - 1]
      elsif raw.starts_with?("%i") || raw.starts_with?("%w")
        raw[3, raw.size - 4]
      else
        raw[1, raw.size - 2] # strip [ ]
      end
    end

    private def parse_symbol_list(raw : String?) : Array(String)
      return [] of String if raw.nil?
      cleaned = raw.gsub(/%[iw][\[\(]/, "").gsub(/[\[\]\(\)'"]/, "")
      cleaned.split(/[,\s]+/).map(&.strip.lchop(':').strip).reject(&.empty?)
    end

    private def current_path_prefix(stack : Array(Frame)) : String
      parts = [] of String
      stack.each do |f|
        next if f.path.empty?
        parts << f.path
      end
      parts.join("/")
    end

    private def current_controller_subdir(stack : Array(Frame)) : String
      parts = [] of String
      stack.each do |f|
        next if f.controller_subdir.empty?
        parts << f.controller_subdir
      end
      parts.join("/")
    end

    # Build URL for a `get :action` inside member/collection blocks. For
    # member: uses the parent resource's `name/1` prefix; for collection:
    # strips the trailing `/1` so the action sits on the index URL.
    private def member_collection_url(stack : Array(Frame), action : String, in_collection : Bool) : String?
      resources_idx = nil
      stack.each_with_index do |f, i|
        resources_idx = i if f.kind == :resources
      end
      return if resources_idx.nil?

      parts = [] of String
      stack[0, resources_idx].each do |f|
        parts << f.path unless f.path.empty?
      end
      rf = stack[resources_idx]
      seg = rf.path
      if in_collection && seg.ends_with?("/1")
        seg = seg[0, seg.size - 2]
      end
      parts << seg unless seg.empty?
      parts << action
      "/" + parts.join("/")
    end

    def controller_to_endpoint(
      path : String,
      @url : String,
      resource : String,
      path_prefix : String = "",
      only : Array(String) = [] of String,
      except : Array(String) = [] of String,
      singular : Bool = false,
    )
      @result = [] of Endpoint

      return @result unless known_file?(path)

      data = extract_controller_data(path)
      defined_actions = data.defined_actions

      methods = [] of String
      {"index", "show", "create", "update", "destroy"}.each do |name|
        next unless defined_actions.includes?(name)
        next unless action_allowed?(name, only, except)
        case name
        when "index"
          methods << "GET/INDEX" unless singular
        when "show"
          methods << "GET/SHOW"
        when "create"
          methods << "POST"
        when "update"
          methods << "PUT"
          methods << "PATCH"
        when "destroy"
          methods << "DELETE"
        end
      end

      index_url = compose_url(path_prefix, "/#{resource}")
      member_url = compose_url(path_prefix, singular ? "/#{resource}" : "/#{resource}/1")

      methods.each do |method|
        case method
        when "GET/INDEX"
          last_params = action_params(data, "index", "GET")
          details = Details.new(PathInfo.new(path, data.action_lines["index"]?))
          endpoint = Endpoint.new(index_url, "GET", last_params, details)
          attach_callees_for_action(endpoint, data, "index")
          @result << endpoint
        when "GET/SHOW"
          last_params = promote_identifier_to_path(action_params(data, "show", "GET"))
          details = Details.new(PathInfo.new(path, data.action_lines["show"]?))
          endpoint = Endpoint.new(member_url, "GET", last_params, details)
          attach_callees_for_action(endpoint, data, "show")
          @result << endpoint
        when "POST"
          last_params = action_params(data, "create", method)
          details = Details.new(PathInfo.new(path, data.action_lines["create"]?))
          endpoint = Endpoint.new(index_url, method, last_params, details)
          attach_callees_for_action(endpoint, data, "create")
          @result << endpoint
        when "DELETE"
          last_params = promote_identifier_to_path(action_params(data, "destroy", method))
          details = Details.new(PathInfo.new(path, data.action_lines["destroy"]?))
          endpoint = Endpoint.new(member_url, method, last_params, details)
          attach_callees_for_action(endpoint, data, "destroy")
          @result << endpoint
        else
          last_params = promote_identifier_to_path(action_params(data, "update", method))
          details = Details.new(PathInfo.new(path, data.action_lines["update"]?))
          endpoint = Endpoint.new(member_url, method, last_params, details)
          attach_callees_for_action(endpoint, data, "update")
          @result << endpoint
        end
      end

      @result
    end

    # Scans a controller file once, collecting per-method params (headers/cookies)
    # plus shared params (params[:x] / params["x"], params.require...permit) and
    # the names of every `def`. Shared because the existing heuristic associates
    # params[:x] with the whole controller, not a specific action. Results are
    # memoized per path so re-resolution (resources + member/collection + `to:`)
    # only reads each controller once.
    private def extract_controller_data(path : String) : ControllerData
      cached = @controller_data_cache[path]?
      return cached if cached

      params_method = Hash(String, Array(Param)).new
      params_body_by_action = Hash(String, Array(Param)).new
      params_query_by_action = Hash(String, Array(Param)).new
      defined_actions = Set(String).new
      helper_calls_by_action = Hash(String, Array(String)).new
      callees_by_action = Hash(String, Array(Noir::RubyCalleeExtractor::Entry)).new
      action_lines = Hash(String, Int32).new
      method_bodies = Hash(String, Array(String)).new
      param_type = "form"

      unless known_file?(path)
        empty = ControllerData.new(param_type, params_method, params_body_by_action, params_query_by_action,
          defined_actions, helper_calls_by_action, callees_by_action, action_lines)
        @controller_data_cache[path] = empty
        return empty
      end

      File.open(path, "r", encoding: "utf-8", invalid: :skip) do |controller_file|
        controller_content = controller_file.gets_to_end
        param_type = "json" if controller_content.includes?("render json:")
        callees_by_action = extract_action_callees(controller_content, path) if callees_needed?

        controller_file.rewind
        this_method = ""

        controller_file.each_line.with_index do |raw_line, index|
          line = strip_inline_comment(raw_line)

          if line.includes?("def ")
            func_name = line.split("def ", 2)[1].split("(")[0].split(";")[0].strip
            func_name = func_name.lchop("self.").strip
            unless func_name.empty?
              this_method = func_name
              defined_actions << func_name
              action_lines[func_name] = index + 1
              method_bodies[this_method] ||= [] of String
            end
          end

          unless this_method.empty?
            method_bodies[this_method] ||= [] of String
            method_bodies[this_method] << line
          end

          if pm = line.match(/permit\s*\(([^)]*)\)/)
            pm[1].split(',').each do |raw|
              name = raw.gsub(/[:\s'"]/, "")
              next if name.empty? || this_method.empty?
              # A permit list entry is always a lowercase symbol/string key
              # (`:title`, `tag_ids`). Splat-of-constant args
              # (`permit(*PERMITTED_PARAMS)`, `permit(:a, *Filter::KEYS)`)
              # and the garbage left by naive comma-splitting of nested
              # `key: [...]` forms survive the quote/colon strip as
              # `*PERMITTED_PARAMS` / `*FilterKEYS` / `address[city`. Drop
              # anything that isn't a clean identifier so those don't leak
              # in as fabricated param names.
              next unless name.matches?(/\A[a-z_][a-z0-9_]*\z/)
              params_body_by_action[this_method] ||= [] of Param
              params_body_by_action[this_method] << Param.new(name, "", param_type)
              params_query_by_action[this_method] ||= [] of Param
              params_query_by_action[this_method] << Param.new(name, "", "query")
            end
          end

          line.scan(/params\[\s*(?::(\w+)|['"]([^'"]+)['"])\s*\]/) do |m|
            name = (m[1]? || m[2]?).to_s.strip
            next if name.empty? || this_method.empty?
            params_body_by_action[this_method] ||= [] of Param
            params_body_by_action[this_method] << Param.new(name, "", param_type)
            params_query_by_action[this_method] ||= [] of Param
            params_query_by_action[this_method] << Param.new(name, "", "query")
          end

          if hm = line.match(/request\.headers\[\s*['"]([^'"]+)['"]\s*\]/)
            name = hm[1].strip
            if !name.empty? && !this_method.empty?
              params_method[this_method] ||= [] of Param
              params_method[this_method] << Param.new(name, "", "header")
            end
          end

          line.scan(/cookies(?:\.(?:signed|encrypted))?\[\s*(?::(\w+)|['"]([^'"]+)['"])\s*\]/) do |cm|
            name = (cm[1]? || cm[2]?).to_s.strip
            next if name.empty? || this_method.empty?
            params_method[this_method] ||= [] of Param
            params_method[this_method] << Param.new(name, "", "cookie")
          end
        end
      end

      helper_calls_by_action = build_helper_call_map(method_bodies, defined_actions)

      data = ControllerData.new(param_type, params_method, params_body_by_action, params_query_by_action,
        defined_actions, helper_calls_by_action, callees_by_action, action_lines)
      @controller_data_cache[path] = data
      data
    end

    private def extract_action_callees(content : String, path : String) : Hash(String, Array(Noir::RubyCalleeExtractor::Entry))
      result = Hash(String, Array(Noir::RubyCalleeExtractor::Entry)).new
      lines = content.lines
      index = 0

      while index < lines.size
        stripped = strip_inline_comment(lines[index]).strip
        if m = stripped.match(/^(?:private\s+|protected\s+|public\s+)?def\s+(?:self\.)?([A-Za-z_]\w*[!?=]?)\b/)
          action = m[1]
          inline_body, closed_on_def_line = inline_def_body(stripped, m[0])
          body_lines = [] of String
          body_start_line = inline_body ? index + 1 : index + 2
          body_lines << inline_body if inline_body

          unless closed_on_def_line
            depth = 1
            index += 1

            while index < lines.size
              raw_body_line = lines[index]
              body_line = strip_inline_comment(raw_body_line).strip

              if closes_ruby_block?(body_line)
                depth -= 1
                break if depth == 0
                body_lines << raw_body_line
                index += 1
                next
              end

              body_lines << raw_body_line
              depth += ruby_block_open_delta(body_line)
              index += 1
            end
          end

          callees = Noir::RubyCalleeExtractor.callees_for_body(body_lines.join("\n"), path, body_start_line)
          result[action] = callees unless callees.empty?
        end

        index += 1
      end

      result
    end

    private def inline_def_body(line : String, match_text : String) : Tuple(String?, Bool)
      return {nil, false} if match_text.size >= line.size

      tail = line[match_text.size, line.size - match_text.size].strip
      return {nil, false} unless tail.starts_with?(";")

      tail = tail[1, tail.size - 1].strip
      if m = tail.match(/^(.*?)(?:;\s*)?end\b/)
        body = m[1].strip
        return {body.empty? ? nil : body, true}
      end

      {tail.empty? ? nil : tail, false}
    end

    private def ruby_block_open_delta(line : String) : Int32
      return 0 if line.empty?
      return 1 if line.match(/\bdo\b\s*(\|[^|]*\|)?\s*\z/)
      return 1 if line.match(/^(if|unless|case|begin|while|until|for|class|module|def)\b/) && !line.match(/\bend\b/)
      0
    end

    private def closes_ruby_block?(line : String) : Bool
      !!line.match(/^end\b/)
    end

    private def dedup_by_name(params : Array(Param)) : Array(Param)
      seen = Set(String).new
      params.each_with_object([] of Param) do |p, acc|
        next if seen.includes?(p.name)
        seen << p.name
        acc << p
      end
    end

    # Build params for a custom action (member/collection or explicit
    # controller#action). Mirrors the resources flow: per-action headers/cookies
    # plus the action-local body/query params for the verb.
    private def params_for_action(controller_path : String?, action : String, verb : String) : Array(Param)
      return [] of Param if controller_path.nil?
      data = extract_controller_data(controller_path)
      return [] of Param unless data.defined_actions.includes?(action)

      action_params(data, action, verb)
    end

    private def action_params(data : ControllerData, action : String, verb : String) : Array(Param)
      result = [] of Param
      merge_action_params(result, data, action, verb)

      helper_names = data.helper_calls_by_action[action]? || [] of String
      helper_names.each do |helper_name|
        next if helper_name == action
        merge_action_params(result, data, helper_name, verb)
      end

      result
    end

    private def merge_action_params(result : Array(Param), data : ControllerData, action : String, verb : String)
      data.params_method[action]?.try &.each { |p| push_unique_param(result, clone_param(p)) }

      source_params = case verb
                      when "GET", "HEAD", "OPTIONS", "DELETE"
                        dedup_by_name(data.params_query_by_action[action]? || [] of Param)
                      else
                        dedup_by_name(data.params_body_by_action[action]? || [] of Param)
                      end

      source_params.each do |param|
        push_unique_param(result, clone_param(param))
      end
    end

    private def push_unique_param(params : Array(Param), param : Param)
      params << param unless params.any? { |existing| existing.name == param.name && existing.param_type == param.param_type }
    end

    private def promote_identifier_to_path(params : Array(Param)) : Array(Param)
      params.each_index do |index|
        next unless params[index].name == "id"
        param = params[index]
        param.param_type = "path"
        params[index] = param
      end
      params
    end

    private def clone_param(param : Param) : Param
      Param.new(param.name, param.value, param.param_type)
    end

    private def build_helper_call_map(method_bodies : Hash(String, Array(String)), defined_actions : Set(String)) : Hash(String, Array(String))
      helper_calls = Hash(String, Array(String)).new

      # Tokenize each method body once into the set of identifiers it
      # references, then test action names by set membership. The previous
      # shape compiled an interpolated `/\b#{candidate}\b/` and rescanned
      # the whole body for every (method × action) pair — O(M·A) recompiled
      # regexes per controller, quadratic in the action count. Whole-token
      # set membership is equivalent to the `\b…\b` word-boundary match for
      # identifier names while running in O(M·body + M·A).
      method_bodies.each do |method_name, body_lines|
        tokens = Set(String).new
        body_lines.each do |line|
          line.scan(/[A-Za-z_]\w*[!?=]?/) { |m| tokens << m[0] }
        end

        matches = [] of String
        defined_actions.each do |candidate|
          next if candidate == method_name
          matches << candidate if tokens.includes?(candidate)
        end
        helper_calls[method_name] = matches unless matches.empty?
      end

      helper_calls
    end

    private def attach_callees_for_action(endpoint : Endpoint, controller_path : String?, action : String)
      return if controller_path.nil?
      attach_callees_for_action(endpoint, extract_controller_data(controller_path), action)
    end

    private def attach_callees_for_action(endpoint : Endpoint, data : ControllerData, action : String)
      return unless callees_needed?
      if callees = data.callees_by_action[action]?
        attach_ruby_callees(endpoint, callees)
      end
    end

    # Callees feed both `--include-callee` (direct output) and `--ai-context`
    # (aggregated review context). Extraction is skipped when neither flag is
    # set so default scans avoid the controller-body walk per action.
    private def callees_needed? : Bool
      any_to_bool(@options["include_callee"]?) || any_to_bool(@options["ai_context"]?)
    end

    private def parent_resources_frame(stack : Array(Frame)) : Frame?
      stack.reverse_each do |f|
        return f if f.kind == :resources
      end
      nil
    end

    # Parses `=> "ctrl#action"`, `to: "ctrl#action"`,
    # `controller: "ctrl", action: :show`, and controller-block
    # `get "path" => :action` forms.
    private def parse_controller_action(rest : String, scoped_controller : String? = nil) : Tuple(String, String)?
      if m = rest.match(/=>\s*['"]([^'"#]+)#([\w]+)['"]/)
        return {m[1], m[2]}
      end
      if m = rest.match(/to:\s*['"]([^'"#]+)#([\w]+)['"]/)
        return {m[1], m[2]}
      end
      options = parse_options(rest)
      if controller = options["controller"]?
        if action = options["action"]?
          return {controller, action}
        end
      end
      if scoped_controller
        if action = options["action"]?
          return {scoped_controller, action}
        end
        if m = rest.match(/(?:=>|to:)\s*:(\w+)/)
          return {scoped_controller, m[1]}
        end
      end
      nil
    end

    private def controller_action_for_symbol_route(rest : String, fallback : String) : String
      parse_options(rest)["action"]? || fallback
    end

    # Rails allows compact declarations such as `post "stories/preview"`
    # which route to `StoriesController#preview`. These still need controller
    # resolution so params/callees/AI context attach to the emitted endpoint.
    private def infer_implicit_controller_action(path : String, rest : String,
                                                 scoped_controller : String? = nil) : Tuple(String, String)?
      return if explicit_route_destination?(rest)

      segments = static_route_segments(path)
      return if segments.empty?

      if scoped_controller
        action = segments.last
        return unless valid_action_name?(action)
        return {scoped_controller, action}
      end

      return if segments.size < 2
      action = segments.last
      return unless valid_action_name?(action)

      {segments[0, segments.size - 1].join("/"), action}
    end

    private def explicit_route_destination?(rest : String) : Bool
      !!rest.match(/^\s*['"][^'"]+['"]\s*=>/) ||
        !!rest.match(/\bto\s*:/) ||
        !!rest.match(/:?to\s*=>/) ||
        !!rest.match(/:?controller\s*(?:=>|:)/) ||
        !!rest.match(/:?action\s*(?:=>|:)/)
    end

    private def static_route_segments(path : String) : Array(String)
      path.lchop('/').split('/').map do |segment|
        segment = segment.split('.', 2)[0]
        return [] of String if segment.empty?
        return [] of String if segment.includes?(':') || segment.includes?('*')
        return [] of String if segment.includes?('(') || segment.includes?(')')
        segment
      end
    end

    private def valid_action_name?(name : String) : Bool
      !!name.match(/\A[A-Za-z_]\w*[!?=]?\z/)
    end

    # Resolve `ctrl#action` to a controller file. When the route lives inside a
    # `namespace :admin` block, Rails resolves "monitor#ping" to
    # `Admin::MonitorController` — try the subdir-prefixed path first, then fall
    # back to a bare lookup so absolute-style references ("api/v1/users") still
    # work regardless of where they're declared.
    private def find_controller_file(framework_root : String, ctrl_name : String,
                                     stack : Array(Frame) = [] of Frame) : String?
      return if ctrl_name.empty?
      candidates = [] of String
      subdir = current_controller_subdir(stack)
      if !subdir.empty? && !ctrl_name.includes?('/')
        candidates << "#{framework_root}/app/controllers/#{subdir}/#{ctrl_name}_controller.rb"
      end
      candidates << "#{framework_root}/app/controllers/#{ctrl_name}_controller.rb"
      candidates.find { |c| known_file?(c) }
    end

    private def action_allowed?(name : String, only : Array(String), except : Array(String)) : Bool
      return false if !only.empty? && !only.includes?(name)
      return false if except.includes?(name)
      true
    end

    private def compose_url(prefix : String, suffix : String) : String
      return suffix if prefix.empty?
      "/#{prefix}#{suffix}"
    end
  end
end
