require "../models/output_builder"
require "../models/endpoint"
require "./oas_common"
require "json"

class OutputBuilderOas3 < OutputBuilder
  include OutputBuilderOasCommon

  def print(endpoints : Array(Endpoint))
    paths = {} of String => Hash(String, JSON::Any)

    endpoints.each do |endpoint|
      next if endpoint.non_http? # deep links / CLI commands aren't HTTP paths; keep them out of the spec
      parameters = [] of Hash(String, JSON::Any)
      json_properties = {} of String => JSON::Any
      form_properties = {} of String => JSON::Any

      endpoint.params.each do |param|
        case param.param_type
        when "json"
          # JSON body parameters go into requestBody
          json_properties[param.name] = JSON::Any.new({
            "type" => JSON::Any.new("string"),
          } of String => JSON::Any)
        when "form"
          # Form data parameters go into requestBody
          form_properties[param.name] = JSON::Any.new({
            "type" => JSON::Any.new("string"),
          } of String => JSON::Any)
        when "header"
          # Header parameters
          append_unique_parameter(parameters, openapi_parameter(param.name, "header", false))
        when "path"
          # Path parameters
          append_unique_parameter(parameters, openapi_parameter(param.name, "path", true))
        when "cookie"
          # Cookie parameters (supported in OAS3)
          append_unique_parameter(parameters, openapi_parameter(param.name, "cookie", false))
        else
          # Default to query parameter
          append_unique_parameter(parameters, openapi_parameter(param.name, "query", false))
        end
      end

      oas_path = normalize_oas_path(endpoint.url)
      path_template_names(oas_path).each do |name|
        append_unique_parameter(parameters, openapi_parameter(name, "path", true))
      end

      # Build operation object
      operation = {
        "responses" => JSON::Any.new({
          "200" => JSON::Any.new({
            "description" => JSON::Any.new("Successful response"),
            "content"     => JSON::Any.new({
              "application/json" => JSON::Any.new({
                "schema" => JSON::Any.new({
                  "type" => JSON::Any.new("object"),
                } of String => JSON::Any),
              } of String => JSON::Any),
            } of String => JSON::Any),
          } of String => JSON::Any),
        } of String => JSON::Any),
        "parameters" => JSON::Any.new(parameters.map { |p| JSON::Any.new(p) }),
      } of String => JSON::Any

      request_content = {} of String => JSON::Any

      # Add requestBody for JSON content
      unless json_properties.empty?
        request_content["application/json"] = JSON::Any.new({
          "schema" => JSON::Any.new({
            "type"       => JSON::Any.new("object"),
            "properties" => JSON::Any.new(json_properties),
          } of String => JSON::Any),
        } of String => JSON::Any)
      end

      # Add requestBody for form data
      unless form_properties.empty?
        request_content["application/x-www-form-urlencoded"] = JSON::Any.new({
          "schema" => JSON::Any.new({
            "type"       => JSON::Any.new("object"),
            "properties" => JSON::Any.new(form_properties),
          } of String => JSON::Any),
        } of String => JSON::Any)
      end

      unless request_content.empty?
        operation["requestBody"] = JSON::Any.new({
          "required" => JSON::Any.new(false),
          "content"  => JSON::Any.new(request_content),
        } of String => JSON::Any)
      end

      add_noir_callees_extension(operation, endpoint)
      add_noir_ai_context_extension(operation, endpoint)

      # Initialize path if not exists
      unless paths.has_key?(oas_path)
        paths[oas_path] = {} of String => JSON::Any
      end

      # Add method to path
      methods = operation_methods(endpoint.method)
      if methods.empty?
        add_unsupported_method_extension(paths[oas_path], endpoint.method)
      else
        methods.each do |method|
          add_operation(paths[oas_path], method, operation)
        end
      end
    end

    oas3_hash = {
      "openapi" => JSON::Any.new("3.0.3"),
      "info"    => JSON::Any.new({
        "title"   => JSON::Any.new("Generated by Noir"),
        "version" => JSON::Any.new("1.0.0"),
      } of String => JSON::Any),
      "servers" => JSON::Any.new([
        JSON::Any.new({
          "url" => JSON::Any.new(@options["url"].to_s.empty? ? "http://localhost" : @options["url"].to_s),
        } of String => JSON::Any),
      ]),
      "paths" => JSON::Any.new(paths.transform_values { |v| JSON::Any.new(v) }),
    } of String => JSON::Any

    ob_puts JSON::Any.new(oas3_hash).to_pretty_json
  end
end
