// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.3
// source: todo/v1/todo.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
)

var _ = new(context.Context)

const _ = http.SupportPackageIsVersion1

const OperationTodoServiceCreateTodo = "/todo.v1.TodoService/CreateTodo"
const OperationTodoServiceDeleteTodo = "/todo.v1.TodoService/DeleteTodo"
const OperationTodoServiceGetTodo = "/todo.v1.TodoService/GetTodo"
const OperationTodoServiceUpdateTodo = "/todo.v1.TodoService/UpdateTodo"

type TodoServiceHTTPServer interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*Todo, error)
	DeleteTodo(context.Context, *DeleteTodoRequest) (*Todo, error)
	GetTodo(context.Context, *GetTodoRequest) (*Todo, error)
	UpdateTodo(context.Context, *UpdateTodoRequest) (*Todo, error)
}

func RegisterTodoServiceHTTPServer(s *http.Server, srv TodoServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/todos/create", _TodoService_CreateTodo0_HTTP_Handler(srv))
	r.GET("/v1/todos/{id}", _TodoService_GetTodo0_HTTP_Handler(srv))
	r.PUT("/v1/todos/update", _TodoService_UpdateTodo0_HTTP_Handler(srv))
	r.DELETE("/v1/todos/{id}", _TodoService_DeleteTodo0_HTTP_Handler(srv))
}

func _TodoService_CreateTodo0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTodoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceCreateTodo)
		out, err := srv.CreateTodo(ctx, &in)
		if err != nil {
			return err
		}
		return ctx.Result(200, out)
	}
}

func _TodoService_GetTodo0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTodoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceGetTodo)
		out, err := srv.GetTodo(ctx, &in)
		if err != nil {
			return err
		}
		return ctx.Result(200, out)
	}
}

func _TodoService_UpdateTodo0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTodoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceUpdateTodo)
		out, err := srv.UpdateTodo(ctx, &in)
		if err != nil {
			return err
		}
		return ctx.Result(200, out)
	}
}

func _TodoService_DeleteTodo0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTodoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceDeleteTodo)
		out, err := srv.DeleteTodo(ctx, &in)
		if err != nil {
			return err
		}
		return ctx.Result(200, out)
	}
}
