require "../../spec_helper"
require "../../../src/output_builder/oas2"
require "../../../src/models/endpoint"
require "../../../src/utils/utils"
require "json"

describe "OutputBuilderOas2" do
  it "print endpoints as OpenAPI 2.0 (Swagger) specification" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
    }
    builder = OutputBuilderOas2.new(options)
    builder.set_io IO::Memory.new

    # Create endpoints with various HTTP methods and parameters
    endpoint1 = Endpoint.new("/pets/{petId}", "GET")
    endpoint1.push_param(Param.new("petId", "123", "path"))
    endpoint1.push_param(Param.new("api_key", "key123", "header"))

    endpoint2 = Endpoint.new("/pets", "POST")
    endpoint2.push_param(Param.new("name", "Fluffy", "json"))
    endpoint2.push_param(Param.new("type", "cat", "json"))
    endpoint2.push_param(Param.new("content-type", "application/json", "header"))

    endpoint3 = Endpoint.new("/pets/{petId}/photos", "POST")
    endpoint3.push_param(Param.new("petId", "123", "path"))
    endpoint3.push_param(Param.new("file", "photo.jpg", "form"))
    endpoint3.push_param(Param.new("description", "Pet photo", "form"))

    endpoints = [endpoint1, endpoint2, endpoint3]
    builder.print(endpoints)
    output = builder.io.to_s

    # Verify output is valid Swagger/OpenAPI 2.0 spec
    spec = JSON.parse(output)

    # Check Swagger version
    spec["swagger"].as_s.should eq("2.0")
    
    # Check info section
    spec["info"]["title"].as_s.should eq("Generated by Noir")
    spec["info"]["version"].as_s.should eq("1.0.0")
    
    # Check required OAS2 fields
    spec["basePath"].as_s.should eq("")
    spec["schemes"].as_a.size.should eq(2)
    spec["produces"].as_a.size.should eq(1)

    # Check paths exist and have correct structure
    paths = spec["paths"]
    paths.as_h.size.should eq(3)
    
    # Verify path parameter format (should be {petId} not :petId)
    paths.as_h.has_key?("/pets/{petId}").should be_true
    
    # Check GET endpoint with path and header parameters
    get_op = paths["/pets/{petId}"]["get"]
    get_params = get_op["parameters"].as_a
    get_params.size.should eq(2)
    
    # Verify path parameter has required properties
    path_param = get_params.find { |p| p["in"].as_s == "path" }
    path_param.should_not be_nil
    if path_param
      path_param["name"].as_s.should eq("petId")
      path_param["type"].as_s.should eq("string")
      path_param["required"].as_bool.should be_true
    end
    
    # Verify header parameter
    header_param = get_params.find { |p| p["in"].as_s == "header" }
    header_param.should_not be_nil
    if header_param
      header_param["name"].as_s.should eq("api_key")
      header_param["type"].as_s.should eq("string")
    end
    
    # Check POST endpoint with JSON body
    post_json_op = paths["/pets"]["post"]
    post_json_params = post_json_op["parameters"].as_a
    # Should have header param + body param
    post_json_params.size.should be >= 1
    
    # Should have body parameter for JSON content
    body_param = post_json_params.find { |p| p["in"].as_s == "body" }
    body_param.should_not be_nil
    if body_param
      body_param["schema"]["type"].as_s.should eq("object")
    end
    
    # Should have consumes field for JSON
    post_json_op.as_h.has_key?("consumes").should be_true
    post_json_op["consumes"].as_a.should contain(JSON::Any.new("application/json"))
    
    # Check POST endpoint with form data
    post_form_op = paths["/pets/{petId}/photos"]["post"]
    post_form_params = post_form_op["parameters"].as_a
    # Should have path param + form params
    post_form_params.size.should be >= 2
    
    # Verify formData parameters
    form_params = post_form_params.select { |p| p["in"].as_s == "formData" }
    form_params.size.should eq(2)
    
    # Should have consumes field for form data
    post_form_op.as_h.has_key?("consumes").should be_true
    post_form_op["consumes"].as_a.should contain(JSON::Any.new("application/x-www-form-urlencoded"))
  end
end
