require "../../spec_helper"
require "../../../src/output_builder/oas2"
require "../../../src/models/endpoint"
require "../../../src/utils/utils"
require "json"

describe "OutputBuilderOas2" do
  it "print endpoints as OpenAPI 2.0 (Swagger) specification" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
    }
    builder = OutputBuilderOas2.new(options)
    builder.io = IO::Memory.new

    # Create endpoints with various HTTP methods and parameters
    endpoint1 = Endpoint.new("/pets/{petId}", "GET")
    endpoint1.push_param(Param.new("petId", "123", "path"))
    endpoint1.push_param(Param.new("api_key", "key123", "header"))
    endpoint1.push_callee(Callee.new("PetService.find", "app/controllers/pets.cr", 12))
    endpoint1.push_callee(Callee.new("AuditLog.record", line: 13))

    endpoint2 = Endpoint.new("/pets", "POST")
    endpoint2.push_param(Param.new("name", "Fluffy", "json"))
    endpoint2.push_param(Param.new("type", "cat", "json"))
    endpoint2.push_param(Param.new("content-type", "application/json", "header"))

    endpoint3 = Endpoint.new("/pets/{petId}/photos", "POST")
    endpoint3.push_param(Param.new("petId", "123", "path"))
    endpoint3.push_param(Param.new("file", "photo.jpg", "form"))
    endpoint3.push_param(Param.new("description", "Pet photo", "form"))

    endpoints = [endpoint1, endpoint2, endpoint3]
    builder.print(endpoints)
    output = builder.io.to_s

    # Verify output is valid Swagger/OpenAPI 2.0 spec
    spec = JSON.parse(output)

    # Check Swagger version
    spec["swagger"].as_s.should eq("2.0")

    # Check info section
    spec["info"]["title"].as_s.should eq("Generated by Noir")
    spec["info"]["version"].as_s.should eq("1.0.0")

    # Check required OAS2 fields
    spec["basePath"].as_s.should eq("/")
    spec["schemes"].as_a.size.should eq(2)
    spec["produces"].as_a.size.should eq(1)

    # Check paths exist and have correct structure
    paths = spec["paths"]
    paths.as_h.size.should eq(3)

    # Verify path parameter format (should be {petId} not :petId)
    paths.as_h.has_key?("/pets/{petId}").should be_true

    # Check GET endpoint with path and header parameters
    get_op = paths["/pets/{petId}"]["get"]
    get_params = get_op["parameters"].as_a
    get_params.size.should eq(2)

    # Verify path parameter has required properties
    path_param = get_params.find { |p| p["in"].as_s == "path" }
    path_param = path_param.should_not be_nil
    path_param["name"].as_s.should eq("petId")
    path_param["type"].as_s.should eq("string")
    path_param["required"].as_bool.should be_true

    # Verify header parameter
    header_param = get_params.find { |p| p["in"].as_s == "header" }
    header_param = header_param.should_not be_nil
    header_param["name"].as_s.should eq("api_key")
    header_param["type"].as_s.should eq("string")

    # Check Noir callee extension
    callees = get_op["x-noir-callees"].as_a
    callees.size.should eq(2)
    callees[0]["name"].as_s.should eq("PetService.find")
    callees[0]["path"].as_s.should eq("app/controllers/pets.cr")
    callees[0]["line"].as_i.should eq(12)
    callees[1]["name"].as_s.should eq("AuditLog.record")
    callees[1].as_h.has_key?("path").should be_false
    callees[1]["line"].as_i.should eq(13)

    # Check POST endpoint with JSON body
    post_json_op = paths["/pets"]["post"]
    post_json_params = post_json_op["parameters"].as_a
    # Should have header param + body param
    post_json_params.size.should be >= 1

    # Should have body parameter for JSON content
    body_param = post_json_params.find { |p| p["in"].as_s == "body" }
    body_param = body_param.should_not be_nil
    body_param["schema"]["type"].as_s.should eq("object")

    # Should have consumes field for JSON
    post_json_op.as_h.has_key?("consumes").should be_true
    post_json_op["consumes"].as_a.should contain(JSON::Any.new("application/json"))

    # Check POST endpoint with form data
    post_form_op = paths["/pets/{petId}/photos"]["post"]
    post_form_params = post_form_op["parameters"].as_a
    # Should have path param + form params
    post_form_params.size.should be >= 2

    # Verify formData parameters
    form_params = post_form_params.select { |p| p["in"].as_s == "formData" }
    form_params.size.should eq(2)

    # Should have consumes field for form data
    post_form_op.as_h.has_key?("consumes").should be_true
    post_form_op["consumes"].as_a.should contain(JSON::Any.new("application/x-www-form-urlencoded"))
  end

  it "normalizes Swagger path, method, and host edge cases" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new("https://api.example.com/v1"),
    }
    builder = OutputBuilderOas2.new(options)
    builder.io = IO::Memory.new

    typed_path = Endpoint.new("/users/<int:user_id>", "ANY")
    typed_path.push_param(Param.new("q", "", "query"))

    mixed_body = Endpoint.new("/mixed", "POST")
    mixed_body.push_param(Param.new("name", "", "json"))
    mixed_body.push_param(Param.new("avatar", "", "form"))

    unsupported = Endpoint.new("/jobs", "SUBSCRIBE")

    builder.print([typed_path, mixed_body, unsupported])
    spec = JSON.parse(builder.io.to_s)
    paths = spec["paths"]

    spec["host"].as_s.should eq("api.example.com")
    # `-u`'s path is already prefixed onto every route by the optimizer, so
    # repeating it here made every operation resolve to `/v1/v1/...`.
    spec["basePath"].as_s.should eq("/")
    spec["schemes"].as_a.should eq([JSON::Any.new("https")])

    paths.as_h.has_key?("/users/{user_id}").should be_true
    paths["/users/{user_id}"].as_h.has_key?("any").should be_false
    %w[get post put patch delete options head].each do |method|
      paths["/users/{user_id}"].as_h.has_key?(method).should be_true
    end
    # `trace` is an OpenAPI 3.0 addition; Swagger 2.0's Path Item Object has
    # no such field and rejects the whole document over it.
    paths["/users/{user_id}"].as_h.has_key?("trace").should be_false

    get_params = paths["/users/{user_id}"]["get"]["parameters"].as_a
    get_params.any? { |p| p["in"].as_s == "path" && p["name"].as_s == "user_id" }.should be_true

    mixed_params = paths["/mixed"]["post"]["parameters"].as_a
    mixed_params.any? { |p| p["in"].as_s == "formData" && p["name"].as_s == "avatar" }.should be_true
    mixed_params.any? { |p| p["in"].as_s == "body" }.should be_false
    paths["/mixed"]["post"]["consumes"].as_a.should eq([JSON::Any.new("application/x-www-form-urlencoded")])

    paths["/jobs"].as_h.has_key?("subscribe").should be_false
    paths["/jobs"]["x-noir-unsupported-methods"].as_a.should contain(JSON::Any.new("SUBSCRIBE"))
  end

  it "keeps every operation's parameter list valid" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas2.new(options)
    builder.io = IO::Memory.new

    # A header param already named `Cookie` and a cookie param both claim the
    # `{in: header, name: Cookie}` slot, which Swagger 2.0 requires to be
    # unique.
    cookies = Endpoint.new("/login", "POST")
    cookies.push_param(Param.new("Cookie", "", "header"))
    cookies.push_param(Param.new("session", "", "cookie"))

    # `id` is both the path template variable and a query param.
    shadowed = Endpoint.new("/users/:id", "GET")
    shadowed.push_param(Param.new("id", "", "query"))

    # A path param the emitted path can't express: `in: path` without a
    # matching template expression is invalid in both OAS versions.
    concrete = Endpoint.new("/posts/1", "DELETE")
    concrete.push_param(Param.new("id", "", "path"))

    builder.print([cookies, shadowed, concrete])
    paths = JSON.parse(builder.io.to_s)["paths"]

    login_params = paths["/login"]["post"]["parameters"].as_a
    login_params.count { |p| p["in"].as_s == "header" && p["name"].as_s.downcase == "cookie" }.should eq(1)
    login_params.find! { |p| p["name"].as_s == "Cookie" }["description"].as_s.should contain("session")

    user_params = paths["/users/{id}"]["get"]["parameters"].as_a
    user_params.map { |p| {p["in"].as_s, p["name"].as_s} }.should eq([{"path", "id"}])

    delete_op = paths["/posts/1"]["delete"]
    delete_op["parameters"].as_a.any? { |p| p["in"].as_s == "path" }.should be_false
    delete_op["x-noir-unmapped-path-params"].as_a.should eq([JSON::Any.new("id")])
  end

  it "degrades a QUERY endpoint to x-noir-unsupported-methods, not to get" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
    }
    builder = OutputBuilderOas2.new(options)
    builder.io = IO::Memory.new

    endpoint = Endpoint.new("/products/search", "QUERY")
    endpoint.push_param(Param.new("q", "widget", "form"))

    builder.print([endpoint])
    path_item = JSON.parse(builder.io.to_s)["paths"]["/products/search"]

    # Swagger 2.0 has no `query` operation key; the verb must survive in the
    # extension instead of being dropped or rewritten to another method.
    path_item["x-noir-unsupported-methods"].as_a.should eq([JSON::Any.new("QUERY")])
    path_item.as_h.keys.should_not contain("query")
    path_item.as_h.keys.should_not contain("get")

    # The verb name alone is not the endpoint. Everything the operation had
    # to say — its form fields here — survives in the operation extension.
    unsupported = path_item["x-noir-unsupported-operations"]["QUERY"]
    unsupported["parameters"].as_a.map { |p| {p["in"].as_s, p["name"].as_s} }
      .should eq([{"formData", "q"}])
    unsupported["consumes"].as_a.should eq([JSON::Any.new("application/x-www-form-urlencoded")])
  end

  it "keeps the base path out of basePath and the port in host" do
    # `-u` is prepended to every endpoint URL by the optimizer, so the route
    # already carries the base path. Declaring it as `basePath` too resolved
    # every operation to `<base><base><path>`, which `-f curl` — the oracle,
    # same run, same endpoint — never did.
    cases = [
      {"", nil},
      {"https://h", "h"},
      {"https://h/v2", "h"},
      {"https://h:8443/v2", "h:8443"},
      {"https://h:8443/v2/nested/deeper", "h:8443"},
    ] of Tuple(String, String?)

    cases.each do |(target, host)|
      options = {
        "debug"   => YAML::Any.new(false),
        "verbose" => YAML::Any.new(false),
        "color"   => YAML::Any.new(false),
        "nolog"   => YAML::Any.new(false),
        "output"  => YAML::Any.new(""),
        "url"     => YAML::Any.new(target),
      }
      builder = OutputBuilderOas2.new(options)
      builder.io = IO::Memory.new

      # What the optimizer hands the builder once `-u` is applied.
      prefix = target.empty? ? "" : target
      builder.print([Endpoint.new("#{prefix}/users", "GET")])
      spec = JSON.parse(builder.io.to_s)

      spec["basePath"].as_s.should eq("/")
      if host
        spec["host"].as_s.should eq(host)
      else
        spec.as_h.has_key?("host").should be_false
      end
      # The path key keeps the base path, so host + basePath + key is the URL
      # `-f curl` prints for the same endpoint.
      spec["paths"].as_h.keys.should eq([target.empty? ? "/users" : "#{URI.parse(target).path}/users"])
    end
  end

  it "merges two routes that differ only in placeholder name" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas2.new(options)
    builder.io = IO::Memory.new

    show = Endpoint.new("/users/:id", "GET")
    show.push_param(Param.new("id", "", "path"))
    show.push_param(Param.new("fields", "", "query"))

    destroy = Endpoint.new("/users/:userId", "DELETE")
    destroy.push_param(Param.new("userId", "", "path"))

    # Same method on the same shape is a real conflict: merge, don't drop.
    alternate = Endpoint.new("/users/:userId", "GET")
    alternate.push_param(Param.new("userId", "", "path"))
    alternate.push_param(Param.new("expand", "", "query"))

    builder.print([show, destroy, alternate])
    paths = JSON.parse(builder.io.to_s)["paths"]

    paths.as_h.keys.should eq(["/users/{id}"])
    paths["/users/{id}"]["x-noir-path-variants"].as_a
      .should eq([JSON::Any.new("/users/{userId}")])

    get_params = paths["/users/{id}"]["get"]["parameters"].as_a
      .map { |p| {p["in"].as_s, p["name"].as_s} }
    get_params.should contain({"path", "id"})
    get_params.should contain({"query", "fields"})
    get_params.should contain({"query", "expand"})
    get_params.count { |location, _| location == "path" }.should eq(1)

    delete_params = paths["/users/{id}"]["delete"]["parameters"].as_a
    delete_params.map { |p| {p["in"].as_s, p["name"].as_s} }.should eq([{"path", "id"}])
  end

  it "unions the body fields of operations merged onto one path and method" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas2.new(options)
    builder.io = IO::Memory.new

    # Noir addresses many GraphQL resolvers on one path with a `#fragment`;
    # they collapse onto one `POST /graphql`, and keeping only the first
    # schema dropped every later resolver's input fields.
    query = Endpoint.new("/graphql#Query.user", "POST")
    query.push_param(Param.new("id", "", "json"))

    mutation = Endpoint.new("/graphql#Mutation.createUser", "POST")
    mutation.push_param(Param.new("name", "", "json"))
    mutation.push_param(Param.new("email", "", "json"))

    builder.print([query, mutation])
    operation = JSON.parse(builder.io.to_s)["paths"]["/graphql"]["post"]

    body = operation["parameters"].as_a.find! { |p| p["in"].as_s == "body" }
    body["schema"]["properties"].as_h.keys.sort!.should eq(["email", "id", "name"])
    operation["x-noir-operations"].as_a
      .should eq([JSON::Any.new("Query.user"), JSON::Any.new("Mutation.createUser")])
  end
end
