require "../../spec_helper"
require "../../../src/output_builder/oas2"
require "../../../src/models/endpoint"
require "../../../src/utils/utils"
require "json"

describe "OutputBuilderOas2" do
  it "print endpoints as OpenAPI 2.0 (Swagger) specification" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
    }
    builder = OutputBuilderOas2.new(options)
    builder.io = IO::Memory.new

    # Create endpoints with various HTTP methods and parameters
    endpoint1 = Endpoint.new("/pets/{petId}", "GET")
    endpoint1.push_param(Param.new("petId", "123", "path"))
    endpoint1.push_param(Param.new("api_key", "key123", "header"))
    endpoint1.push_callee(Callee.new("PetService.find", "app/controllers/pets.cr", 12))
    endpoint1.push_callee(Callee.new("AuditLog.record", line: 13))

    endpoint2 = Endpoint.new("/pets", "POST")
    endpoint2.push_param(Param.new("name", "Fluffy", "json"))
    endpoint2.push_param(Param.new("type", "cat", "json"))
    endpoint2.push_param(Param.new("content-type", "application/json", "header"))

    endpoint3 = Endpoint.new("/pets/{petId}/photos", "POST")
    endpoint3.push_param(Param.new("petId", "123", "path"))
    endpoint3.push_param(Param.new("file", "photo.jpg", "form"))
    endpoint3.push_param(Param.new("description", "Pet photo", "form"))

    endpoints = [endpoint1, endpoint2, endpoint3]
    builder.print(endpoints)
    output = builder.io.to_s

    # Verify output is valid Swagger/OpenAPI 2.0 spec
    spec = JSON.parse(output)

    # Check Swagger version
    spec["swagger"].as_s.should eq("2.0")

    # Check info section
    spec["info"]["title"].as_s.should eq("Generated by Noir")
    spec["info"]["version"].as_s.should eq("1.0.0")

    # Check required OAS2 fields
    spec["basePath"].as_s.should eq("/")
    spec["schemes"].as_a.size.should eq(2)
    spec["produces"].as_a.size.should eq(1)

    # Check paths exist and have correct structure
    paths = spec["paths"]
    paths.as_h.size.should eq(3)

    # Verify path parameter format (should be {petId} not :petId)
    paths.as_h.has_key?("/pets/{petId}").should be_true

    # Check GET endpoint with path and header parameters
    get_op = paths["/pets/{petId}"]["get"]
    get_params = get_op["parameters"].as_a
    get_params.size.should eq(2)

    # Verify path parameter has required properties
    path_param = get_params.find { |p| p["in"].as_s == "path" }
    path_param = path_param.should_not be_nil
    path_param["name"].as_s.should eq("petId")
    path_param["type"].as_s.should eq("string")
    path_param["required"].as_bool.should be_true

    # Verify header parameter
    header_param = get_params.find { |p| p["in"].as_s == "header" }
    header_param = header_param.should_not be_nil
    header_param["name"].as_s.should eq("api_key")
    header_param["type"].as_s.should eq("string")

    # Check Noir callee extension
    callees = get_op["x-noir-callees"].as_a
    callees.size.should eq(2)
    callees[0]["name"].as_s.should eq("PetService.find")
    callees[0]["path"].as_s.should eq("app/controllers/pets.cr")
    callees[0]["line"].as_i.should eq(12)
    callees[1]["name"].as_s.should eq("AuditLog.record")
    callees[1].as_h.has_key?("path").should be_false
    callees[1]["line"].as_i.should eq(13)

    # Check POST endpoint with JSON body
    post_json_op = paths["/pets"]["post"]
    post_json_params = post_json_op["parameters"].as_a
    # Should have header param + body param
    post_json_params.size.should be >= 1

    # Should have body parameter for JSON content
    body_param = post_json_params.find { |p| p["in"].as_s == "body" }
    body_param = body_param.should_not be_nil
    body_param["schema"]["type"].as_s.should eq("object")

    # Should have consumes field for JSON
    post_json_op.as_h.has_key?("consumes").should be_true
    post_json_op["consumes"].as_a.should contain(JSON::Any.new("application/json"))

    # Check POST endpoint with form data
    post_form_op = paths["/pets/{petId}/photos"]["post"]
    post_form_params = post_form_op["parameters"].as_a
    # Should have path param + form params
    post_form_params.size.should be >= 2

    # Verify formData parameters
    form_params = post_form_params.select { |p| p["in"].as_s == "formData" }
    form_params.size.should eq(2)

    # Should have consumes field for form data
    post_form_op.as_h.has_key?("consumes").should be_true
    post_form_op["consumes"].as_a.should contain(JSON::Any.new("application/x-www-form-urlencoded"))
  end

  it "normalizes Swagger path, method, and host edge cases" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new("https://api.example.com/v1"),
    }
    builder = OutputBuilderOas2.new(options)
    builder.io = IO::Memory.new

    typed_path = Endpoint.new("/users/<int:user_id>", "ANY")
    typed_path.push_param(Param.new("q", "", "query"))

    mixed_body = Endpoint.new("/mixed", "POST")
    mixed_body.push_param(Param.new("name", "", "json"))
    mixed_body.push_param(Param.new("avatar", "", "form"))

    unsupported = Endpoint.new("/jobs", "SUBSCRIBE")

    builder.print([typed_path, mixed_body, unsupported])
    spec = JSON.parse(builder.io.to_s)
    paths = spec["paths"]

    spec["host"].as_s.should eq("api.example.com")
    spec["basePath"].as_s.should eq("/v1")
    spec["schemes"].as_a.should eq([JSON::Any.new("https")])

    paths.as_h.has_key?("/users/{user_id}").should be_true
    paths["/users/{user_id}"].as_h.has_key?("any").should be_false
    %w[get post put patch delete options head trace].each do |method|
      paths["/users/{user_id}"].as_h.has_key?(method).should be_true
    end

    get_params = paths["/users/{user_id}"]["get"]["parameters"].as_a
    get_params.any? { |p| p["in"].as_s == "path" && p["name"].as_s == "user_id" }.should be_true

    mixed_params = paths["/mixed"]["post"]["parameters"].as_a
    mixed_params.any? { |p| p["in"].as_s == "formData" && p["name"].as_s == "avatar" }.should be_true
    mixed_params.any? { |p| p["in"].as_s == "body" }.should be_false
    paths["/mixed"]["post"]["consumes"].as_a.should eq([JSON::Any.new("application/x-www-form-urlencoded")])

    paths["/jobs"].as_h.has_key?("subscribe").should be_false
    paths["/jobs"]["x-noir-unsupported-methods"].as_a.should contain(JSON::Any.new("SUBSCRIBE"))
  end
end
