require "../../spec_helper"
require "../../../src/output_builder/oas3"
require "../../../src/models/endpoint"
require "../../../src/utils/utils"
require "json"

describe "OutputBuilderOas3" do
  it "print endpoints as OpenAPI 3.0 specification" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas3.new(options)
    builder.io = IO::Memory.new

    # Create endpoints with various HTTP methods and parameters
    endpoint1 = Endpoint.new("/pets/{petId}", "GET")
    endpoint1.push_param(Param.new("petId", "123", "path"))
    endpoint1.push_param(Param.new("api_key", "key123", "header"))
    endpoint1.push_callee(Callee.new("PetService.find", "app/controllers/pets.cr", 12))
    endpoint1.push_callee(Callee.new("AuditLog.record", line: 13))
    context = AIContext.new
    context.push_guard(AIContextEntry.new("auth", "auth", source: "express_auth", description: "Protected by Express requireAuth middleware"))
    endpoint1.ai_context = context

    endpoint2 = Endpoint.new("/pets", "POST")
    endpoint2.push_param(Param.new("name", "Fluffy", "json"))
    endpoint2.push_param(Param.new("type", "cat", "json"))
    endpoint2.push_param(Param.new("content-type", "application/json", "header"))

    endpoint3 = Endpoint.new("/pets/{petId}/photos", "POST")
    endpoint3.push_param(Param.new("petId", "123", "path"))
    endpoint3.push_param(Param.new("file", "photo.jpg", "form"))
    endpoint3.push_param(Param.new("description", "Pet photo", "form"))
    endpoint3.push_param(Param.new("session", "abc123", "cookie"))

    endpoints = [endpoint1, endpoint2, endpoint3]
    builder.print(endpoints)
    output = builder.io.to_s

    # Verify output is valid OpenAPI 3.0 spec
    spec = JSON.parse(output)

    # Check OpenAPI version
    spec["openapi"].as_s.should eq("3.0.3")

    # Check info section
    spec["info"]["title"].as_s.should eq("Generated by Noir")
    spec["info"]["version"].as_s.should eq("1.0.0")

    # Check servers section
    spec["servers"].as_a.size.should eq(1)
    spec["servers"][0]["url"].as_s.should eq("http://localhost")

    # Check paths exist and have correct structure
    paths = spec["paths"]
    paths.as_h.size.should eq(3)

    # Verify path parameter format (should be {petId} not :petId)
    paths.as_h.has_key?("/pets/{petId}").should be_true

    # Check GET endpoint with path and header parameters
    get_op = paths["/pets/{petId}"]["get"]
    get_params = get_op["parameters"].as_a
    get_params.size.should eq(2)

    # Verify path parameter has required properties with schema
    path_param = get_params.find { |p| p["in"].as_s == "path" }
    path_param = path_param.should_not be_nil
    path_param["name"].as_s.should eq("petId")
    path_param["required"].as_bool.should be_true
    path_param["schema"]["type"].as_s.should eq("string")

    # Verify header parameter has schema
    header_param = get_params.find { |p| p["in"].as_s == "header" }
    header_param = header_param.should_not be_nil
    header_param["name"].as_s.should eq("api_key")
    header_param["schema"]["type"].as_s.should eq("string")

    # Check response has content
    get_response = get_op["responses"]["200"]
    get_response["description"].as_s.should eq("Successful response")
    get_response["content"]["application/json"]["schema"]["type"].as_s.should eq("object")

    # Check Noir callee extension
    callees = get_op["x-noir-callees"].as_a
    callees.size.should eq(2)
    callees[0]["name"].as_s.should eq("PetService.find")
    callees[0]["path"].as_s.should eq("app/controllers/pets.cr")
    callees[0]["line"].as_i.should eq(12)
    callees[1]["name"].as_s.should eq("AuditLog.record")
    callees[1].as_h.has_key?("path").should be_false
    callees[1]["line"].as_i.should eq(13)
    get_op["x-noir-ai-context"]["guards"].as_a.size.should eq(1)
    get_op["x-noir-ai-context"]["guards"][0]["source"].as_s.should eq("express_auth")

    # Check POST endpoint with JSON body
    post_json_op = paths["/pets"]["post"]
    post_json_params = post_json_op["parameters"].as_a
    # Should have header param (JSON params go to requestBody)
    post_json_params.size.should eq(1)

    # Should have requestBody for JSON content
    post_json_op.as_h.has_key?("requestBody").should be_true
    request_body = post_json_op["requestBody"]
    request_body["content"]["application/json"]["schema"]["type"].as_s.should eq("object")
    request_body["content"]["application/json"]["schema"]["properties"].as_h.size.should eq(2)

    # Check POST endpoint with form data
    post_form_op = paths["/pets/{petId}/photos"]["post"]
    post_form_params = post_form_op["parameters"].as_a
    # Should have path param + cookie param
    post_form_params.size.should eq(2)

    # Verify cookie parameter (OAS3 supports cookies)
    cookie_param = post_form_params.find { |p| p["in"].as_s == "cookie" }
    cookie_param = cookie_param.should_not be_nil
    cookie_param["name"].as_s.should eq("session")
    cookie_param["schema"]["type"].as_s.should eq("string")

    # Should have requestBody for form data
    post_form_op.as_h.has_key?("requestBody").should be_true
    form_body = post_form_op["requestBody"]
    form_body["content"]["application/x-www-form-urlencoded"]["schema"]["type"].as_s.should eq("object")
    form_body["content"]["application/x-www-form-urlencoded"]["schema"]["properties"].as_h.size.should eq(2)
  end

  it "normalizes OpenAPI path and method edge cases" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new("https://api.example.com"),
    }
    builder = OutputBuilderOas3.new(options)
    builder.io = IO::Memory.new

    typed_path = Endpoint.new("/users/<int:user_id>", "ANY")
    typed_path.push_param(Param.new("q", "", "query"))

    optional_path = Endpoint.new("/accounts/:id{/:section}", "GET")
    optional_path.push_param(Param.new("id", "", "path"))
    optional_path.push_param(Param.new("section", "", "path"))
    optional_path.push_param(Param.new("section", "", "path"))

    mixed_body = Endpoint.new("/mixed", "POST")
    mixed_body.push_param(Param.new("name", "", "json"))
    mixed_body.push_param(Param.new("avatar", "", "form"))

    unsupported = Endpoint.new("/jobs", "SUBSCRIBE")

    builder.print([typed_path, optional_path, mixed_body, unsupported])
    spec = JSON.parse(builder.io.to_s)
    paths = spec["paths"]

    paths.as_h.has_key?("/users/{user_id}").should be_true
    paths["/users/{user_id}"].as_h.has_key?("any").should be_false
    %w[get post put patch delete options head trace].each do |method|
      paths["/users/{user_id}"].as_h.has_key?(method).should be_true
    end

    get_params = paths["/users/{user_id}"]["get"]["parameters"].as_a
    get_params.any? { |p| p["in"].as_s == "path" && p["name"].as_s == "user_id" }.should be_true

    paths.as_h.has_key?("/accounts/{id}/{section}").should be_true
    optional_params = paths["/accounts/{id}/{section}"]["get"]["parameters"].as_a
    optional_params.count { |p| p["in"].as_s == "path" && p["name"].as_s == "section" }.should eq(1)

    content = paths["/mixed"]["post"]["requestBody"]["content"].as_h
    content.has_key?("application/json").should be_true
    content.has_key?("application/x-www-form-urlencoded").should be_true

    paths["/jobs"].as_h.has_key?("subscribe").should be_false
    paths["/jobs"]["x-noir-unsupported-methods"].as_a.should contain(JSON::Any.new("SUBSCRIBE"))
  end

  it "moves path parameters with no template expression into an extension" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas3.new(options)
    builder.io = IO::Memory.new

    # The optimizer substituted a concrete value for the placeholder, so `id`
    # has nowhere to bind — `in: path` here fails every OAS validator.
    concrete = Endpoint.new("/posts/1", "GET")
    concrete.push_param(Param.new("id", "", "path"))
    concrete.push_param(Param.new("draft", "", "query"))

    # Sanic-style `<name:type>`, resolved by the endpoint's own path param.
    typed = Endpoint.new("/reports/<report_id:int>", "GET")
    typed.push_param(Param.new("report_id", "", "path"))

    builder.print([concrete, typed])
    paths = JSON.parse(builder.io.to_s)["paths"]

    operation = paths["/posts/1"]["get"]
    operation["parameters"].as_a.map { |p| {p["in"].as_s, p["name"].as_s} }.should eq([{"query", "draft"}])
    operation["x-noir-unmapped-path-params"].as_a.should eq([JSON::Any.new("id")])

    paths.as_h.has_key?("/reports/{report_id}").should be_true
    typed_params = paths["/reports/{report_id}"]["get"]["parameters"].as_a
    typed_params.map { |p| {p["in"].as_s, p["name"].as_s} }.should eq([{"path", "report_id"}])
  end

  it "emits a QUERY endpoint as a real `query` operation on an OpenAPI 3.2 document" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas3.new(options)
    builder.io = IO::Memory.new

    get_endpoint = Endpoint.new("/pets", "GET")

    query_endpoint = Endpoint.new("/products/search", "QUERY")
    query_endpoint.push_param(Param.new("q", "widget", "form"))

    builder.print([get_endpoint, query_endpoint])
    spec = JSON.parse(builder.io.to_s)

    # OpenAPI 3.2 added `query` to the Path Item Object, so the verb keeps
    # its own operation key instead of degrading to the unsupported-methods
    # extension. A single `query` operation anywhere in the document forces
    # the whole document onto 3.2 — a "get"+"query" mix under a declared
    # 3.0.3 would be invalid, since 3.0.3 has no `query` key at all.
    spec["openapi"].as_s.should eq("3.2.0")

    paths = spec["paths"]
    paths["/pets"].as_h.keys.should contain("get")

    query_path_item = paths["/products/search"]
    query_path_item.as_h.keys.should_not contain("x-noir-unsupported-methods")
    query_path_item.as_h.keys.should_not contain("get")

    query_operation = query_path_item["query"]
    query_operation["requestBody"]["content"]["application/x-www-form-urlencoded"]["schema"]["properties"].as_h.keys.should eq(["q"])
  end

  it "keeps the base path out of the document server url" do
    # `-u` is prepended to every endpoint URL by the optimizer, so the route
    # already carries the base path. Declaring it in `servers[0].url` too
    # resolved every operation to `<base><base><path>`; `-f curl` — the same
    # run, the same endpoint — never did.
    cases = [
      {"", "http://localhost", "/users"},
      {"https://h", "https://h", "/users"},
      {"https://h/v2", "https://h", "/v2/users"},
      {"https://h:8443/v2", "https://h:8443", "/v2/users"},
    ]

    cases.each do |(target, server, path_key)|
      options = {
        "debug"   => YAML::Any.new(false),
        "verbose" => YAML::Any.new(false),
        "color"   => YAML::Any.new(false),
        "nolog"   => YAML::Any.new(false),
        "output"  => YAML::Any.new(""),
        "url"     => YAML::Any.new(target),
      }
      builder = OutputBuilderOas3.new(options)
      builder.io = IO::Memory.new

      # What the optimizer hands the builder once `-u` is applied.
      builder.print([Endpoint.new("#{target}/users", "GET")])
      spec = JSON.parse(builder.io.to_s)

      spec["servers"][0]["url"].as_s.should eq(server)
      spec["paths"].as_h.keys.should eq([path_key])

      # An absolute route also carries a per-operation `servers` override,
      # which is the authority alone — the document-level entry has to agree
      # with it or the two disagree about where the base path lives.
      operation_servers = spec["paths"][path_key]["get"].as_h["servers"]?
      operation_servers.try(&.[0]["url"].as_s).should eq(server) unless target.empty?
    end
  end

  it "merges two routes that differ only in placeholder name" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas3.new(options)
    builder.io = IO::Memory.new

    # Both OAS 2.0 and OAS 3.x say two templated paths with the same
    # hierarchy but different variable names are identical and MUST NOT both
    # appear, so `openapi-spec-validator` rejected the whole document.
    show = Endpoint.new("/users/:id", "GET")
    show.push_param(Param.new("id", "", "path"))
    show.push_param(Param.new("fields", "", "query"))

    destroy = Endpoint.new("/users/:userId", "DELETE")
    destroy.push_param(Param.new("userId", "", "path"))

    # Same method on the same shape is a real conflict: merge, don't drop.
    alternate = Endpoint.new("/users/:userId", "GET")
    alternate.push_param(Param.new("userId", "", "path"))
    alternate.push_param(Param.new("expand", "", "query"))

    builder.print([show, destroy, alternate])
    paths = JSON.parse(builder.io.to_s)["paths"]

    paths.as_h.keys.should eq(["/users/{id}"])
    paths["/users/{id}"]["x-noir-path-variants"].as_a
      .should eq([JSON::Any.new("/users/{userId}")])

    get_params = paths["/users/{id}"]["get"]["parameters"].as_a
      .map { |p| {p["in"].as_s, p["name"].as_s} }
    get_params.should contain({"path", "id"})
    get_params.should contain({"query", "fields"})
    get_params.should contain({"query", "expand"})
    get_params.count { |location, _| location == "path" }.should eq(1)

    delete_params = paths["/users/{id}"]["delete"]["parameters"].as_a
    delete_params.map { |p| {p["in"].as_s, p["name"].as_s} }.should eq([{"path", "id"}])
  end

  it "unions the request body of operations merged onto one path and method" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas3.new(options)
    builder.io = IO::Memory.new

    # Noir addresses many GraphQL resolvers on one path with a `#fragment`;
    # they collapse onto one `POST /graphql`, and keeping only the first
    # media-type entry dropped every later resolver's input fields.
    query = Endpoint.new("/graphql#Query.user", "POST")
    query.push_param(Param.new("id", "", "json"))

    mutation = Endpoint.new("/graphql#Mutation.createUser", "POST")
    mutation.push_param(Param.new("name", "", "json"))
    mutation.push_param(Param.new("email", "", "json"))

    upload = Endpoint.new("/graphql#Mutation.upload", "POST")
    upload.push_param(Param.new("file", "", "form"))

    builder.print([query, mutation, upload])
    operation = JSON.parse(builder.io.to_s)["paths"]["/graphql"]["post"]

    content = operation["requestBody"]["content"]
    content["application/json"]["schema"]["properties"].as_h.keys.sort!
      .should eq(["email", "id", "name"])
    content["application/x-www-form-urlencoded"]["schema"]["properties"].as_h.keys
      .should eq(["file"])
    operation["x-noir-operations"].as_a.map(&.as_s)
      .should eq(["Query.user", "Mutation.createUser", "Mutation.upload"])
  end

  it "keeps the operation of a verb the spec cannot express" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderOas3.new(options)
    builder.io = IO::Memory.new

    # AsyncAPI channels arrive as PUBLISH/SUBSCRIBE endpoints. Recording only
    # the verb threw the parameters, request body and callees away with it.
    publish = Endpoint.new("/user/signedup", "PUBLISH")
    publish.push_param(Param.new("userId", "", "json"))
    publish.push_param(Param.new("trace", "", "header"))
    publish.push_callee(Callee.new("SignupHandler.call", "app/handlers.rb", 7))

    subscribe = Endpoint.new("/user/signedup", "SUBSCRIBE")
    subscribe.push_param(Param.new("displayName", "", "json"))

    builder.print([publish, subscribe])
    path_item = JSON.parse(builder.io.to_s)["paths"]["/user/signedup"]

    path_item["x-noir-unsupported-methods"].as_a
      .should eq([JSON::Any.new("PUBLISH"), JSON::Any.new("SUBSCRIBE")])

    operations = path_item["x-noir-unsupported-operations"]
    operations["PUBLISH"]["requestBody"]["content"]["application/json"]["schema"]["properties"]
      .as_h.keys.should eq(["userId"])
    operations["PUBLISH"]["parameters"].as_a
      .map { |p| {p["in"].as_s, p["name"].as_s} }.should eq([{"header", "trace"}])
    operations["PUBLISH"]["x-noir-callees"][0]["name"].as_s.should eq("SignupHandler.call")

    # Each verb keeps its own operation rather than the last one winning.
    operations["SUBSCRIBE"]["requestBody"]["content"]["application/json"]["schema"]["properties"]
      .as_h.keys.should eq(["displayName"])
  end
end
