require "../../spec_helper"
require "../../../src/output_builder/postman"
require "../../../src/models/endpoint"
require "../../../src/utils/utils"
require "json"

describe "OutputBuilderPostman" do
  it "print endpoints as Postman collection" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    # Create endpoints with various HTTP methods and parameters
    endpoint1 = Endpoint.new("/pets/:petId", "GET")
    endpoint1.push_param(Param.new("petId", "123", "path"))
    endpoint1.push_param(Param.new("api_key", "key123", "header"))
    endpoint1.push_callee(Callee.new("PetService.find", "app/controllers/pets.cr", 12))
    endpoint1.push_callee(Callee.new("AuditLog.record", line: 13))
    context = AIContext.new
    context.push_guard(AIContextEntry.new("auth", "auth", source: "express_auth", description: "Protected by auth middleware"))
    # Carries a source *and* a location, so the description pins the field
    # order the plain-text report and Postman now share. With only one of
    # the two set (as the guard above has) any ordering looks the same.
    context.push_sink(AIContextEntry.new("sql", "run_query", source: "callee",
      path: "app/controllers/pets.cr", line: 12))
    endpoint1.ai_context = context

    endpoint2 = Endpoint.new("/pets", "POST")
    endpoint2.push_param(Param.new("name", "Fluffy", "json"))
    endpoint2.push_param(Param.new("type", "cat", "json"))

    endpoint3 = Endpoint.new("/pets/:petId/photos", "POST")
    endpoint3.push_param(Param.new("petId", "123", "path"))
    endpoint3.push_param(Param.new("file", "photo.jpg", "form"))
    endpoint3.push_param(Param.new("description", "Pet photo", "form"))
    endpoint3.push_param(Param.new("session", "abc123", "cookie"))

    endpoint4 = Endpoint.new("/search", "GET")
    endpoint4.push_param(Param.new("q", "test", "query"))
    endpoint4.push_param(Param.new("limit", "10", "query"))

    endpoints = [endpoint1, endpoint2, endpoint3, endpoint4]
    builder.print(endpoints)
    output = builder.io.to_s

    # Verify output is valid Postman collection
    collection = JSON.parse(output)

    # Check collection info
    collection["info"]["name"].as_s.should eq("Generated by Noir")
    collection["info"]["schema"].as_s.should eq("https://schema.getpostman.com/json/collection/v2.1.0/collection.json")

    # Check items exist
    items = collection["item"].as_a
    items.size.should eq(4)

    # Check first item (GET with path param and header)
    item1 = items[0]
    item1["name"].as_s.should eq("GET /pets/:petId")
    item1["request"]["method"].as_s.should eq("GET")
    item1["request"]["url"]["path"].as_a.map(&.as_s).should eq(["pets", ":petId"])
    item1["request"]["url"]["variable"].as_a.size.should eq(1)
    item1["request"]["url"]["variable"][0]["key"].as_s.should eq("petId")
    item1["request"]["header"].as_a.size.should eq(1)
    item1["request"]["header"][0]["key"].as_s.should eq("api_key")
    item1["description"].as_s.should contain("Noir AI context:")
    item1["description"].as_s.should contain("guards:")
    item1["description"].as_s.should contain("auth: auth [express_auth]")
    # `[source]` before the location, matching OutputBuilderCommon's
    # plain-text ai_context block — the two used to disagree.
    item1["description"].as_s.should contain("sql: run_query [callee] (app/controllers/pets.cr:12)")

    # Check second item (POST with JSON body)
    item2 = items[1]
    item2["name"].as_s.should eq("POST /pets")
    item2["request"]["method"].as_s.should eq("POST")
    item2["request"]["body"]["mode"].as_s.should eq("raw")
    item2["request"]["body"]["options"]["raw"]["language"].as_s.should eq("json")

    # Verify JSON body content
    body_raw = item2["request"]["body"]["raw"].as_s
    body_json = JSON.parse(body_raw)
    body_json["name"].as_s.should eq("Fluffy")
    body_json["type"].as_s.should eq("cat")

    # Check Content-Type header is added for JSON body
    headers = item2["request"]["header"].as_a
    content_type_header = headers.find { |h| h["key"].as_s == "Content-Type" }
    content_type_header = content_type_header.should_not be_nil
    content_type_header["value"].as_s.should eq("application/json")

    # Check third item (POST with form data and cookie)
    item3 = items[2]
    item3["name"].as_s.should eq("POST /pets/:petId/photos")
    item3["request"]["method"].as_s.should eq("POST")
    item3["request"]["body"]["mode"].as_s.should eq("urlencoded")
    item3["request"]["body"]["urlencoded"].as_a.size.should eq(2)

    # Check Cookie header
    cookie_header = item3["request"]["header"].as_a.find { |h| h["key"].as_s == "Cookie" }
    cookie_header = cookie_header.should_not be_nil
    cookie_header["value"].as_s.should contain("session=abc123")

    # Check fourth item (GET with query params)
    item4 = items[3]
    item4["name"].as_s.should eq("GET /search")
    item4["request"]["method"].as_s.should eq("GET")
    item4["request"]["url"]["query"].as_a.size.should eq(2)
    query_keys = item4["request"]["url"]["query"].as_a.map(&.["key"].as_s)
    query_keys.should contain("q")
    query_keys.should contain("limit")

    # Check baseUrl variable
    collection["variable"].as_a.size.should eq(1)
    collection["variable"][0]["key"].as_s.should eq("baseUrl")
    collection["variable"][0]["value"].as_s.should eq("http://localhost")
  end

  it "uses custom URL when provided" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new("https://api.example.com"),
    }
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    endpoint = Endpoint.new("/test", "GET")
    builder.print([endpoint])
    output = builder.io.to_s

    collection = JSON.parse(output)
    collection["variable"][0]["value"].as_s.should eq("https://api.example.com")
  end

  it "expands synthetic ANY methods into concrete collection items" do
    options = {
      "debug"   => YAML::Any.new(false),
      "verbose" => YAML::Any.new(false),
      "color"   => YAML::Any.new(false),
      "nolog"   => YAML::Any.new(false),
      "output"  => YAML::Any.new(""),
      "url"     => YAML::Any.new(""),
    }
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    builder.print([Endpoint.new("/wildcard", "ANY")])
    collection = JSON.parse(builder.io.to_s)
    items = collection["item"].as_a
    methods = items.map(&.["request"].["method"].as_s)

    methods.should eq(WILDCARD_HTTP_METHODS)
    methods.includes?("ANY").should be_false
    items.map(&.["name"].as_s).should eq(WILDCARD_HTTP_METHODS.map { |method| "#{method} /wildcard" })
  end
end

describe "OutputBuilderPostman URLs" do
  options = {
    "debug"   => YAML::Any.new(false),
    "verbose" => YAML::Any.new(false),
    "color"   => YAML::Any.new(false),
    "nolog"   => YAML::Any.new(false),
    "output"  => YAML::Any.new(""),
    "url"     => YAML::Any.new(""),
  }

  it "keeps the host of an absolute endpoint instead of {{baseUrl}}" do
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    absolute = Endpoint.new("https://demo.example.com.evil/api/users/{id}", "GET")
    absolute.push_param(Param.new("id", "", "path"))

    builder.print([absolute])
    url = JSON.parse(builder.io.to_s)["item"][0]["request"]["url"]

    url["raw"].as_s.should eq("https://demo.example.com.evil/api/users/:id")
    url["host"].as_a.map(&.as_s).should eq(["demo", "example", "com", "evil"])
    url["protocol"].as_s.should eq("https")
    # The sidebar shows the name alone, so a host-less name would render this
    # and `demo.example.com/api/users/{id}` identically.
    JSON.parse(builder.io.to_s)["item"][0]["name"].as_s
      .should eq("GET demo.example.com.evil/api/users/{id}")
  end

  it "still routes a relative endpoint through {{baseUrl}}" do
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    builder.print([Endpoint.new("/api/users", "GET")])
    url = JSON.parse(builder.io.to_s)["item"][0]["request"]["url"]

    url["raw"].as_s.should eq("{{baseUrl}}/api/users")
    url["host"].as_a.map(&.as_s).should eq(["{{baseUrl}}"])
    url.as_h.has_key?("protocol").should be_false
  end

  it "keeps raw in agreement with the structured query list" do
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    endpoint = Endpoint.new("/search", "GET")
    endpoint.push_param(Param.new("q", "noir", "query"))
    endpoint.push_param(Param.new("page", "2", "query"))

    builder.print([endpoint])
    url = JSON.parse(builder.io.to_s)["item"][0]["request"]["url"]

    url["raw"].as_s.should eq("{{baseUrl}}/search?q=noir&page=2")
    url["query"].as_a.map(&.["key"].as_s).should eq(["q", "page"])
  end

  it "keeps a query string the route itself carries, with no declared param" do
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    # How WordPress addresses an AJAX handler. This builder rebuilds the URL
    # from `uri.path`, so the query used to be dropped outright and the
    # imported request addressed a different handler.
    builder.print([Endpoint.new("/wp-admin/admin-ajax.php?action=get_user_data", "GET")])
    item = JSON.parse(builder.io.to_s)["item"][0]
    url = item["request"]["url"]

    url["raw"].as_s.should eq("{{baseUrl}}/wp-admin/admin-ajax.php?action=get_user_data")
    url["query"].as_a.map(&.["key"].as_s).should eq(["action"])
    url["query"].as_a.map(&.["value"].as_s).should eq(["get_user_data"])
    item["name"].as_s.should eq("GET /wp-admin/admin-ajax.php?action=get_user_data")
  end

  it "does not repeat a pair the route and a declared param both spell out" do
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    # The WordPress analyzer records `action` as a query param on top of the
    # URL that already carries it. Emitting both would produce
    # `?action=get_user_data&action=get_user_data`.
    endpoint = Endpoint.new("/wp-admin/admin-ajax.php?action=get_user_data", "GET")
    endpoint.push_param(Param.new("action", "get_user_data", "query"))

    builder.print([endpoint])
    url = JSON.parse(builder.io.to_s)["item"][0]["request"]["url"]

    url["raw"].as_s.should eq("{{baseUrl}}/wp-admin/admin-ajax.php?action=get_user_data")
    url["query"].as_a.size.should eq(1)
  end

  it "appends a declared param that overrides the route's own value" do
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    # `--pvalue query=…` style override: the later pair is the one servers
    # read, so it survives alongside the route's own.
    endpoint = Endpoint.new("/search?q=old", "GET")
    endpoint.push_param(Param.new("q", "new", "query"))

    builder.print([endpoint])
    url = JSON.parse(builder.io.to_s)["item"][0]["request"]["url"]

    url["raw"].as_s.should eq("{{baseUrl}}/search?q=old&q=new")
    url["query"].as_a.map(&.["value"].as_s).should eq(["old", "new"])
  end

  it "gives endpoints that differ only by query string distinct names" do
    builder = OutputBuilderPostman.new(options)
    builder.io = IO::Memory.new

    # `action` is the only discriminator for WordPress AJAX, so a path-only
    # name renders these two identically in the Postman sidebar.
    builder.print([
      Endpoint.new("/wp-admin/admin-ajax.php?action=get_user_data", "GET"),
      Endpoint.new("/wp-admin/admin-ajax.php?action=save_settings", "GET"),
    ])
    names = JSON.parse(builder.io.to_s)["item"].as_a.map(&.["name"].as_s)

    names.uniq.size.should eq(2)
    names.should eq([
      "GET /wp-admin/admin-ajax.php?action=get_user_data",
      "GET /wp-admin/admin-ajax.php?action=save_settings",
    ])
  end
end
