#!/usr/bin/env crystal
# noir/scripts/generate_supported_docs.cr
# Generate supported documentation pages directly from NoirTechs::TECHS.
#
# No binary build required — requires the techs module directly.
#
# Generates (auto-injected after <!-- AUTOGENERATED--> marker):
#   - docs/content/usage/supported/language_and_frameworks/*.md
#   - docs/content/usage/supported/specification/*.md
#   - docs/content/usage/supported/callee_coverage/*.md
#
# Usage:
#   crystal run scripts/generate_supported_docs.cr -- [options]
#   just docs-supported
#
# Examples:
#   crystal run scripts/generate_supported_docs.cr
#   crystal run scripts/generate_supported_docs.cr -- --dry-run
#   crystal run scripts/generate_supported_docs.cr -- -q
#
# Exit codes:
#   0 - Success
#   2 - Invalid options

require "option_parser"
require "../src/techs/techs"

AUTOGEN_MARKER     = "<!-- AUTOGENERATED-->"
AUTOGEN_END_MARKER = "<!-- /AUTOGENERATED-->"

SPEC_FRIENDLY_NAMES = {
  "android"              => "Android (Manifest)",
  "ios"                  => "iOS (Info.plist)",
  "well_known_applinks"  => "App Links / Universal Links (server-side)",
  "har"                  => "HAR",
  "mitmproxy"            => "mitmproxy Flow",
  "oas2"                 => "OpenAPI 2.0 (Swagger)",
  "oas3"                 => "OpenAPI 3.0",
  "graphql"              => "GraphQL",
  "graphql_sdl"          => "GraphQL SDL",
  "raml"                 => "RAML",
  "postman"              => "Postman Collection",
  "apache_httpd"         => "Apache httpd",
  "aws_cdk"              => "AWS CDK",
  "caddy"                => "Caddy",
  "aws_cloudformation"   => "AWS SAM / CloudFormation",
  "azure_functions"      => "Azure Functions",
  "cloudflare_wrangler"  => "Cloudflare Workers (wrangler)",
  "istio_virtualservice" => "Istio VirtualService",
  "kamal"                => "Kamal",
  "k8s_gateway_api"      => "Kubernetes Gateway API (HTTPRoute)",
  "k8s_ingress"          => "Kubernetes Ingress",
  "nginx"                => "Nginx",
  "serverless_framework" => "Serverless Framework",
  "traefik"              => "Traefik Dynamic Config",
  "typespec"             => "TypeSpec",
}

def check(b : Bool) : String
  b ? "☑️" : "✗"
end

ROUTE_FEATURES = [
  {key: "endpoint", label: "endpoint"},
  {key: "method", label: "method"},
  {key: "query", label: "query"},
  {key: "path", label: "path"},
  {key: "body", label: "body"},
  {key: "header", label: "header"},
  {key: "cookie", label: "cookie"},
  {key: "static_path", label: "static"},
  {key: "websocket", label: "websocket"},
  {key: "callee", label: "callee"},
]

AI_FEATURES = [
  {key: "guards", label: "guards"},
  {key: "sinks", label: "sinks"},
  {key: "validators", label: "validators"},
  {key: "signals", label: "signals"},
]

def project_root : String
  script_dir = File.dirname(File.expand_path(__FILE__))
  File.basename(script_dir) == "scripts" ? File.expand_path("..", script_dir) : script_dir
end

def ensure_parent_dir(path : String)
  dir = File.dirname(path)
  Dir.mkdir_p(dir) unless Dir.exists?(dir)
end

# Extract per-feature support map from a tech's supported JSON.
def feature_flags(tech : String, supported : JSON::Any) : Hash(String, Bool)
  h = supported.as_h
  params = h["params"]?.try(&.as_h) || {} of String => JSON::Any
  {
    "endpoint"    => h["endpoint"]?.try(&.as_bool) || false,
    "method"      => h["method"]?.try(&.as_bool) || false,
    "query"       => params["query"]?.try(&.as_bool) || false,
    "path"        => params["path"]?.try(&.as_bool) || false,
    "body"        => params["body"]?.try(&.as_bool) || false,
    "header"      => params["header"]?.try(&.as_bool) || false,
    "cookie"      => params["cookie"]?.try(&.as_bool) || false,
    "static_path" => h["static_path"]?.try(&.as_bool) || false,
    "websocket"   => h["websocket"]?.try(&.as_bool) || false,
    "callee"      => NoirTechs.context_supported?(tech, "callee"),
    "guards"      => NoirTechs.context_supported?(tech, "guards"),
    "sinks"       => NoirTechs.context_supported?(tech, "sinks"),
    "validators"  => NoirTechs.context_supported?(tech, "validators"),
    "signals"     => NoirTechs.context_supported?(tech, "signals"),
  }
end

# Render a chip row for a feature group.
def chip_row(flags : Hash(String, Bool), features : Array(NamedTuple(key: String, label: String)), label : String) : String
  io = IO::Memory.new
  io << %(    <div class="tech-card-row">\n)
  io << %(      <span class="tech-card-label">#{label}</span>\n)
  io << %(      <div class="tech-card-chips">\n)
  features.each do |f|
    state = flags[f[:key]] ? "on" : "off"
    io << %(        <span class="tech-chip #{state}">#{f[:label]}</span>\n)
  end
  io << %(      </div>\n)
  io << %(    </div>\n)
  io.to_s
end

# Render a single framework card.
def framework_card(name : String, flags : Hash(String, Bool)) : String
  io = IO::Memory.new
  io << %(  <article class="tech-card">\n)
  io << %(    <h3 class="tech-card-title">#{name}</h3>\n)
  io << chip_row(flags, ROUTE_FEATURES, "Route")
  io << chip_row(flags, AI_FEATURES, "AI Context")
  io << %(  </article>\n)
  io.to_s
end

LEGEND_HTML = <<-HTML
  <div class="tech-legend">
    <span class="tech-legend-item"><span class="tech-chip on">supported</span> available out of the box</span>
    <span class="tech-legend-item"><span class="tech-chip off">supported</span> not yet implemented</span>
  </div>
  HTML

# Generate language/framework card grids grouped by language.
def generate_language_tables(data : JSON::Any) : String
  by_language = Hash(String, Array({name: String, flags: Hash(String, Bool)})).new { |h, k| h[k] = [] of {name: String, flags: Hash(String, Bool)} }

  data.as_h.each do |_key, info|
    h = info.as_h
    next unless h.has_key?("language")

    language = h["language"].as_s
    framework = h["framework"]?.try(&.as_s) || ""
    framework = "Pure" if framework.empty?
    by_language[language] << {name: framework, flags: feature_flags(_key, h["supported"])}
  end

  io = IO::Memory.new
  io << LEGEND_HTML
  io << "\n\n"
  by_language.keys.sort!.each do |lang|
    entries = by_language[lang].sort_by { |e| e[:name] }
    io << "## #{lang}\n\n"
    io << %(<div class="tech-grid">\n)
    entries.each do |e|
      io << framework_card(e[:name], e[:flags])
    end
    io << %(</div>\n\n)
  end

  io.to_s
end

SPEC_COLUMNS = ["endpoint", "method", "query", "path", "body", "header", "cookie"]

# Render supported feature cells for the spec table — only the columns that
# specifications can meaningfully support (source-analysis-only columns are
# always unsupported and dropped to keep the table narrow).
def spec_feature_cells(supported : JSON::Any) : String
  h = supported.as_h
  params = h["params"]?.try(&.as_h) || {} of String => JSON::Any
  values = {
    "endpoint" => h["endpoint"]?.try(&.as_bool) || false,
    "method"   => h["method"]?.try(&.as_bool) || false,
    "query"    => params["query"]?.try(&.as_bool) || false,
    "path"     => params["path"]?.try(&.as_bool) || false,
    "body"     => params["body"]?.try(&.as_bool) || false,
    "header"   => params["header"]?.try(&.as_bool) || false,
    "cookie"   => params["cookie"]?.try(&.as_bool) || false,
  }
  SPEC_COLUMNS.map { |c| check(values[c]) }.join(" | ")
end

# Generate specification table
def generate_spec_table(data : JSON::Any) : String
  specs = [] of {name: String, format: String, cells: String}

  data.as_h.each do |key, info|
    h = info.as_h
    next if h.has_key?("language")
    next unless h.has_key?("format")

    name = SPEC_FRIENDLY_NAMES[key]? || key.gsub("_", " ").split.map(&.capitalize).join(" ")
    formats = h["format"].as_a.map(&.as_s)
    cells = spec_feature_cells(h["supported"])

    formats.each do |fmt|
      specs << {name: name, format: fmt, cells: cells}
    end
  end

  specs.sort_by! { |e| e[:name] }

  columns = ["Specification", "Format"] + SPEC_COLUMNS
  separator = columns.map { "---" }

  io = IO::Memory.new
  io << "| #{columns.join(" | ")} |\n"
  io << "|#{separator.join("|")}|\n"
  specs.each do |e|
    io << "| #{e[:name]} | #{e[:format]} | #{e[:cells]} |\n"
  end

  io.to_s
end

# Generate the callee coverage matrix grouped by language.
# Source of truth is NoirTechs::CALLEE_SUPPORTED_TECHS, the same metadata that
# drives the framework callee chips and `noir list techs`, so the matrix never
# drifts from the analyzers.
def generate_callee_table(data : JSON::Any) : String
  by_language = Hash(String, Array(String)).new { |h, k| h[k] = [] of String }

  data.as_h.each do |key, info|
    next unless NoirTechs::CALLEE_SUPPORTED_TECHS.includes?(key)
    h = info.as_h
    next unless h.has_key?("language")

    language = h["language"].as_s
    framework = h["framework"]?.try(&.as_s) || ""
    framework = "Pure" if framework.empty?
    by_language[language] << framework
  end

  io = IO::Memory.new
  io << "| Language | Frameworks with callee coverage |\n"
  io << "|----------|---------------------------------|\n"
  by_language.keys.sort!.each do |lang|
    frameworks = by_language[lang].sort!.join(", ")
    io << "| #{lang} | #{frameworks} |\n"
  end

  io.to_s
end

# Inject generated content after AUTOGEN_MARKER in all .md files in a directory.
# If an AUTOGEN_END_MARKER is present, only the region between the two markers is
# replaced and any hand-written content after the end marker is preserved.
# Otherwise the content from the marker to end-of-file is replaced (legacy behavior).
def inject_autogen(dir : String, content : String, dry_run : Bool) : Array(String)
  updated = [] of String

  Dir.glob(File.join(dir, "*.md")).each do |path|
    file_content = File.read(path)
    parts = file_content.split(AUTOGEN_MARKER, 2)
    next unless parts.size == 2

    if parts[1].includes?(AUTOGEN_END_MARKER)
      tail = parts[1].split(AUTOGEN_END_MARKER, 2)[1]
      new_content = parts[0] + AUTOGEN_MARKER + "\n\n" + content + "\n" + AUTOGEN_END_MARKER + tail
    else
      new_content = parts[0] + AUTOGEN_MARKER + "\n\n" + content
      new_content += "\n" unless new_content.ends_with?("\n")
    end

    unless dry_run
      ensure_parent_dir(path)
      File.write(path, new_content)
    end
    updated << path
  end

  updated
end

# --------------------
# CLI and entry point
# --------------------

quiet = false
dry_run = false
show_help = false

parser = OptionParser.new do |p|
  p.banner = "Usage: crystal run scripts/generate_supported_docs.cr -- [options]"
  p.on("-q", "--quiet", "Quiet mode (suppress output messages)") { quiet = true }
  p.on("--dry-run", "Preview changes without writing files") { dry_run = true }
  p.on("-h", "--help", "Show help") { show_help = true }
end

begin
  parser.parse
rescue ex : OptionParser::Exception
  STDERR.puts ex.message
  STDERR.puts
  STDERR.puts parser
  exit 2
end

if show_help
  puts parser
  puts
  puts "Description:"
  puts "  Generates supported documentation pages from NoirTechs::TECHS."
  puts "  No binary build required."
  puts
  puts "Generates:"
  puts "  - docs/content/usage/supported/language_and_frameworks/*.md"
  puts "  - docs/content/usage/supported/specification/*.md"
  puts "  - docs/content/usage/supported/callee_coverage/*.md"
  puts
  puts "Examples:"
  puts "  crystal run scripts/generate_supported_docs.cr"
  puts "  crystal run scripts/generate_supported_docs.cr -- --dry-run"
  puts "  crystal run scripts/generate_supported_docs.cr -- -q"
  puts "  just docs-supported"
  exit 0
end

root = project_root
data = JSON.parse(NoirTechs::TECHS.to_json)
docs_dir = File.join(root, "docs", "content", "usage", "supported")

# Generate and inject language/framework tables
lang_tables = generate_language_tables(data)
updated = inject_autogen(File.join(docs_dir, "language_and_frameworks"), lang_tables, dry_run)
unless quiet
  prefix = dry_run ? "Would update" : "Updated"
  updated.each { |p| puts "#{prefix}: #{p}" }
end

# Generate and inject specification table
spec_table = generate_spec_table(data)
updated = inject_autogen(File.join(docs_dir, "specification"), spec_table, dry_run)
unless quiet
  prefix = dry_run ? "Would update" : "Updated"
  updated.each { |p| puts "#{prefix}: #{p}" }
end

# Generate and inject callee coverage matrix
callee_table = generate_callee_table(data)
updated = inject_autogen(File.join(docs_dir, "callee_coverage"), callee_table, dry_run)
unless quiet
  prefix = dry_run ? "Would update" : "Updated"
  updated.each { |p| puts "#{prefix}: #{p}" }
end
