require "../../../models/analyzer"
require "../../../miniparsers/groovy_callee_extractor"
require "../../../utils/groovy_literal_scanner"

module Analyzer::Groovy
  # Grails follows a convention-over-configuration layout where each
  # controller class under `grails-app/controllers/` exposes its action
  # methods as URL endpoints. The default URL mapping is
  # `"/$controller/$action?/$id?(.$format)?"`, so we surface every
  # action method as `/<controller>/<action>` (the controller name is
  # the class name with the `Controller` suffix dropped and the first
  # letter lowercased).
  #
  # Two action styles are handled:
  #   * Method form:  `def show() { ... }`
  #   * Closure form: `def show = { ... }`  (legacy Grails)
  #
  # When the controller declares
  #   `static allowedMethods = [save: 'POST', update: ['PUT', 'PATCH']]`
  # those restrictions are honored; otherwise actions are emitted as
  # `GET` (the default Grails dispatch verb when no restriction is set).
  #
  # `UrlMappings.groovy` is also scanned for explicit string-based mappings
  # of the form
  #   `get '/api/users'(controller: 'user', action: 'list')`
  # which are surfaced as additional endpoints. It lives under
  # `grails-app/conf/` on Grails 1.x/2.x and `grails-app/controllers/` on
  # Grails 3+; both locations are handled. Per-verb `action = [GET: ..., PUT:
  # ...]` dispatch maps and `${name}` GString path variables are recognized,
  # while bare-status-code (`"404"`, `"500"`) error mappings are excluded.
  class Grails < Analyzer
    DEFAULT_METHODS = ["GET"]
    HTTP_METHODS    = %w[GET POST PUT DELETE PATCH HEAD OPTIONS]

    # Actions added implicitly by `static scaffold = X` (Grails legacy
    # CRUD scaffolding).
    SCAFFOLD_ACTIONS = [
      {name: "index", method: "GET"},
      {name: "show", method: "GET"},
      {name: "create", method: "GET"},
      {name: "save", method: "POST"},
      {name: "edit", method: "GET"},
      {name: "update", method: "PUT"},
      {name: "delete", method: "DELETE"},
    ]

    # Actions inherited from `RestfulController<T>` (Grails REST base).
    RESTFUL_ACTIONS = [
      {name: "index", method: "GET"},
      {name: "show", method: "GET"},
      {name: "save", method: "POST"},
      {name: "update", method: "PUT"},
      {name: "patch", method: "PATCH"},
      {name: "delete", method: "DELETE"},
    ]

    # Endpoints generated by `(resources: "name")` shortcuts in
    # `UrlMappings.groovy`. Each tuple is suffix appended to the base
    # URL plus the verb.
    RESOURCES_ENDPOINTS = [
      {suffix: "", method: "GET"},
      {suffix: "", method: "POST"},
      {suffix: "/:id", method: "GET"},
      {suffix: "/:id", method: "PUT"},
      {suffix: "/:id", method: "PATCH"},
      {suffix: "/:id", method: "DELETE"},
    ]

    SKIP_ACTION_NAMES = %w[
      beforeInterceptor afterInterceptor afterView allowedMethods
      scaffold defaultAction errors response request params
      responseFormats namespace transactional
    ]

    def analyze
      include_callee = any_to_bool(@options["include_callee"]?) || any_to_bool(@options["ai_context"]?)
      all_files.each do |path|
        next if File.directory?(path)
        next unless path.ends_with?(".groovy")

        content = read_file_content(path)

        if controller_path?(path)
          process_controller(path, content, include_callee)
        end

        if url_mappings_path?(path)
          process_url_mappings(path, content)
        end
      end

      @result
    end

    private def controller_path?(path : String) : Bool
      path.includes?("/grails-app/controllers/")
    end

    private def url_mappings_path?(path : String) : Bool
      # Grails plugins ship their own `<Name>UrlMappings.groovy` files
      # alongside the canonical `UrlMappings.groovy`, so accept any basename
      # ending in `UrlMappings.groovy`. The canonical location changed across
      # Grails versions: 1.x/2.x kept it under `grails-app/conf/`, while
      # Grails 3+ moved it to `grails-app/controllers/`. Accept both so modern
      # apps (the common case today) are not silently skipped.
      return false unless path.includes?("/grails-app/conf/") ||
                          path.includes?("/grails-app/controllers/")
      File.basename(path).ends_with?("UrlMappings.groovy")
    end

    private def process_controller(path : String, content : String, include_callee : Bool)
      cleaned = strip_groovy_comments(content)

      cleaned.scan(/((?:(?:public|protected|private|abstract|final|static)\s+)*)class\s+([A-Z][A-Za-z0-9_]*Controller)\b([^\{]*)\{/) do |match|
        modifiers = match[1]
        class_name = match[2]
        extends_clause = match[3]
        match_end = match.end(0)
        match_start = match.begin(0)
        next unless match_end && match_start
        # Abstract base controllers are templates for subclasses, not
        # directly addressable endpoints — skip them.
        next if modifiers.includes?("abstract")

        body_info = extract_braced_block(cleaned, match_end - 1)
        next unless body_info
        body, body_start = body_info

        controller_name = controller_name_for(class_name)
        allowed_methods = parse_allowed_methods(body)
        actions = extract_actions(body)
        existing_action_names = actions.map { |a| a[:name] }.to_set

        # Inherited actions from a `RestfulController<T>` superclass.
        if extends_restful_controller?(extends_clause)
          RESTFUL_ACTIONS.each do |restful|
            next if existing_action_names.includes?(restful[:name])
            emit_inherited_action(path, content, controller_name,
              restful[:name], restful[:method],
              allowed_methods, match_start)
            existing_action_names << restful[:name]
          end
        end

        # Implicit CRUD added by `static scaffold = X`.
        if has_scaffold?(body)
          SCAFFOLD_ACTIONS.each do |scaff|
            next if existing_action_names.includes?(scaff[:name])
            emit_inherited_action(path, content, controller_name,
              scaff[:name], scaff[:method],
              allowed_methods, match_start)
            existing_action_names << scaff[:name]
          end
        end

        actions.each do |action|
          methods = allowed_methods[action[:name]]? || DEFAULT_METHODS
          line = line_for_offset(content, body_start + action[:offset])
          line = line_for_offset(content, match_start) if line <= 0
          callees = include_callee ? callees_for_action(path, content, body_start, action) : [] of Noir::GroovyCalleeExtractor::Entry
          methods.each do |verb|
            url = "/#{controller_name}/#{action[:name]}"
            details = Details.new(PathInfo.new(path, line))
            endpoint = Endpoint.new(url, verb, [] of Param, details)
            Noir::GroovyCalleeExtractor.attach_to(endpoint, callees)
            @result << endpoint
          end
        end
      end
    end

    private def callees_for_action(path : String,
                                   content : String,
                                   class_body_start : Int32,
                                   action : Action) : Array(Noir::GroovyCalleeExtractor::Entry)
      start_line = line_for_offset(content, class_body_start + action[:body_start])
      Noir::GroovyCalleeExtractor.callees_for_body(action[:body], path, start_line)
    end

    private def extends_restful_controller?(clause : String) : Bool
      clause.matches?(/extends\s+RestfulController\b/)
    end

    private def has_scaffold?(body : String) : Bool
      body.matches?(/static\s+scaffold\s*=/)
    end

    private def emit_inherited_action(path : String, content : String,
                                      controller : String, action_name : String,
                                      default_method : String,
                                      allowed_methods : Hash(String, Array(String)),
                                      class_offset : Int32)
      methods = allowed_methods[action_name]? || [default_method]
      line = line_for_offset(content, class_offset)
      methods.each do |verb|
        url = "/#{controller}/#{action_name}"
        @result << Endpoint.new(url, verb, [] of Param,
          Details.new(PathInfo.new(path, line)))
      end
    end

    private def controller_name_for(class_name : String) : String
      base = class_name
      base = base[0...(base.size - "Controller".size)] if base.ends_with?("Controller")
      return class_name.downcase if base.empty?
      base[0].downcase.to_s + base[1..]
    end

    # JavaBean-style property accessors (`getFoo`, `setFoo`, `isFoo`) follow
    # the `<get|set|is><UpperCase>` convention. Grails treats these as
    # property access, never as routable actions, so they must be excluded
    # from the surfaced endpoint set even though they are public methods.
    private def accessor_name?(name : String) : Bool
      name.matches?(/\A(?:get|set|is)[A-Z]/)
    end

    # Grails only dispatches to *public, non-static* controller methods.
    # A leading `private`/`protected`/`static` modifier therefore disqualifies
    # a method from being a routable action. The char-by-char scanner can land
    # on a method's return-type keyword *after* stepping past its modifier, so
    # the modifier run is captured and checked here rather than relied upon to
    # be absent.
    private def nonpublic_modifier?(modifiers : String?) : Bool
      return false if modifiers.nil?
      modifiers.matches?(/\b(?:private|protected|static)\b/)
    end

    alias Action = NamedTuple(name: String, offset: Int32, body: String, body_start: Int32)

    private def extract_actions(body : String) : Array(Action)
      actions = [] of Action
      depth = 0
      i = 0

      while i < body.size
        c = body[i]

        if literal_end = Noir::GroovyLiteralScanner.skip_literal(body, i)
          i = literal_end
          next
        end

        case c
        when '{'
          depth += 1
          i += 1
          next
        when '}'
          depth -= 1 if depth > 0
          i += 1
          next
        else
          # fall through
        end

        if depth == 0
          rest = body[i..]
          # Method form: `def name(...)`
          # Closure form: `def name = { ... }` — explicitly require the
          # closure brace via lookahead so plain field assignments like
          # `def cache = [:]` or `def bookService = new BookService()`
          # are not mistaken for actions.
          m = rest.match(/\A(public\s+|protected\s+|private\s+)?def\s+([a-z_][A-Za-z0-9_]*)\s*(?:\(|=\s*(?=\{))/)
          if m
            modifier = m[1]?
            name = m[2]
            unless nonpublic_modifier?(modifier) || SKIP_ACTION_NAMES.includes?(name) || accessor_name?(name)
              if action_body = extract_braced_block(body, i + (m.end(0) || 0))
                action_body_text, action_body_start = action_body
                actions << {name: name, offset: i, body: action_body_text, body_start: action_body_start}
              end
            end
            match_end = m.end(0)
            i = match_end ? i + match_end : i + 1
            next
          end

          # Typed-return method form: `<Type> name(...) { ... }`.
          # Grails 3+ allows actions with explicit return types. We
          # require the trailing `{` to avoid matching field declarations
          # like `String name = "x"` or method calls.
          m2 = rest.match(/\A((?:(?:public|protected|private|static|final|synchronized)\s+)*)([A-Z][A-Za-z0-9_]*(?:\s*<[^<>]+>)?(?:\s*\[\s*\])?)\s+([a-z_][A-Za-z0-9_]*)\s*\([^)]*\)\s*(?:throws\s+[A-Za-z0-9_,\s.]+)?\s*\{/)
          if m2
            name = m2[3]
            unless nonpublic_modifier?(m2[1]?) || SKIP_ACTION_NAMES.includes?(name) || accessor_name?(name)
              open_brace = i + (m2.end(0) || 1) - 1
              if action_body = extract_braced_block(body, open_brace)
                action_body_text, action_body_start = action_body
                actions << {name: name, offset: i, body: action_body_text, body_start: action_body_start}
              end
            end
            match_end = m2.end(0)
            i = match_end ? i + match_end : i + 1
            next
          end

          # Void / primitive-return method form: `void name(...) { ... }`,
          # `int count(...) { ... }`. Distinct from the uppercase-return
          # pattern above to avoid colliding with field declarations and
          # `def` actions.
          m3 = rest.match(/\A((?:(?:public|protected|private|static|final|synchronized)\s+)*)(void|int|long|boolean|byte|short|float|double|char)\s+([a-z_][A-Za-z0-9_]*)\s*\([^)]*\)\s*(?:throws\s+[A-Za-z0-9_,\s.]+)?\s*\{/)
          if m3
            name = m3[3]
            unless nonpublic_modifier?(m3[1]?) || SKIP_ACTION_NAMES.includes?(name) || accessor_name?(name)
              open_brace = i + (m3.end(0) || 1) - 1
              if action_body = extract_braced_block(body, open_brace)
                action_body_text, action_body_start = action_body
                actions << {name: name, offset: i, body: action_body_text, body_start: action_body_start}
              end
            end
            match_end = m3.end(0)
            i = match_end ? i + match_end : i + 1
            next
          end
        end

        i += 1
      end

      # De-duplicate while preserving order (multiple matches can occur if
      # a closure-style action is followed by a method-style override).
      seen = Set(String).new
      actions.select do |entry|
        if seen.includes?(entry[:name])
          false
        else
          seen << entry[:name]
          true
        end
      end
    end

    private def parse_allowed_methods(body : String) : Hash(String, Array(String))
      mapping = {} of String => Array(String)
      header = body.match(/static\s+allowedMethods\s*=\s*\[/)
      return mapping unless header
      header_end = header.end(0)
      return mapping unless header_end

      depth = 1
      i = header_end
      while i < body.size && depth > 0
        c = body[i]
        case c
        when '['
          depth += 1
        when ']'
          depth -= 1
          break if depth == 0
        else
          # ignore
        end
        i += 1
      end
      return mapping if depth != 0
      inner = body[header_end...i]
      buffer = String::Builder.new
      entries = [] of String
      list_depth = 0
      inner.each_char do |ch|
        case ch
        when '['
          list_depth += 1
          buffer << ch
        when ']'
          list_depth -= 1 if list_depth > 0
          buffer << ch
        when ','
          if list_depth == 0
            entries << buffer.to_s
            buffer = String::Builder.new
          else
            buffer << ch
          end
        else
          buffer << ch
        end
      end
      tail = buffer.to_s.strip
      entries << tail unless tail.empty?

      entries.each do |entry|
        pair = entry.strip
        next if pair.empty?
        kv = pair.split(':', 2)
        next if kv.size < 2
        key = kv[0].strip.gsub(/['"]/, "")
        next if key.empty?
        value = kv[1].strip
        verbs = extract_method_list(value)
        mapping[key] = verbs unless verbs.empty?
      end

      mapping
    end

    private def extract_method_list(raw : String) : Array(String)
      cleaned = raw.gsub(/[\[\]]/, "")
      cleaned.split(',').compact_map do |token|
        verb = token.strip.gsub(/['"]/, "").upcase
        next unless HTTP_METHODS.includes?(verb)
        verb
      end
    end

    private def process_url_mappings(path : String, content : String)
      cleaned = strip_groovy_comments(content)
      emit_mapping_endpoints(path, content, cleaned, "")
    end

    # Recursively walks a URL mappings closure body, surfacing endpoints
    # for every recognized DSL form. `prefix` accumulates `group` blocks
    # so nested mappings inherit the outer URL prefix.
    private def emit_mapping_endpoints(path : String, content : String,
                                       text : String, prefix : String, base_offset : Int32 = 0)
      # `text` may be a group-body SUBSTRING; base_offset is its start offset in
      # `content` so match offsets resolve to real file line numbers.
      remaining = consume_groups(path, content, text, prefix, base_offset)

      # Verb-prefixed mappings: `get '/users'(controller: ..., action: ...)`.
      # An optional `name <id>:` prefix names the mapping for reverse URL
      # lookup; it does not affect the URL itself but must be tolerated
      # so we don't drop the endpoint.
      pattern = /(?:\bname\s+[A-Za-z_][A-Za-z0-9_]*\s*:\s*)?\b(get|post|put|delete|patch|head|options)\s+(['"])([^'"]+)\2\s*\((.*?)\)/m
      remaining.scan(pattern) do |match|
        verb = match[1].upcase
        url_pattern = prefix + match[3]
        line = line_for_offset(content, base_offset + (match.begin(0) || 0))
        @result << Endpoint.new(translate_pattern(url_pattern), verb,
          extract_path_params(url_pattern),
          Details.new(PathInfo.new(path, line)))
      end

      # Verbless paren-form: `'/path'(controller: ..., action: ...,
      # method: 'POST')`, the `(resources: 'name')` / `(resource: 'name')`
      # REST shortcut, and `'/path'(uri: '/some/where')` redirect-style
      # mappings.
      simple_pattern = /(?:^|\n)\s*(?:name\s+[A-Za-z_][A-Za-z0-9_]*\s*:\s*)?(['"])([^'"]+)\1\s*\(([^)]*?)\)/m
      remaining.scan(simple_pattern) do |match|
        # Response-code mappings (`"404"(...)`, `"500"(...)`) reuse the same
        # paren-form syntax but the "path" is an HTTP status code, not a URL.
        # They are error-page handlers, not addressable endpoints.
        next if status_code_mapping?(match[2])

        url_pattern = prefix + match[2]
        body_args = match[3]
        line = line_for_offset(content, base_offset + (match.begin(0) || 0))

        if body_args.match(/\bresources:\s*['"]/)
          RESOURCES_ENDPOINTS.each do |ep|
            full = url_pattern + ep[:suffix]
            @result << Endpoint.new(translate_pattern(full), ep[:method],
              extract_path_params(full),
              Details.new(PathInfo.new(path, line)))
          end
          next
        end

        # Singular `resource:` (single REST resource — no list endpoint,
        # no `:id`-keyed entries). Common in Grails for singleton resources.
        if body_args.match(/\bresource:\s*['"]/)
          {"GET", "POST", "PUT", "PATCH", "DELETE"}.each do |verb|
            @result << Endpoint.new(translate_pattern(url_pattern), verb,
              extract_path_params(url_pattern),
              Details.new(PathInfo.new(path, line)))
          end
          next
        end

        next unless body_args.includes?("controller:") || body_args.includes?("action:") ||
                    body_args.includes?("view:") || body_args.includes?("uri:")

        # A trailing closure block may declare per-verb action dispatch via
        # `action = [GET: "show", PUT: "apiUpdate"]`. When present, surface one
        # endpoint per HTTP verb rather than the single GET fallback.
        verbs = action_map_verbs_after(remaining, match.end(0))
        if verbs
          verbs.each do |verb|
            @result << Endpoint.new(translate_pattern(url_pattern), verb,
              extract_path_params(url_pattern),
              Details.new(PathInfo.new(path, line)))
          end
          next
        end

        verb = extract_method_arg(body_args) || "GET"
        @result << Endpoint.new(translate_pattern(url_pattern), verb,
          extract_path_params(url_pattern),
          Details.new(PathInfo.new(path, line)))
      end

      # Closure-form mapping: `'/path' { controller = 'foo'; method = 'POST' }`.
      closure_pattern = /(?:^|\n)\s*(['"])([^'"]+)\1\s*\{([^}]*)\}/m
      remaining.scan(closure_pattern) do |match|
        next if status_code_mapping?(match[2])
        url_pattern = prefix + match[2]
        body_block = match[3]
        next unless body_block.match(/\b(controller|action|method|view)\s*=/)
        line = line_for_offset(content, base_offset + (match.begin(0) || 0))
        verb = extract_method_assignment(body_block) || "GET"
        @result << Endpoint.new(translate_pattern(url_pattern), verb,
          extract_path_params(url_pattern),
          Details.new(PathInfo.new(path, line)))
      end
    end

    # Finds every `group "/prefix", { ... }` block, recursively emits
    # endpoints from its body with the prefix applied, and returns a
    # copy of `text` with those blocks blanked out so the caller's
    # subsequent regex passes do not double-process them.
    private def consume_groups(path : String, content : String,
                               text : String, prefix : String, base_offset : Int32 = 0) : String
      mutable = text
      cursor = 0
      while m = mutable.match(/group\s+(['"])([^'"]+)\1\s*,?\s*\{/, cursor)
        group_prefix = m[2]
        match_start = m.begin(0)
        match_end = m.end(0)
        break unless match_start && match_end

        open_brace = match_end - 1 # position of `{`
        close_brace = find_matching_brace(mutable, open_brace)

        if close_brace
          block_body = mutable[(open_brace + 1)...close_brace]
          emit_mapping_endpoints(path, content, block_body, prefix + group_prefix, base_offset + open_brace + 1)
          replacement = " " * (close_brace + 1 - match_start)
          mutable = mutable[0...match_start] + replacement + mutable[(close_brace + 1)..]
          cursor = match_start + replacement.size
        else
          cursor = match_end
        end
      end
      mutable
    end

    private def find_matching_brace(text : String, open_idx : Int32) : Int32?
      return unless open_idx < text.size && text[open_idx] == '{'
      depth = 1
      i = open_idx + 1
      while i < text.size && depth > 0
        if literal_end = Noir::GroovyLiteralScanner.skip_literal(text, i)
          i = literal_end
          next
        end

        c = text[i]
        case c
        when '{'
          depth += 1
        when '}'
          depth -= 1
          return i if depth == 0
        else
          # ignore
        end
        i += 1
      end
      nil
    end

    private def extract_method_assignment(body : String) : String?
      m = body.match(/method\s*=\s*['"]([A-Za-z]+)['"]/)
      return unless m
      verb = m[1].upcase
      HTTP_METHODS.includes?(verb) ? verb : nil
    end

    private def extract_method_arg(body_args : String) : String?
      m = body_args.match(/method:\s*['"]([A-Za-z]+)['"]/)
      return unless m
      verb = m[1].upcase
      HTTP_METHODS.includes?(verb) ? verb : nil
    end

    # Grails response-code mappings (`"404"(...)`, `"500" { ... }`) carry a
    # bare HTTP status code where a URL would normally go. They configure
    # error pages, not routable endpoints, so they must not be surfaced.
    private def status_code_mapping?(raw : String) : Bool
      raw.matches?(/\A\d{3}\z/)
    end

    # Parses the `action = [GET: "show", PUT: "apiUpdate"]` per-verb dispatch
    # map from a closure block that trails a paren-form mapping. `match_end`
    # is the offset just past the closing `)` of the paren form; we only look
    # ahead when the very next token is the opening `{` of that block.
    private def action_map_verbs_after(text : String, match_end : Int32?) : Array(String)?
      return unless match_end
      return if match_end >= text.size

      lead = text[match_end..].match(/\A\s*\{/)
      return unless lead

      brace_pos = match_end + (lead.end(0) || 1) - 1
      close = find_matching_brace(text, brace_pos)
      return unless close

      block = text[(brace_pos + 1)...close]
      map_match = block.match(/\baction\s*=\s*\[([^\]]*)\]/)
      return unless map_match

      verbs = [] of String
      map_match[1].scan(/([A-Za-z]+)\s*:/) do |vm|
        verb = vm[1].upcase
        verbs << verb if HTTP_METHODS.includes?(verb) && !verbs.includes?(verb)
      end
      verbs.empty? ? nil : verbs
    end

    private def translate_pattern(pattern : String) : String
      # `$name` and `${name}` path variables both map to `:name`.
      strip_format_suffix(pattern)
        .gsub(/\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?\??/) { |_, m| ":#{m[1]}" }
    end

    private def extract_path_params(pattern : String) : Array(Param)
      params = [] of Param
      strip_format_suffix(pattern).scan(/\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?/) do |m|
        params << Param.new(m[1], "", "path")
      end
      params
    end

    # Drops the optional Grails content-format suffix `(.$format)?` /
    # `(.${type})` so it does not leak into the surfaced URL as a literal
    # `(.:format)` segment. The suffix denotes optional content negotiation
    # (`.json`, `.xml`), not an actual path component.
    private def strip_format_suffix(pattern : String) : String
      pattern.gsub(/\(\.\$\{?[A-Za-z_][A-Za-z0-9_]*\}?\)\??/, "")
    end

    private def extract_braced_block(text : String, start : Int32) : Tuple(String, Int32)?
      i = start
      while i < text.size && text[i] != '{'
        i += 1
      end
      return if i >= text.size

      body_start = i + 1
      depth = 1
      i += 1

      while i < text.size && depth > 0
        if literal_end = Noir::GroovyLiteralScanner.skip_literal(text, i)
          i = literal_end
          next
        end

        c = text[i]
        case c
        when '{'
          depth += 1
        when '}'
          depth -= 1
          break if depth == 0
        else
          # ignore
        end
        i += 1
      end

      return if depth != 0
      {text[body_start...i], body_start}
    end

    private def strip_groovy_comments(text : String) : String
      result = String::Builder.new
      i = 0

      while i < text.size
        c = text[i]

        if literal_end = Noir::GroovyLiteralScanner.skip_literal(text, i)
          append_source_range(result, text, i, literal_end)
          i = literal_end
          next
        end

        if i + 1 < text.size && c == '/' && text[i + 1] == '/'
          result << ' '
          result << ' '
          i += 2
          while i < text.size && text[i] != '\n'
            result << ' '
            i += 1
          end
          if i < text.size
            result << text[i]
            i += 1
          end
          next
        end

        if i + 1 < text.size && c == '/' && text[i + 1] == '*'
          result << ' '
          result << ' '
          i += 2
          while i + 1 < text.size && !(text[i] == '*' && text[i + 1] == '/')
            result << (text[i] == '\n' ? '\n' : ' ')
            i += 1
          end
          if i + 1 < text.size
            result << ' '
            result << ' '
            i += 2
          end
          next
        end

        result << c
        i += 1
      end

      result.to_s
    end

    private def append_source_range(result : String::Builder, text : String, start : Int32, finish : Int32)
      index = start
      while index < finish && index < text.size
        result << text[index]
        index += 1
      end
    end

    private def line_for_offset(content : String, offset : Int32) : Int32
      return 1 if offset <= 0
      limit = offset > content.size ? content.size : offset
      count = 1
      i = 0
      while i < limit
        count += 1 if content[i] == '\n'
        i += 1
      end
      count
    end
  end
end
